### ISSUE TITLE
Linking of session_tests fails 

### ISSUE THREAD

**Issue by ahsanjav** [gadgetron/gadgetron#1005]
Linking CXX executable apps/storage/session_tests
FAILED: apps/storage/session_tests apps/storage/session_tests[1]_tests.cmake
: && /usr/bin/c++  -fopenmp -Werror=return-type -Werror=terminate -Werror=non-virtual-dtor -Werror=format-overflow -O3 -DNDEBUG   apps/storage/CMakeFiles/session_tests.dir/storage_test.cpp.o apps/storage/CMakeFiles/session_tests.dir/server_test.cpp.o  -o apps/storage/session_tests  -Wl,-rpath,/opt/code/gadgetron/build/gadgets:/opt/code/gadgetron/build/gadgets/plplot:/opt/code/gadgetron/build/gadgets/moco:/opt/code/gadgetron/build/gadgets/cartesian:/opt/code/gadgetron/build/gadgets/grappa:/opt/code/gadgetron/build/gadgets/spiral:/opt/code/gadgetron/build/gadgets/mri_noncartesian:/opt/code/gadgetron/build/gadgets/gpu:/opt/code/gadgetron/build/gadgets/hyper:/opt/code/gadgetron/build/gadgets/radial:/opt/code/gadgetron/build/gadgets/pmri:/opt/code/gadgetron/build/gadgets/fatwater:/opt/code/gadgetron/build/gadgets/epi:/opt/code/gadgetron/build/gadgets/cmr:/opt/code/gadgetron/build/gadgets/interventional_mri:/opt/code/gadgetron/build/gadgets/mri_core:/opt/code/gadgetron/build/toolboxes:/opt/code/gadgetron/build/toolboxes/plplot:/opt/code/gadgetron/build/toolboxes/python:/opt/code/gadgetron/build/toolboxes/image_io:/opt/code/gadgetron/build/toolboxes/denoise:/opt/code/gadgetron/build/toolboxes/pattern_recognition:/opt/code/gadgetron/build/toolboxes/image:/opt/code/gadgetron/build/toolboxes/image/cpu:/opt/code/gadgetron/build/toolboxes/ffd:/opt/code/gadgetron/build/toolboxes/registration:/opt/code/gadgetron/build/toolboxes/registration/optical_flow:/opt/code/gadgetron/build/toolboxes/registration/optical_flow/gpu:/opt/code/gadgetron/build/toolboxes/registration/optical_flow/cpu:/opt/code/gadgetron/build/toolboxes/dwt:/opt/code/gadgetron/build/toolboxes/dwt/cpu:/opt/code/gadgetron/build/toolboxes/dwt/gpu:/opt/code/gadgetron/build/toolboxes/nfft:/opt/code/gadgetron/build/toolboxes/nfft/cpu:/opt/code/gadgetron/build/toolboxes/nfft/gpu:/opt/code/gadgetron/build/toolboxes/deblur:/opt/code/gadgetron/build/toolboxes/fatwater:/opt/code/gadgetron/build/toolboxes/klt:/opt/code/gadgetron/build/toolboxes/klt/cpu:/opt/code/gadgetron/build/toolboxes/mri_image:/opt/code/gadgetron/build/toolboxes/cmr:/opt/code/gadgetron/build/toolboxes/mri:/opt/code/gadgetron/build/toolboxes/mri/hyper:/opt/code/gadgetron/build/toolboxes/mri/epi:/opt/code/gadgetron/build/toolboxes/mri/spiral:/opt/code/gadgetron/build/toolboxes/mri/pmri:/opt/code/gadgetron/build/toolboxes/mri/pmri/gpu:/opt/code/gadgetron/build/toolboxes/mri_core:/opt/code/gadgetron/build/toolboxes/core:/opt/code/gadgetron/build/toolboxes/core/gpu:/opt/code/gadgetron/build/toolboxes/core/cpu:/opt/code/gadgetron/build/toolboxes/core/cpu/hostutils:/opt/code/gadgetron/build/toolboxes/core/cpu/math:/opt/code/gadgetron/build/toolboxes/fft:/opt/code/gadgetron/build/toolboxes/fft/gpu:/opt/code/gadgetron/build/toolboxes/fft/cpu:/opt/code/gadgetron/build/toolboxes/solvers:/opt/code/gadgetron/build/toolboxes/solvers/gpu:/opt/code/gadgetron/build/toolboxes/solvers/cpu:/opt/code/gadgetron/build/toolboxes/operators:/opt/code/gadgetron/build/toolboxes/operators/gpu:/opt/code/gadgetron/build/toolboxes/operators/cpu:/opt/code/gadgetron/build/toolboxes/log:/opt/code/gadgetron/build/core:/opt/code/gadgetron/build/core/distributed:/opt/code/gadgetron/build/core/parallel:/opt/code/gadgetron/build/core/writers:/opt/code/gadgetron/build/core/readers:/usr/local/lib:/usr/lib/x86_64-linux-gnu/hdf5/serial  /usr/lib/x86_64-linux-gnu/libgtest_main.a  apps/storage/libgadgetron_storage.a  core/libgadgetron_core.so.4.1.1  /usr/lib/x86_64-linux-gnu/libgtest.a  toolboxes/core/cpu/libgadgetron_toolbox_cpucore.so.4.1.1  /usr/local/lib/libismrmrd.so.1.5.0  /usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5.so  /usr/lib/x86_64-linux-gnu/libpthread.so  /usr/lib/x86_64-linux-gnu/libsz.so  /usr/lib/x86_64-linux-gnu/libz.so  /usr/lib/x86_64-linux-gnu/libdl.so  -lm  toolboxes/log/libgadgetron_toolbox_log.so.4.1.1  /usr/lib/x86_64-linux-gnu/libboost_system.so.1.71.0  /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.71.0  /usr/lib/x86_64-linux-gnu/libboost_coroutine.so.1.71.0  /usr/lib/x86_64-linux-gnu/libboost_chrono.so.1.71.0  /usr/lib/x86_64-linux-gnu/libboost_context.so.1.71.0  /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.71.0  /usr/lib/x86_64-linux-gnu/libboost_atomic.so.1.71.0  /usr/lib/librocksdb.so  /usr/lib/x86_64-linux-gnu/libboost_date_time.so.1.71.0 && cd /opt/code/gadgetron/build/apps/storage && /usr/bin/cmake -D TEST_TARGET=session_tests -D TEST_EXECUTABLE=/opt/code/gadgetron/build/apps/storage/session_tests -D TEST_EXECUTOR= -D TEST_WORKING_DIR=/opt/code/gadgetron/build/apps/storage -D TEST_EXTRA_ARGS= -D TEST_PROPERTIES= -D TEST_PREFIX= -D TEST_SUFFIX= -D NO_PRETTY_TYPES=FALSE -D NO_PRETTY_VALUES=FALSE -D TEST_LIST=session_tests_TESTS -D CTEST_FILE=/opt/code/gadgetron/build/apps/storage/session_tests[1]_tests.cmake -D TEST_DISCOVERY_TIMEOUT=5 -P /usr/share/cmake-3.16/Modules/GoogleTestAddTests.cmake
/opt/code/gadgetron/build/apps/storage/session_tests: symbol lookup error: /opt/code/gadgetron/build/apps/storage/session_tests: undefined symbol: _ZN9Gadgetron7Storage17istream_from_dataERKSt6vectorIcSaIcEE
CMake Error at /usr/share/cmake-3.16/Modules/GoogleTestAddTests.cmake:40 (message):
  Error running test executable.

    Path: '/opt/code/gadgetron/build/apps/storage/session_tests'
    Result: 127
    Output:

**Comment by ojosephs** [comment]
I think we solved this at today's hangout using nm, ldd and ldconfig. The application was trying to link in an older version of the library from /usr/local/lib, rather than the newly compiled library.

**Comment by ahsanjav** [comment]
This is now resolved. Thanks to @ojosephs and @roopchansinghv.

**Comment by apd47** [comment]
checking libgadgetron_mricore.so with nm, the symbols look like they're there: 
```
(gadgetron) vscode ➜ .../gadgetron/build/gadgets/mri_core (channelGadgetConversions) $ nm -gDC libgadgetron_mricore.so | grep AcquisitionPassthrough
00000000003de038 V gadget_factory_export_AcquisitionPassthroughGadget
00000000000b1800 T Gadgetron::AcquisitionPassthroughGadget::process(Gadgetron::Core::InputChannel<std::tuple<ISMRMRD::AcquisitionHeader, Gadgetron::hoNDArray<std::complex<float> >, std::optional<Gadgetron::hoNDArray<float> > > >&, Gadgetron::Core::OutputChannel&)
                 U Gadgetron::AcquisitionPassthroughGadget::AcquisitionPassthroughGadget(Gadgetron::Core::Context const&, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&)
00000000000a7ab0 T Gadgetron::gadget_factory_AcquisitionPassthroughGadget(Gadgetron::Core::Context const&, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&)
00000000003d2288 V typeinfo for Gadgetron::AcquisitionPassthroughGadget
00000000003677c0 V typeinfo name for Gadgetron::AcquisitionPassthroughGadget
00000000003d2930 V vtable for Gadgetron::AcquisitionPassthroughGadget
```

**Comment by apd47** [comment]
I think I resolved my own error here. In the new AcquisitionPassthroughGadget's header, I was missing a "using", and ended up with a badly formed constructor that would build but wouldn't match the constructor calls that would come into the gadget. 
#fb5d2f8e8885f0ebf91d1e97f72cfde8f8c9f28a
