### ISSUE TITLE
dicom_ismrmrd_utility: PatientSex dicom tag set to empty string if patient_info.patientGender is "O"

### ISSUE THREAD

**Issue by achataigner** [gadgetron/gadgetron#1008]
"O" is the standard value to indicate "Other" sex in the PatientSex dicom tag.
Why is PatientSex set to empty string if patient_info.patientGender is "O" ?

dicom_ismrmrd_utility.cpp line 342:
`
  // Patient Sex
  key.set(0x0010, 0x0040);
  if (patient_info.patientGender) {
      if (*patient_info.patientGender == "O") {
          status = dataset->insertEmptyElement(key);
      }
      else {
          write_dcm_string(dataset, key, patient_info.patientGender->c_str());
      }
  }
  else {
      write_dcm_string(dataset, key, "");
  }
`
Would it be ok to remove this code ?
`
  if (*patient_info.patientGender == "O") {
      status = dataset->insertEmptyElement(key);
  }
`

**Comment by hansenms** [comment]
@kristofferknudsen maybe you can have a look.

And @achataigner, if there is a bug, I would suggest a pull request to fix it.

**Comment by achataigner** [comment]
ok thanks a lot !

**Comment by achataigner** [comment]
here is the pull request: https://github.com/gadgetron/gadgetron/pull/1011
