### ISSUE TITLE
why dependency on boost:coroutine?

### ISSUE THREAD

**Issue by KrisThielemans** [gadgetron/gadgetron#1019]
CMake files say we depend on `boost::coroutine` https://github.com/gadgetron/gadgetron/blob/d7073e9dc3afd8891232c0519ee8fa9eb11b3ab9/apps/storage/CMakeLists.txt#L8
https://github.com/gadgetron/gadgetron/blob/12ffc43debb9bad2e170713006d29dea78d966bf/CMakeLists.txt#L205-L209
but it doesn't seem to be used anywhere at all in the code. Does this really need to be here?

**Comment by KrisThielemans** [comment]
Especially as it is deprecated (over `coroutine2`) already in boost 1.71.0. https://live.boost.org/doc/libs/1_71_0/?view=condensed&sort=boost-version

**Comment by hansenms** [comment]
I don't think it is used. I would suggest trying to take it out....you can put up a PR with it removed and we will run the build pipeline and see, but I don't see it used.

**Comment by hansenms** [comment]
It is being used by the storage server. Hopefully we can remove it when we move to https://github.com/ismrmrd/mrd-storage-server
