### ISSUE TITLE
missing gadgetron.xml.example

### ISSUE THREAD

**Issue by paskino** [gadgetron/gadgetron#1024]
A `gadgetron.xml.example` used to be shipped with previous gadgetron versions, https://github.com/gadgetron/gadgetron/blob/v3.17.0/apps/gadgetron/gadgetron.xml.example

This is also referenced in 
https://github.com/gadgetron/gadgetron/blob/681f5d39cde8faaae6567d43168efcdcbc36e42a/cmake/debian/postinst#L4

and 
https://github.com/gadgetron/gadgetron/blob/681f5d39cde8faaae6567d43168efcdcbc36e42a/chroot/create_chroot_from_base.sh#L86

But now it's nowhere to be found.

**Comment by hansenms** [comment]
The file is no longer used. The references should be removed from the chroot files. In facts, all of the chroot files and debian stuff should be removed as it is not used. We will do some spring cleaning at some point,
