### ISSUE TITLE
ZFP installation failing. Missing && at end of line?

### ISSUE THREAD

**Issue by ojosephs** [gadgetron/gadgetron#1034]
git clone at line 61 is throwing a "fatal: Too many arguments." error and so I don't think zfp is getting built. Missing an && before the \\?

https://github.com/gadgetron/gadgetron/blob/10531591411fea4e16a074a574cd449a60d28ef8/docker/install_ubuntu_dependencies.sh#L57-L67

**Comment by hansenms** [comment]
Yeah, looks like bug. Can ou can put up a PR for fixing that? Unfortunately, we have no tests validating the ZFP compression, so I would be inclined to remove it instead.

**Comment by ojosephs** [comment]
We don't use it. I just noticed the error message during image building. We just _might_ use it for squeezing 1.5 Gbit data through a 1 Gbit port, though, and I think the transmit code is in IceGadgetron (and not sure about Fire). So I'll PR a (three character) fix for now.

**Comment by hansenms** [comment]
@ojosephs I don't think IceGadgetron actually supports the ZFP compression. It supports the NHLBI algorithm (that we have recently improved the performance for). Would it be better to just remove this, since we are not testing it?

**Comment by ojosephs** [comment]
My mistake. Totally. I will do that PR, instead.
