### ISSUE TITLE
HDF5_INCLUDE_DIR should be HDF5_INCLUDE_DIRS

### ISSUE THREAD

**Issue by KrisThielemans** [gadgetron/gadgetron#1042]
see comments in https://github.com/ismrmrd/ismrmrd/issues/112, this problem was fixed in ISMRMRD

**Comment by hansenms** [comment]
PR please.

**Comment by KrisThielemans** [comment]
sorry. very difficult for me at present as we're still transitioning to recent Gadgetron.

By the way, I believe that at least some of these just shouldn't be there at all. Any target that depends on `ISMRMRD::ISMRMRD` would have the include path set.

**Comment by hansenms** [comment]
I suspected that it was not as trivial as a search and replace in the code. I'm trying to have a bit more discipline around the issues and PRs so we don't have a bunch of random, unactionable things sitting around for ages, so I would propose that we close this and when you have a fix/patch, then just put up a PR. Makes sense?
