### ISSUE TITLE
Linking error

### ISSUE THREAD

**Issue by valeryozenne** [gadgetron/gadgetron#1050]
Hi Kristoffer,

Hope you are going well.
I recently did an update of the Gadgetron. I haven't been able to compile it without reverting your last commit. My ismrmrd repo is up to date.
In case, it helps.

Best,
Valéry

```
[ 14%] Building CXX object gadgets/mri_core/CMakeFiles/gadgetron_mricore.dir/IsmrmrdDumpGadget.cpp.o
In file included from /home/vozenne/Dev/gadgetron/gadgets/mri_core/IsmrmrdDumpGadget.h:8,
                 from /home/vozenne/Dev/gadgetron/gadgets/mri_core/IsmrmrdDumpGadget.cpp:1:
/usr/local/include/ismrmrd/dataset.h:13:10: fatal error: hdf5.h: Aucun fichier ou dossier de ce type
   13 | #include <hdf5.h>
```

```
In file included from /home/vozenne/Dev/gadgetron/apps/clients/gadgetron_ismrmrd_client/gadgetron_ismrmrd_client.cpp:22:
/usr/local/include/ismrmrd/dataset.h:13:10: fatal error: hdf5.h: Aucun fichier ou dossier de ce type
   13 | #include <hdf5.h>
```

**Comment by valeryozenne** [comment]
I should precise that it is happening using the Cmake/make/make install version .

I just tested the new Conda approach, except for the 4 packages mentioned by Hui, it is working on my ubuntu 20.

conda install -c bioconda dcmtk
conda install -c cefca plplot

**Comment by hansenms** [comment]
@valeryozenne can you be specific on the repro steps here? What platform? What conditions?
@kristofferknudsen tagging for your awareness since you were mentioned in the issue.

**Comment by valeryozenne** [comment]
I used the up-to-date master branch of gadgetron, this is purely the official repo without any personal code. I always do a fresh compilation before updating our fork. This is running on a ubuntu platform without docker and conda. Dependencies are installed through apt-get install.  
```
cd build
rm -rf *
cmake ../
make 
```
Re adding the two include solves the issue so it is not a big deal.

**Comment by hansenms** [comment]
So trying to interpret what is going on here, but it looks like it can't find the HDF5 include files, is that correct? I am wondering if this was introduce with this PR: https://github.com/gadgetron/gadgetron/pull/1043

Could you try to roll back to before that PR and try again?

**Comment by valeryozenne** [comment]
Yes, re-adding the line from 1043 solve the issue.

So for the test I tried to roll back the the previous commit using
```
 git checkout  021e86eeb8556185ecdd0eeef0ea2d299338cce8
```
but I trigger another issue. I mean, during this interval of time. I have installed and tested the new conda installation: the compilation succeed using the new tutorial. 

now building the gadgetron outside conda for testing the previous commit (I did well deactivate conda and clean the build repo) give the following error as python3 is now for some reasons linking to anaconda instead of the standard /usr/bin/python3.8

```
-- Found Python3: /home/vozenne/anaconda3/lib/libpython3.9.so (found version "3.9.7") found components: Development NumPy Interpreter 
CMake Error at /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake:117 (find_package):
  Found package configuration file:

    /usr/lib/x86_64-linux-gnu/cmake/boost_python-1.71.0/boost_python-config.cmake

  but it set boost_python_FOUND to FALSE so package "boost_python" is
  considered to be NOT FOUND.  Reason given by package:

  No suitable build variant has been found.

  The following variants have been tried and rejected:

  * libboost_python38.so.1.71.0 (3.8, Boost_PYTHON_VERSION=3.9)

  * libboost_python38.a (3.8, Boost_PYTHON_VERSION=3.9)

Call Stack (most recent call first):
  /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake:182 (boost_find_component)
  /usr/share/cmake-3.16/Modules/FindBoost.cmake:443 (find_package)
  CMakeLists.txt:345 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/vozenne/Dev/gadgetron/build/CMakeFiles/CMakeOutput.log".
````
using ccmake I set BUILD_PYTHON_SUPPORT to OFF and succeed to build the gadgetron.

## Summary

* the last commit  is responsible for the first mentionned error with the HDF5 include files

* setting the conda environnement slighty change my ubuntu environnement , some modification should be possible in the ccmake to link back again to /usr/bin/python3.8

**Comment by hansenms** [comment]
@valeryozenne did you complete remove your build folder before trying to build outside the conda environment (to make sure there was no reference in your cmake cache to your conda environment?). Are there any references anywhere in your environment variables to that python install in the conda environment? If you check those things it should be possible to get it to build outside the conda environment. 

For the issue of the HDF5 includes, I may want to bring @KrisThielemans in here for a consult. @KrisThielemans, the change you introduce in #1042 is causing some problems. Could the issue be the version of HDF5 installed on @valeryozenne's machine or is it the version of ISMRMRD. Do you have any thoughts here. We may have to roll back that change?

**Comment by KrisThielemans** [comment]
Regarding the HDF5, I will investigate this more, but it could be a problem in ISMRMRD. Maybe that one is too old?

Could you please give Ubuntu version, cmake version, ISMRMRD version?  It would also be instructive to add the log file of
```
cmake . HDF5_FIND_DEBUG=ON >& cmake.log
```

**Comment by valeryozenne** [comment]
Yes, I haven't seen that conda automatically modify my bash , changing it solve the boost linking error.

So, about the hdf5 issue. Please find below the output of cmake  HDF5_FIND_DEBUG=ON ../

[cmake.log](https://github.com/gadgetron/gadgetron/files/7960892/cmake.log)

**Comment by hansenms** [comment]
@KrisThielemans I think your suggestion about the ISMRMRD version might be relevant. @valeryozenne it would be good to know what version you are using there.

**Comment by KrisThielemans** [comment]
I'm confused. This log says it found
```
-- HDF5: Using hdf5 compiler wrapper to determine C configuration
-- Found HDF5: /usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5.so;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/x86_64-linux-gnu/libsz.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libm.so (found version "1.10.4") found components: C 
```
but I cannot find any reference of ISMRMRD in the log file.

@hansenms is Gadgetron finding HDF5 itself anywhere (I didn't think so)

**Comment by hansenms** [comment]
FindHDF5.cmake is called indirectly from the ISMRMRD configuration: https://github.com/ismrmrd/ismrmrd/blob/master/cmake/ISMRMRDConfig.cmake.in

**Comment by KrisThielemans** [comment]
ok. I believe the `hdf5` is caused by https://github.com/ismrmrd/ismrmrd/issues/184, so I will need to revert #1043 I think. @hansenms what do you think?

**Comment by hansenms** [comment]
@KrisThielemans I think so, yes. @valeryozenne what is the best path from your perspective?

**Comment by hansenms** [comment]
@valeryozenne this has been reverted. Can you confirm and close this please.

**Comment by valeryozenne** [comment]
Sorry for the delay.
Compilation succeeded.
