### ISSUE TITLE
Subdirectory Readme's

### ISSUE THREAD

**Issue by apd47** [gadgetron/gadgetron#1065]
**Is your feature request related to a problem? Please describe.**
Finding what you're looking for within the repository (especially if you're unfamiliar with the project) is difficult, as is keeping an inventory of what gadgets and toolboxes are configured to work together or are updated to the Gadgetron 4.0 classes/styles. Additionally, many gadget and toolbox folders are full of sparely commented code without directions for use or integration within a pipeline (beyond the xml). 

**Describe the solution you'd like**
Add readme's to subdirectories as a form of easily versioned and updateable inline documentation. The links below are strongly WIPs, but might help get an idea across. Scroll to the bottom of pages for in-situ markdown. 

At the "gadgets/toolboxes/etc" level this can be a list with brief categorical descriptions of each subdirectory they contain, similar to https://github.com/apd47/gadgetron/tree/add-subdirectory-readmes/gadgets. 

Within a gadget or toolbox folder, this can be a list of included gadgets like (along with types and inputs to facilitate identification for use in a pipeline) similar to https://github.com/apd47/gadgetron/tree/add-subdirectory-readmes/gadgets/mri_core - possibly with additional brief gadget descriptions, as well as brief summaries of the included configuration xmls and the intent of the subdirectory/its utility (and any relevant publications). 

**Describe alternatives you've considered**
There's ongoing discussion of wiki/website/readthedocs options for long term documentation, but none are in-situ browseable in the repository or facilitate finding a gadget as a base for new work or as a solution to a problem. Additionally, subdirectory readme updates can be standardized, tracked, and enforced as part of the normal pull request process. 

ReadTheDocs is a good solution for allowing contributers to self-document, but requires knowledge of the tooling rather than just adding markup to the PR. These readme's should not be in place of proper API documentation, but instead a low-barrier, immediate way to improve repo usability.

**Comment by hansenms** [comment]
Just to try to keep ourselves honest here:

1. It seems like this adds a fourth type of documentation to manage when we are trying consolidate?
2. I am not sure this is as "easily versioned and updateable inline documentation" as one may think. The major, major challenge here has been to make sure the documentation is updated with the code. Historically, it has been made harder by having it in multiple places and no system that forces a contributor to do it in the PRs. I think (but it's a hypothesis, I don't know) that it would be better if we have one place with documentation (the stuff that turns into readthedocs) and PR reviewers have to get in the habit of checking if documentation is updated.

This reminds me that we should write a PR review guide. Like this:

When you review a PR:

1. Unless this is a small concise, well described in the PR, bug fix. Go and read the "spec" and understand the context. If there is no spec, stop here and ask for one.
2. Check that it works. Don't just look at the code in the browser. Checkout the branch, build it, run the tests and see if it does what it is supposed to. If it doesn't, stop here and ask for that to be fixed. 
3. Check that the documentation is updated accordingly. If it is not, stop here and ask for that.
4. Run the code again and look for memory leaks, etc.
5. Do the line-by-line code review, look for:
      * Pointers that could be null
      * Memory that is not deallocated.
      * Concurrency problems.
      * Unhandled return values and error messages.
      * Etc.

For item 5, we could write a bit of guidance for what you should done.

**Comment by apd47** [comment]
100% agree on the PR review guide. 

>     1. It seems like this adds a fourth type of documentation to manage when we are trying consolidate?

This summarizes my week well. I've gone through everything we currently have, and the biggest realization I've had is that I don't think there's actually any "valid" updated docs. Our ReadTheDocs has hardly anything on it, so may not be worth pursuing unless someone is 1) already familiar with its syntax and 2) willing to keep its separate tree up-to-date. The wiki is out-of-date and shouldn't be used as new reference material. The website is really just a landing page for existing citations of its URL, and possibly for future whole-organization news (including the weekly meeting links or similar). 

>     2. I am not sure this is as "easily versioned and updateable inline documentation" as one may think. The major, major challenge here has been to make sure the documentation is updated with the code. Historically, it has been made harder by having it in multiple places and no system that forces a contributor to do it in the PRs. I think (but it's a hypothesis, I don't know) that it would be better if we have one place with documentation (the stuff that turns into readthedocs) and PR reviewers have to get in the habit of checking if documentation is updated.

This idea is coming from https://github.com/microsoft/MixedRealityToolkit, where it's used pretty universally for folder inventory, instructions, and brief summaries of why something exists and how to use it. 

Your concern is actually the main motivation for this concept, which I wanted to put this out there as an option for a more familiar (markdown) and easily updated alternative going forwards, largely because: 
1) the paths to folders are essentially static, therefore linkable from external tutorials etc (this is actively used by MixedRealityToolkit's external Microsoft tutorials)
2) code and documentation live together, and can be reviewed/PRd together (and enforced, without additional build tools/sites)
3) isn't hosted externally and doesn't require it to be built - meaning its also available in human-readable format within the downloaded repo

Much of the existing wiki content easily 'syncs up' with an existing specific folder. Github supports relative linking of Markdown, so we can have linked tables of contents to sub-directory readmes, as well as supplemental documentation beyond the default-displayed readme.md files as well.

**Comment by hansenms** [comment]
I haven’t looked at that other project. But I think that our problem here is that if for instance a new user is interested in how the pipelines work in general, what types of gadgets one can make, they might (naturally) think that information would be in /gadgets, but that’s actually not where it would be, it would be in /apps/Gadgetron. So I’m not convinced the model is good.

**Comment by apd47** [comment]
In other implementations of this approach I've seen, there's usually still a set of Markdown documentation within root or a docs folder in the vein of GettingStarted.md or similar. Navigation is via relative paths to other markdown files with a Table of Contents in the root directory. 

To expand on your example: currently if you go to apps or apps/gadgetron as a new user, there's nothing to help you understand what that code is for, what it does, etc. Readmes in the subdirectory for [apps](https://github.com/apd47/gadgetron/tree/add-subdirectory-readmes/apps) and [apps/gadgetron](https://github.com/apd47/gadgetron/tree/add-subdirectory-readmes/apps/gadgetron) would help breadcrumb users through the repo, and provide logical homes for instructions. 

The key becomes managing the main repo "readme" in a way that lets you traverse to what you need. But even if most readme's are just a summary of the contents of the folder, I feel like that's better than the status quo of having no instructions, details, etc in many of the gadget or toolbox sub-projects - which seems to also have contributed to the fact that MOCO gadgets exist in 3 different subdirectories, as do GRAPPA gadgets and noncartesian.

**Comment by hansenms** [comment]
Couple of observations and then let’s defer discussion to when we meet:

1. “something better than the status quo” is not really the bar here. Deleting all docs is better than the status quo by far. So let’s aim higher.
2. The fact that things are disorganized (moco in 3 folders, etc) should not be solved by adding bread crumbs in markdown form. It should just be cleaned up.
3. Read the docs can be written in a mix of rst and markdown so the “syntax” should not be an issue.

**Comment by apd47** [comment]
Fair enough

**Comment by hansenms** [comment]
I was looking forward to being convinced on this tomorrow. Change of heart?
