### ISSUE TITLE
Cmake fails at finding Python3, while building using conda

### ISSUE THREAD

**Issue by mscipio** [gadgetron/gadgetron#1066]
**Describe the bug**
I am trying to compile `gadgetron` using  `conda`, but for some reason the cmake is failing at finding the right python path to the executable and packages (aka `numpy`)

This is the instruction I run to build (and the output follows):
```
(gadgetron) celer[0]:gadgetron$ cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DUSE_MKL=ON -DCMAKE_INSTALL_PREFIX=/autofs/space/celer_001/users/michele/code/SIRF/INSTALL /autofs/space/celer_001/users/michele/code/SIRF/SOURCE/gadgetron/
```

The only things I did before running the `make` command are:
- creating a brand new `conda` environment using the `environment.yml` file provided
- cloning the git repo locally

I am surprised I didn't find any issue about this, so there must be something wrong with my setup, but I tried even to manually pass the global variables regarding python with no success:

**To Reproduce**
I am working on `CentOS 8` with `conda 4.11.0`

**Expected behavior**
Compiling successfully, I guess ...
The actual path that I expected the MakeFIle to locate are:
```csh
# have the Python libs been found
set(PYTHONLIBS_FOUND 1)        
# path to python executable
set(PYTHON_EXECUTABLE /autofs/space/celer_001/users/software/miniconda3/envs/gadgetron/bin/python)
# path to the python library
set(PYTHON_LIBRARIES /autofs/space/celer_001/users/software/miniconda3/envs/gadgetron/lib)
set(PYTHON_LIBRARY ${PYTHON_LIBRARIES})
# path to where Python.h is found
set(PYTHON_INCLUDE_DIR3 /autofs/space/celer_001/users/software/miniconda3/envs/gadgetron/include)
set(PYTHON_INCLUDE_DIRS ${PYTHON_INCLUDE_DIR3}/python3.9)
set(Python3_INCLUDE_DIRS ${PYTHON_INCLUDE_DIR3}/python3.9)
set(PYTHON_INCLUDE_PATH ${PYTHON_INCLUDE_DIRS})

set(PYTHON_MAJOR_VERSION 3.9)
set(PYTHONLIBS_VERSION_STRING ${PYTHON_MAJOR_VERSION})
set(Python3_VERSION ${PYTHON_MAJOR_VERSION})
set(Python3_VERSION_MINOR 9)
```

**Logs/Screenshots**
```
-- The CXX compiler identification is GNU 9.4.0
-- The C compiler identification is GNU 9.4.0
-- Check for working CXX compiler: /autofs/space/celer_001/users/software/miniconda3/envs/gadgetron/bin/x86_64-conda-linux-gnu-c++
-- Check for working CXX compiler: /autofs/space/celer_001/users/software/miniconda3/envs/gadgetron/bin/x86_64-conda-linux-gnu-c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /autofs/space/celer_001/users/software/miniconda3/envs/gadgetron/bin/x86_64-conda-linux-gnu-cc
-- Check for working C compiler: /autofs/space/celer_001/users/software/miniconda3/envs/gadgetron/bin/x86_64-conda-linux-gnu-cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for packages in : /autofs/space/celer_001/users/software/ismrmrd/INSTALL
-- Found Git: /usr/bin/git (found version "2.31.1") 
64bit system is found
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
OpenMP multithreading enabled
-- Performing Test COMPILER_SUPPORTS_WRETURNTYPE
-- Performing Test COMPILER_SUPPORTS_WRETURNTYPE - Success
-- Performing Test COMPILER_SUPPORTS_WTERMINATE
-- Performing Test COMPILER_SUPPORTS_WTERMINATE - Success
-- Performing Test COMPILER_SUPPORT_WNON_VIRTUAL
-- Performing Test COMPILER_SUPPORT_WNON_VIRTUAL - Success
-- Performing Test COMPILER_SUPPORT_WOVERFLOW
-- Performing Test COMPILER_SUPPORT_WOVERFLOW - Success
-- Boost 1.71.0 found.
-- Found Boost components:
   coroutine;system;date_time;program_options;filesystem;timer
-- Found CUDA: /usr/pubsw/packages/CUDA/11.1 (found version "11.1") 
Compiling with -gencode arch=compute_60,code=sm_60;-gencode arch=compute_61,code=sm_61;-gencode arch=compute_70,code=sm_70 --std=c++17
-- Found Armadillo: /autofs/space/celer_001/users/software/miniconda3/envs/gadgetron/include (found version "9.900.5") 
-- Found PugiXML: /autofs/space/celer_001/users/software/miniconda3/envs/gadgetron/lib/libpugixml.a  
-- HDF5: Using hdf5 compiler wrapper to determine C configuration
-- Found HDF5: /autofs/space/celer_001/users/software/miniconda3/envs/gadgetron/lib/libhdf5.so;/autofs/space/celer_001/users/software/miniconda3/envs/gadgetron/lib/libcrypto.so;/autofs/space/celer_001/users/software/miniconda3/envs/gadgetron/lib/libcurl.so;/autofs/space/celer_001/users/software/miniconda3/envs/gadgetron/x86_64-conda-linux-gnu/sysroot/usr/lib/librt.so;/autofs/space/celer_001/users/software/miniconda3/envs/gadgetron/x86_64-conda-linux-gnu/sysroot/usr/lib/libpthread.so;/autofs/space/celer_001/users/software/miniconda3/envs/gadgetron/lib/libz.so;/autofs/space/celer_001/users/software/miniconda3/envs/gadgetron/x86_64-conda-linux-gnu/sysroot/usr/lib/libdl.so;/autofs/space/celer_001/users/software/miniconda3/envs/gadgetron/x86_64-conda-linux-gnu/sysroot/usr/lib/libm.so (found version "1.10.6") found components:  C 
FFTW3 UNIX libraries: /autofs/space/celer_001/users/software/miniconda3/envs/gadgetron/lib/libfftw3f.so/autofs/space/celer_001/users/software/miniconda3/envs/gadgetron/lib/libfftw3.so
-- Found FFTW3: /autofs/space/celer_001/users/software/miniconda3/envs/gadgetron/lib/libfftw3f.so  
-- MKL_THREADING = OMP
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of void*
-- Check size of void* - done
-- Checking for [mkl_intel_lp64 - mkl_gnu_thread - mkl_core - gomp - pthread - m - dl]
--   Library mkl_intel_lp64: /autofs/space/celer_001/users/software/miniconda3/envs/gadgetron/lib/libmkl_intel_lp64.so
--   Library mkl_gnu_thread: /autofs/space/celer_001/users/software/miniconda3/envs/gadgetron/lib/libmkl_gnu_thread.so
--   Library mkl_core: /autofs/space/celer_001/users/software/miniconda3/envs/gadgetron/lib/libmkl_core.so
--   Library gomp: -fopenmp
--   Library pthread: /autofs/space/celer_001/users/software/miniconda3/envs/gadgetron/x86_64-conda-linux-gnu/sysroot/usr/lib/libpthread.so
--   Library m: /autofs/space/celer_001/users/software/miniconda3/envs/gadgetron/x86_64-conda-linux-gnu/sysroot/usr/lib/libm.so
--   Library dl: /autofs/space/celer_001/users/software/miniconda3/envs/gadgetron/x86_64-conda-linux-gnu/sysroot/usr/lib/libdl.so
-- Looking for cblas_sgemm
-- Looking for cblas_sgemm - found
-- MKL library found
MKL LIB DIR /lib/intel64
Do not find TORCH_HOME
CMake Error at /autofs/cluster/pubsw/2/pubsw/Linux2-2.3-x86_64/packages/cmake/3.12.2/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Python3 (missing: NumPy) (found version "3.6.8")
Call Stack (most recent call first):
  /autofs/cluster/pubsw/2/pubsw/Linux2-2.3-x86_64/packages/cmake/3.12.2/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /autofs/cluster/pubsw/2/pubsw/Linux2-2.3-x86_64/packages/cmake/3.12.2/share/cmake-3.12/Modules/FindPython/Support.cmake:795 (find_package_handle_standard_args)
  /autofs/cluster/pubsw/2/pubsw/Linux2-2.3-x86_64/packages/cmake/3.12.2/share/cmake-3.12/Modules/FindPython3.cmake:138 (include)
  CMakeLists.txt:344 (find_package)


-- Configuring incomplete, errors occurred!
See also "/autofs/space/celer_001/users/michele/code/SIRF/BUILD/gadgetron/CMakeFiles/CMakeOutput.log".

```

**System Information:**
 - OS: CentOS 8
 - conda environment
 - current master branch

**Comment by hansenms** [comment]
Did you activate the conda environment before running cmake? And also, if you have any "old" stuff in your build folder, please clean that out.....i.e. delete everything in the build folder.

(please use the issue template)

**Comment by mscipio** [comment]
Yes, I am very familiar with conda, and I activated the environment before doing every other thing.
Also, yes, before every new try I made sure to empty the build folder.

I will try to reformat the OP using the template, but I thought I had already provided all the relevant information ...

**Comment by hansenms** [comment]
Hmm....this is strange. This is (as you can see if you check our Docker builds), the flow that we use in our build pipeline. Only variation is that you are on CentOS, not quite sure what this would do, but you never know. We have some folks using it on Fedora, Ubuntu, WSL2. So we have some confidence that the setup works in general. 

Few observations:
* Where it fails to find Python, it actually says that numpy is missing. Could you validate that numpy is in fact working in your conda environment?
* Also, it seems to be finding CUDA 11.1 and not the one installed in the Conda environment, which should be 11.6, which suggests that there is something about your paths in your conda environment that are not quite right. 

Just reading between the lines of the output, it looks like this is some kind of shared cluster environment? Or at least something with centrally managed mounts, etc. There could be special setup in that, which is interfering. 

For us to dig in here, we probably need some kind of repro outside that environment. If you are up for it we can dig in together. What I would suggest you do is create a Dockerfile on a centos 8 base, where you then setup conda (check our conda files for details). Then setup the environment from this repo in there and try the build. If that works, we can maybe work out way backwards to the environment you have. If it doesn't work, then we have a repro that I can take a look at.

**Comment by mscipio** [comment]
I agree this is very strange. I was so excited to see that you supported a conda-based installation as I thought that it would have been very smooth!

I will try again now, after cleaning up my bash profile ... hopefully, that would help a bit.

I am trying to install it on a computer in a network at my center (MGH Martinos Center, in Boston) and I am limited to what is provided by the IT dept. For instance we are not allowed to use Docker on those machine ... But also I am planning to use `gadgetron` together with `SIRF` so I don't think that having it inside a docker would actually work for me, but I might be wrong about this ...

I will keep you updated.
Thanks for the feedback so far!

**Comment by mscipio** [comment]
Solved!

It was indeed an issue with my PATH and .bashrc file. 
For some reason `python` was correctly linked to the python executable installed in the conda environment, but `python3` was not (hence the inability to locate `numpy`)

I have only one last (partially unrelated) question before we can close this.
I was trying to tun the test and so far all are succeeding. However, for some reason one of the GPU-based test is skipped because of not-enough GPU memory.

However, if I had a print statement to the `run_test.py` file, it's clear that I DO have enough memory but what's happening is that most likely the wrong GPU is selected:

```
(gadgetron) [mu512@celer integration]$ python run_tests.py --echo-log-on-failure --timeout=600 -F --stats stats.csv cases/*
```
```
Querying Gadgetron capabilities...
{'version': '4.1.3',
 'build': 'ebc6ff91eb5e7a9bcc893189246e7730b7bba98f', 
'memory': '385327 MB', 
'python': 'YES', 
'julia': 'NO', 
'matlab': 'NO', 
'cuda': 'YES', 
'cuda_memory': ['48601 MB', '16125 MB', '2000 MB']}

Skipped tests:
	cases/external_julia_acquisition_example.cfg (Julia support required.)
	cases/external_matlab_acquisition_example.cfg (MATLAB support required.)
	cases/external_matlab_bucket_example.cfg (MATLAB support required.)
	cases/external_matlab_buffer_example.cfg (MATLAB support required.)
	cases/external_matlab_tiny_example.cfg (MATLAB support required.)
	cases/gpu_golden_radial_mode2_sb.cfg (Not enough graphics memory.)    <====

```

Is there a way I can specify which GPU to use (in this case the one with 48GB of memory)?

**Comment by hansenms** [comment]
First you can check which GPUs Gadgetron sees by running the command `gadgetron --info`. In your case, you will probably see 3 of them. I normally control which GPUs to use by choosing which ones are available in a Docker container, but since you will not be using Docker, you could try to set the environment variable `CUDA_VISIBLE_DEVICES` to target the GPU that you want to use. 

Another thing to look into is the configuration it runs in that test. I think it is https://github.com/gadgetron/gadgetron/blob/master/gadgets/radial/config/golden_radial_mode2_gpusense_sb.xml, and as you can see it selects device `0` in that configuration. You could change that to make the test actually run, but the test script may itself get confused as it tries to check if you have enough, so it will still skip the test.

Try the `CUDA_VISIBLE_DEVICES` first and see if you can control which GPUs Gadgetron sees. I would start there.

**Comment by hansenms** [comment]
Great. I’ll close this then. The conda stuff is pretty new so let us know how it works out. The shared cluster experience is one that we hope to enable with it since they usually offer conda environments these days, but maybe not Docker. Glad it enables you to run the Gadgetron.
