### ISSUE TITLE
Image processing chains and infrastructures

### ISSUE THREAD

**Issue by xueh2** [gadgetron/gadgetron#1074]
The first goal of Gadgetron is to enable high-performance MR reconstruction from kspace data to images. While this goal has been well accomplished with new features added continuously, Gadgetron is found to very suitable for automated image analysis, thanks to its solid data flow infrastructures and flexibility to be extended for new data types. The introduction of deep learning now further encourage to build in image analysis support in gadgetron, as with trained models, many new applications become possible.

There are different attempts to introduce some image analysis into gadgetron (e.g. flow phase extraction, physio-interpolation for cine images etc.). We still do not have a top-down design. 

**Justification**
The reason to introduce these features is to support a more uniformed image analysis workflow, and to enable efficient building of new applications and to enable design end-to-end applications, including both kspace reconstruction and analysis with automation.

Another justification is there are good components and mechanisms already in Gadgetron. Extended to image processing seems not far-reaching.

**Scenarios**
A few usecases can be listed here:

a) Image denoising and enhancement: the real-time cine data is reconstructed with current generic chain. The image enhancement gadget receives the images and applies models to improve SNR or conduct super-resolution. Test is to compare the final output images and to compare raw and processed images.

b) Cardiac long-axis landmark detection: the purpose is to detect key landmarks (e.g. valve points and apical points) to measure longitudinal contractility. The chain setup is to recon the cine images with generic chain, with the on-the-fly triggering by slice. The image analysis chain buffers incoming images. If all images for a slice arrived, the pack of images is sent for processing. The model will be called up detect landmarks and results are plotted to resulting image series as well as stored into the meta fields.

c) Pure image processing chain for image denoising: this usecase is to have a chain with only the image processing part of processing. The chain will start with reader/writer of images and have the buffering scheme. Once sufficient images are buffered, it will be forwarded for processing. The testing will involve both the image client and result image series.

**Design and implementation**

Some components are already implemented in Gadgetron: ImageReader and ImageWriter, ImageBufferandTrigger gadgets. 

New components to add:

a) gadgetron_ismrmrd_image_client: the client application to send images. The key convention is user will specify which image series to send. E.g. if an application requires to send two image series (10 and 20):

gadgetron_ismrmrd_image_client -f image.h5 -c Image_processing_chain.xml -s 10 20

The client will read in image series 10 and send out images as the order of images stored in the series; after sending all images in series 10, it will send out series 20 etc.

--> This convention will not be arbitrarily flexible, but should handle many usecases.

b) Add gadgets and models for image denoising

c) Helper and utility functions to stream images and image arrays

d) Add manual pages and examples to the documentation

**Test Strategy**
For the combined kspace and image processing chains, the existing testing method will be sufficient, to compare the image values.

Optional: add the support to compare meta fields.

For the pure image processing chain, the existing testing framework requires extensions to call the image client and to specify which image series to be send out in order. The comparison will be on the resulting series pixel values and meta fields.

**Maintenance**
A new set of integration test cases will be added for proposed usecases. What is new here is to add ismrmrd image h5 file as test inputs. The image client will be called up to read in the testing h5 images and send them to Gadgetron for image-only processing.

@xueh2 will maintain these features.

**Other**
None

**Comment by xueh2** [comment]
This is a draft to add image analysis chains. Please comment on the plan.

**Comment by hansenms** [comment]
This sounds like a good plan @xueh2. Let's put this on the agenda for discussion in the meeting tomorrow. Some things to discuss:

1. Should we do related work in ISMRMRD/MRD to support the idea of playing back images from an output file. What we are missing is some kind of index in the file. This is also relevant for waveforms, so a topic to discuss. 
2. Should this be an image client or just added the existing client. I think the image client makes sense, but we should then untangle share components from the current client so we can reuse those in two different clients. So some refactoring for this. 
3. For testing, this adds a different kind of flow with a new type of client. It can certainly be added to the current test framework but every time I consider something like that I feel an urge to redo the custom framework we have based on pytest and fixtures, which I think will be more expandable and configurable. Another topic to discuss. 
4. I think we should break this down in the smallest minimum end-to-end version we can have and work through that use case first. 
5. Are there use cases where we need to send both images and raw data? If so, how does that affect this proposal?

**Comment by xueh2** [comment]
This issue is moved to discussion #1143 . Close the issue here.
