### ISSUE TITLE
anaconda  IsmrmrdDumpGadget, find pre-set ip for no-data-saving 

### ISSUE THREAD

**Issue by SoftVision17** [gadgetron/gadgetron#1103]
Dear Gadgetron Team

I have a problem to use IsmrmrdDumpGadget on my config file, it's like I don't have any information in storage IP, and the same config file is working in old gadgetron version 3.15 .  

**To Reproduce**

1. Start with clean Debian 10 VM '...'
2. Install and compile gadgetron with anaconda 
3. use in the config file  with a IsmrmrdDumpGadget
4. error 
![error_dump](https://user-images.githubusercontent.com/100497592/169622757-f1399411-3ae8-48f0-b665-bab08d4e1f16.PNG)

**Expected behavior**

I expect normaly to get a dump of .h5 in /tmp/gadgetron_data/ 

**System Information:**
 - OS: Debian 10
 - Install/deployment method [conda environment, local compile]
 - Version  : Master branche 
 - commit : 7d91c40a4398cdb7fd383733dfdfbb325ad7cf52

**Comment by hansenms** [comment]
Do you have `ifconfig` installed? (do `sudo apt install net-tools` if not)?

**Comment by SoftVision17** [comment]
Thank you for your response @hansenms . I have the net-tools installed ,  and this is the result of the command .
![sudo_ifconfig](https://user-images.githubusercontent.com/100497592/169817766-ff1e2f59-09e4-43f3-948c-69598ab6582c.PNG)

**Comment by roopchansinghv** [comment]
It should.  You can also try:

   `ip -a address`

which gives very similar, though not identical info, and is installed by default.  Also does **not** need sudo access to run.

**Comment by hansenms** [comment]
The problem is really this [crime](https://github.com/gadgetron/gadgetron/blob/master/toolboxes/core/cpu/hostutils/network_utils.cpp#L42) which means that the dump gadget will fail (unelegantly) if it cannot access `ifconfig`. I'm not 100% sure that is the issue here, but I have had problems with that in the past.

**Comment by SoftVision17** [comment]
Yes, it is this problem, the same. I have modified the privilege (without using sudo) for ifconfig and it's fixed for me. Thank you a lot .
