### ISSUE TITLE
gadgetron is not built from source code in docker images for the dev builds

### ISSUE THREAD

**Issue by ahsanjav** [gadgetron/gadgetron#1116]
**Describe the bug**
The section of the docker file that should install gadgetron for the dev build is not executed. 

**To Reproduce**
Steps to reproduce the behavior, :
1. clone the gadgetron repository
2. run the './build-images.sh --type dev'
3. See that gadgetron_cudabuild layer is never added. 

**Expected behavior**
I expected that layer to be added and gadgetron to be built in the docker images using the source code being used to build the docker images. 

**System Information:**
 - OS: Ubuntu 20.04

**Additional context**
I was trying to add our out of tree builds to the Docker file when I stumbled upon this issue. I wanted to see if my diagnosis is correct or if I am missing something.

**Comment by hansenms** [comment]
It is not meant to be added. The dev images don't actually have gadgetron installed in them. They are meant to build the Gadgetron in them. You are maybe looking for something that is a hybrid between the runtime and the dev images?
