### ISSUE TITLE
CSM INATI DUMP from gadgetron (debug_folder not dumping DATA)

### ISSUE THREAD

**Issue by SoftVision17** [gadgetron/gadgetron#1127]
**Describe the bug**
My objective is to dump a Coils map sensitivity  from Inati estimation in gadgetron 
for that i added a value in debug folder as you can see in the image bellow but I got nothing. 

** information aboute my system : 
   gadgetron installed with conda 
   SHA1 : 2fd257dc0f637d78d4ceafccbe6a533e49d8a80a
   I have tested this in VM debian 10
   and in server Debian 10

**Expected behavior**
I was expected to have some data to analyse and see if I can get the CSM from gadgetron 
![CSM](https://user-images.githubusercontent.com/100497592/180012876-f519648d-9e5c-4c22-b01c-dfc08d93121a.PNG)

**Comment by xueh2** [comment]
This is correct. Can you check /tmp/data folder is created after running the chain? 

Sometimes the write/read permission can prevent writing out the data.

**Comment by SoftVision17** [comment]
your right i will close the issue .it was  in write permission for group part in our server, Thank you for your guidance.
