### ISSUE TITLE
gadgetron dump complex image reconstruction(Phase+ magnitude)

### ISSUE THREAD

**Issue by SoftVision17** [gadgetron/gadgetron#1152]
Dear all,

I'm working on under-sampling data with GRAPPA .
I want to know if gadgetron allow us to get a complex image after a reconstruction to be able to get the the magnitude and phase in the same time. i have tried but nothing work .  
If you have please any hint or ideas.

Best regards,

**Comment by hansenms** [comment]
Yes, complex images are produced before magnitude and phase are extracted. When you say you have tried, could you give a few specifics? What did you try? How did it fail?
