### ISSUE TITLE
Gadgetron environment.yml has incompatible packages stored

### ISSUE THREAD

**Issue by ZhengLiu97** [gadgetron/gadgetron#1185]
**Describe the bug**
conda ```environment.yml``` has incompatible packages, caused failure of environment creation both in Ubuntu and DevContainer.

**To Reproduce**
run ```conda env create -f environment.yml```

**Logs/Screenshots**
![image](https://user-images.githubusercontent.com/65115609/206867313-b32f8562-0ed0-45cd-b42f-e5a2f3a3424e.png)

**System Information:**
 - OS: Ubuntu20.04 in Windows11 WSL2 (also DevContainer in gadgetron)

**Comment by hansenms** [comment]
Yes, thanks for flagging this in an issue. Some packages broke for us and we are looking into it. The prebuilt containers still work so you can reference a known image in your devcontainer.json for now until we get the right fix in.

Basically nvidia broke their packages (again) and we need to update boost. It’s a bit of a puzzle but I’m working on it.

**Comment by ZhengLiu97** [comment]
Thank you so much for your reply! 
I'm not quite sure about where should I modify. Should I modify the value  of ```cacheFrom``` to ```ghcr.io/gadgetron/gadgetron/gadgetron_ubuntu_dev_cuda:20221121.1```?
```
	"build": {
		"dockerfile": "../Dockerfile",
		"target": "gadgetron_dev_cuda",
		"context": "../",
		"cacheFrom": "ghcr.io/gadgetron/gadgetron/gadgetron_ubuntu_dev_cuda:20221121.1",
	},
```

**Comment by hansenms** [comment]
Something like this should do it:

```jsonc
{
        "name": "Gadgetron",
	"image": "ghcr.io/gadgetron/gadgetron/gadgetron_ubuntu_dev_cuda:20221121.1",
	// "build": {
	// 	"dockerfile": "../Dockerfile",
	// 	"target": "gadgetron_dev_cuda",
	// 	"context": "../",
	// 	"cacheFrom": "ghcr.io/gadgetron/gadgetron/gadgetron_ubuntu_dev_cuda:latest",
	// },

       //  .... rest of file  
}
```

**Comment by ZhengLiu97** [comment]
Thanks. BTW, if there is no cuda in my pc, should I use gadgetron_ubuntu_dev_nocuda?

**Comment by hansenms** [comment]
There is no harm in using the cuda images, but the nocuda image is smaller (faster to pull) so you might as well use that if you don't need the GPU stuff. Either way is fine though.

**Comment by hansenms** [comment]
@ZhengLiu97, PR is up to fix this. #1187

**Comment by ZhengLiu97** [comment]
Excellent!
