### ISSUE TITLE
Error building dicom_ismrmrd_utility.cpp

### ISSUE THREAD

**Issue by paskino** [gadgetron/gadgetron#1201]
**Describe the bug**

I am building Gadgetron master on a Ubuntu 22.04 machine, from the[ `SIRF-SuperBuild` ](https://github.com/SyneRBI/SIRF-SuperBuild)chain. Gadgetron fails to build because of this line, which seems to have been changed in #1193.
https://github.com/gadgetron/gadgetron/blob/a0318d1349dce1b9799cb9f6b4486c6cfc5e0c7f/gadgets/dicom/dicom_ismrmrd_utility.cpp#L208

The failure arises as warnings get translated into build [errors](https://github.com/gadgetron/gadgetron/blob/a0318d1349dce1b9799cb9f6b4486c6cfc5e0c7f/CMakeLists.txt#L166-L183).

The [error ](https://github.com/SyneRBI/SIRF-SuperBuild/pull/438#issuecomment-1443493867)is 
```
/opt/SIRF-SuperBuild/sources/Gadgetron/gadgets/dicom/dicom_ismrmrd_utility.cpp:208:44: error: format '%lld' expects argument of type 'long long int', but argument 4 has type 'long int' [-Werror=format=]
  208 |                 snprintf(buf, BUFSIZE, "%lld", *study_info.accessionNumber);
      |                                         ~~~^   ~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                            |   |
      |                                            |   long int
      |                                            long long int
      |                                         %ld
cc1plus: all warnings being treated as errors

```

Changing to `snprintf(buf, BUFSIZE, "%ld", *study_info.accessionNumber);` in my build seems to fix it.

I am building ISMRMRD master, [`3cb9cabaa01fad0164eccfb80fe9678471911dbd`](https://github.com/ismrmrd/ismrmrd/commit/3cb9cabaa01fad0164eccfb80fe9678471911dbd).

**Expected behavior**
Build to succeed. 

**Logs/Screenshots**
If applicable, add screenshots or logs to help explain your problem.

**System Information:**
 - OS: Linux, Ubuntu 22.04
 - Compiler: g++ (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
 - Install/deployment method docker image, local compile
 - Version master

**Additional context**

**Comment by hansenms** [comment]
@roopchansinghv

**Comment by paskino** [comment]
For the record the `accessionNumber` is a `std::int64_t` 
https://github.com/ismrmrd/ismrmrd/blob/838840dd17a1267304785b09783646d3d19ee678/include/ismrmrd/xml.h#L196
