### ISSUE TITLE
unused variable

### ISSUE THREAD

**Issue by maddin200** [gadgetron/gadgetron#1214]
/core/Gadget.cpp line 6
code:
std::string Gadget::get_string_value(const char *name) {
        std::string str_val; // <- unused
        GadgetPropertyBase *p = find_property(name);
        if (!p) {
            GERROR("Property %s\n", name);
            throw std::runtime_error(
                    "Attempting to access non existent property on Gadget");
        }
        return std::string(p->string_value());
    }

**Comment by hansenms** [comment]
Please put up a PR

**Comment by maddin200** [comment]
see https://github.com/gadgetron/gadgetron/pull/1217
