### ISSUE TITLE
Forbidden 'intel' channel - building the gadgetron environment

### ISSUE THREAD

**Issue by joeyplum** [gadgetron/gadgetron#1261]
Hi gadgetron community,

Posting this here in case anybody else experiences a similar bug...

When installing the gadgetron environment from environment.yml using: 
`mamba env create -f environment.yml`,

I experience the following problem: 
![image](https://github.com/gadgetron/gadgetron/assets/75384637/2bcc5ff3-a493-455b-8009-6a46f825b50d)

The problem seems to be consistent as of early July with other conda users looking for the Intel channel:
https://community.intel.com/t5/Intel-Integrated-Performance/Problems-installing-with-conda-HTTP-403-FORBIDDEN/td-p/1611876)

I haven't spent too long verifying if this is the case, but it appears that the Intel channel has been removed from conda. For the meantime, it may be possible to install the gadgetron environment without `intel` and subsequently, `memkind`... but perhaps the community has some better ideas?

Thanks!

**Comment by roopchansinghv** [comment]
Seems this issues has been address in [this commit](https://github.com/gadgetron/gadgetron/commit/9f88dcda0705a99a15492489fb89766860f7becc).  If no objections, we should close this issue.

**Comment by joeyplum** [comment]
I agree--looks to be solved now. Happy to close. Thank you both!
