### ISSUE TITLE
Make CloudBus compatible with AWS

### ISSUE THREAD

**Issue by hansenms** [gadgetron/gadgetron#132]
@gtdeveloper5 was trying to prepare some cloud images using the latest version of the Gadgetron and we ran into a bad problem. 

When we implemented the CloudBus (as a replacement to the static text files for lists of which nodes are available), we used multicasting, but apparently is not supported on AWS or other cloud providers. For an enlightening (but not ultimately uplifting) discussion see here: 

http://www.ravellosystems.com/blog/cloud-networking-ip-broadcasting-multicasting-amazon-ec2/

To make a long story short the cloud nodes cannot see each other. So we have to come up with a different solution. This issue is to start this discussion and figure out what the right model is. 

Basically we have to resort to unicast only to make this work. This means that there has to be some sort of messaging relay (ie all hosts report into some central cloud bus) and that is where other nodes will get their information from. In some sense that makes a few things easier, for instance, we spend some energy on generating unique IDs to identify hosts, that is no longer needed. The multicasting architecture also made it difficult or impossible to make a cluster that was not comprised of nodes co-located on the same subnet. That would resolved with a unicasting approach and we could even make it more sophisticated (see below)

But it also creates some other problems. 

The first decision to make is should this cloudbus relay be part of a specific running Gadgetron instance or should it simply be a standalone server application that machines can report into? I actually think it should be a separate component so that this service does not stop/start (or worse crash) when a Gadgetron instances stop/starts. Since this would now be a central service, multiple nodes will be affected badly if the node running the relay crashes. 

If we pick such an architecture, we could add some sophistication (either initially or at a later date) to allow a host to "report in" to the CloudBusRelay and at the same time start a reverse tunnel into the gadgetron instance. With that it would be possible to join multiple hosts across many networks (and behind firewalls) and have clients simply connect to mapped ports on the CloudBus relay and transparently distribute the work. It would be possible to create a global Gadgetron cluster with many participating nodes. Just some thoughts, let me hear comments on that.

So my proposal would probably be that we:

1. Create a standalone CloudBusRelay
2. The Gadgetron nodes would have to have the IP (and port) of this relay in the gadgetron.xml configuration file.
3. Have the nodes join (report in) to the CloudBusRelay when they start (with IP and port).
4. The nodes should probably maintain an open socket to this relay as long as they are "alive" breaking the connection would be an indication that the nodes are no longer available. 
5. Provide some interface for hosts to query this CloudBusRelay for which nodes are available at any given time. 
6. At a later date explore the reverse tunneling stuff. 

This is some serious work, so in the mean time, we need an alternative. 

@gtdeveloper5, does the text files still work as a fallback?

@naegelejd, @inati, @gtdeveloper5, @dchansen I would like to hear your comments. Let's discuss.

**Comment by naegelejd** [comment]
Your proposal looks fine and makes sense to me. I need to better familiarize myself with the CloudBus infrastructure to get a better sense of its role in the Gadgetron but this does sound like some serious work. I think any real effort should be saved until after a good amount of discussion about design. For example, you mention adding some sophistication to allow a host to "report in" to the CloudBusRelay, but I see this as necessary and expect it in a centralized messaging framework.

**Comment by hansenms** [comment]
@naegelejd, thanks for comments. I think I wasn't clear. It is of course necessary for the nodes to "report in". As far as sophisticated features go, I mean that we could add the ability for them to open a reverse tunnel when they report in so that they would be accessible through the CloudBusRelay even if they are behind a firewall or other restrictions.

**Comment by naegelejd** [comment]
OK yes of course. I think the central CloudBus should be a standalone server application. How difficult would it be to implement a central CloudBusRelay app that maintains a list of nodes, adds to that list when a node connects ("reports in"), and loops through that list to distribute work?

Is it necessary to have an alternative solution to your full proposal in the meantime? If the static text files are working then we can discuss designing/implementing your full proposal rather than an intermediate solution.

**Comment by gtdeveloper5** [comment]
To support the multiple scanner connection, should CloudBusRelay also take the responsibilities to start/stop amazon VPC and nodes? 

E.g., one case is multiple scanners are connected to amazon. A single CloudBusRelay will setup nodes when a scanner connection request comes in and establish the tunneling between gateway nodes and scanner connection point. Then further data transfer will happen between the gateway node and scanner without going through the cloudbus relay. When the job on these nodes are done, nodes should report this status to CloudBusRelay. Relay can take back those nodes and allocates them for next scanner request.

Maybe a white board discussion will be helpful? I agree that we shouldn't need an intermediate solution.

I am updating cloud ui scripts to make current static text based solution updated with the chroot installed amazon instance.

**Comment by hansenms** [comment]
The CloudBus should definitely NOT start and stop Amazon stuff. It should be generic and independent of a specific deployment strategy.

For AWS Deployment, we could add some monitoring features that would allow an external instance to monitor the load on the cloud bus and trigger autoscaling on AWS, but that is a secondary concern right now.

**Comment by hansenms** [comment]
I am closing this one. The new gadgetron_cloudbus_relay fixes this
