### ISSUE TITLE
Convert remaining gadgets to new property interfaces

### ISSUE THREAD

**Issue by hansenms** [gadgetron/gadgetron#143]
We still have some gadgets in there using the "old" parameters and not the new declared properties. I would like to do away with the old ones and enforce declared properties. This is the first step in doing some structures help on setting these parameters. 

@gtdeveloper5, gtplus gadgets need to be converted. 
@inati, @naegelejd, Matlab gadgets
@dchansen, hyper gadgets.

**Comment by naegelejd** [comment]
I'm doing the Matlab gadgets now to familiarize myself with the
GADGET_PROPERTY.

--
Joe Naegele
joseph.naegele@gmail.com
josephnaegele.com
301.676.1403
