### ISSUE TITLE
Cannot build standalone gadgetron-ismrmrd-client binary without boost-filesystem and boost-python

### ISSUE THREAD

**Issue by ghisvail** [gadgetron/gadgetron#150]
Boost-filesystem is forced by the main CMakeLists.txt
Boost-python is forced by toolboxes/CMakeLists.txt

I don't know if the goal is still to allow the gadgetron source tree to build at least the client app if its dependencies are present, i.e. HDF5, ISMRMRD and boost-{po,thread,system}. At the moment, this is not the case.

**Comment by hansenms** [comment]
I guess we have only really said, is boost there or not. This can certainly be changed...by somebody with the appropriate motivation;)

**Comment by ghisvail** [comment]
Indeed in #92 you mentioned Boost (as a whole) and not the minimum set of Boost components the client relies on. This issue results from my misinterpretation, sorry about that.

**Comment by naegelejd** [comment]
I think this is worth fixing though. I started looking at it but I just want to make sure no one else is fixing it too.

**Comment by ghisvail** [comment]
Please go ahead @naegelejd

**Comment by naegelejd** [comment]
Actually I changed my mind. Boost-filesystem is a requirement of both `gadgetron_info` and `gadgetron` itself. They *should* be required in the top-level CMakeLists.txt.

An alternative solution to the client Boost dependency issue is to ensure that the `gadgetron_ismrmrd_client` can be built standalone via its corresponding `CMakeLists.txt`, e.g.

```
$ cd apps/clients/gadgetron_ismrmrd_client
$ mkdir build
$ cd build
$ cmake ..
$ make install
```
should "just work".

**Comment by ghisvail** [comment]
Fair enough. Feel free to close the issue if no further action should be taken.
