### ISSUE TITLE
Remove Matlab Java command server

### ISSUE THREAD

**Issue by inati** [gadgetron/gadgetron#156]
Now that we have buffered data structures, the speed of executing matlab commands through engine calls is no longer an issue.  We should remove the Java command server and it's hacks.

**Comment by hansenms** [comment]
I don't understand this. Eventhough some Gadgets have buffered structures, why would you sacrifice performance in Matlab?

**Comment by dchansen** [comment]
We would remove a needless dependence on java, the Matlab scripts will be easier to debug, it's a codepath less for us to keep up to date.
In addition, the java stuff does provide a speedup, but it's still painfully slow to do acquisition by acquisition processing. Instead we can now just use the buffers, which send enough data that the reduced overhead from using the command server does not matter.

**Comment by hansenms** [comment]
Fair point.

**Comment by hansenms** [comment]
Did we do this already? @inati , @dchansen

**Comment by inati** [comment]
Not yet



Sent with a mobile device

-----Original Message-----

**Comment by naegelejd** [comment]
Yes... the `MatlabCommandServer` was removed by David in 39d7cd569a3a621c92e4b13b02642c3a125f5d9b. The basic `MatlabGadget`, however, still attempts to load the `MatlabCommandServer` in `process_config`. The current `matlab.xml` chain **does not work**. David has stated that keeping the old `MatlabGadget` around makes no sense and we should just use `MatlabBufferGadget`, which he has updated to work without the `MatlabCommandServer`.

In my opinion, two things related to this issue still need to happen:

1. Remove old `MatlabGadget` and update corresponding example chain and docs. Related: clean up comments referring to `MatlabCommandServer` in the newer `MatlabBufferGadget`.
2. Add an integration test that tests the `MatlabBufferGadget` without requiring a GPU.
