### ISSUE TITLE
Compatibility with Mac Os X 10.10

### ISSUE THREAD

**Issue by srapacchi** [gadgetron/gadgetron#169]
Few modifications are needed to make compilation compatible with Mac Os X 10.10.

I made a post about it here: https://groups.google.com/d/topic/gadgetron/lUTTkbTqUvY/discussion

I believe point 1/ to be ok, point 2/ to be an actual correction and I am concerned about point 3/. Removing a namespace might fail to comply with other platforms (Windows especially) although I do not have the means to check this.

Here are the 3 points of modifications:

====================================
1/ Clang (I have Apple LLVM version 6.1.0 (clang-602.0.49) (based on LLVM 3.6.0svn)) compiles now natively to c++11, which requires a change in the CMakeLists.txt to remove the compiler option:

From :
    SET (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 -stdlib=libc++")

To:	   
   SET (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fPIC ")

the option "-stdlib=libc++" returns the first error I had.
I believe a check of Clang version would be necessary to maintain retro-compatibility (  if (CMAKE_CXX_COMPILER_VERSION VERSION_LESS 3.6) etc.).

====================================
2/ There is an error in cuSparseMatrix.cu :

gadgetron/toolboxes/core/gpu/cuSparseMatrix.cu:56:148: error: redefinition of default argument
template< class T> void Gadgetron::sparseMV(T alpha, T beta, const cuCsrMatrix< T> &mat, const cuNDArray< T> &vec_in, cuNDArray< T> &vec_out, bool adjoint = false) {

Default parameter values are meant to be declared in the header file only (I learned something!), so I removed it from cuSparseMatrix.cu:
template< class T> void Gadgetron::sparseMV(T alpha, T beta, const cuCsrMatrix< T> &mat, const cuNDArray< T> &vec_in, cuNDArray< T> &vec_out, bool adjoint) {

====================================
3/ I get multiple conflicts of overloading in cuNDArray_elemwise.cu:

gadgetron/toolboxes/core/gpu/cuNDArray_elemwise.cu:207
template<typename T> struct cuNDA_real : public thrust::unary_function<T,typename realType<T>::Type>
{
  __device__ typename realType<T>::Type operator()(const T &x) const {return real(x);}
};

The issue is that the overloaded definition is confused between Gadgetron::T and std::T (with T=float).
The solution I found (and my skills are limited to support its safety) is to remove the namespace std from this file:

gadgetron/toolboxes/core/gpu/cuSparseMatrix.cu:10:
using namespace Gadgetron;
//using namespace std;

**Comment by samuelhurley** [comment]
Nice work getting it to compile with CUDA on OSX.

For point #1, I am not running into this issue. I am compiling with the
same version of Clang as you (Apple LLVM version 6.1.0 (clang-602.0.49)).
I am building it fine directly from what is on GitHub with no
modifications. (Note I am not building with CUDA). Wonder why that is the
case.

Sam

---
Samuel A. Hurley, PhD
MRI Physics Support Scientist
FMRIB Centre, University of Oxford
Telephone:  +44 (0) 1865 222733
http://users.fmrib.ox.ac.uk/~shurley/

**Comment by hansenms** [comment]
Thanks. It would be great if this was in the form of a pull request, so we can see the specific changes needed line by line and we have an easy way to check on other platforms.

**Comment by srapacchi** [comment]
Sure, I will try to put a pull request. I will check again the error I had with stdlib=libc++.

**Comment by srapacchi** [comment]
I pulled the most recent version, and tested it all again. I stand corrected, the CMAKE_CXX_FLAGS are good for Clang.
But the other 2 changes are indeed required. I will put a pull request through a branch.

Thanks
Stan

**Comment by srapacchi** [comment]
Closing the issue.
