### ISSUE TITLE
Different weighting from GPU NUFFT causing inconsistent CS reconstruction results

### ISSUE THREAD

**Issue by PlutoniumHeart** [gadgetron/gadgetron#192]
Hi guys,
I just updated my Gadgetron to the latest master branch, and I noticed this commit "dde8b6d56002c376f29becc982c8bc0e221d11ca" with commit message "Updated cuNDFFT to use correct scaling and use fast FFTshift" breaks all my Compressed Sensing reconstruction parameters. I now have to recalibrate all my CS parameters for multiple projects. 

I am just wondering if changing the FFT scaling is worth the trouble?

Thanks!

**Comment by hansenms** [comment]
Not quite sure I understand the question. The scaling was wrong, it was a bug if you will. The actual scaling was not tied to the number of points being transformed as it should be so scaling was dependent on matrix sizes, etc. That causes severe problems in exactly the situations you describe because regularization parameters now become dependent on matrix size or number of points being transformed. 

So it had to be fixed. And yes it eliminated a great deal of trouble. Sure you will have to "recalibrate" your parameters, but I suspect that following that recalibration, your parameters will now be valid over a wider range of imaging problems. 

Makes sense?

**Comment by hansenms** [comment]
I'm closing this one. Feel free comment if you have comments.

**Comment by PlutoniumHeart** [comment]
Sorry for the late reply, I got really busy recently, I was also using a CPU based NUFFT, now I think the weighting is the same on both, so I just copied the CPU version's weightings over and it works. 

For some applications the FFT weightings are not very important, I think FFTW is also not doing the weighting, and I got used to the not weighted version of the GPU NUFFT, that's why I raised the questions. 

Thanks!

**Comment by hansenms** [comment]
Which CPU based NUFFT do you use. Would you like to work on getting a wrapped version into the Gadgetron to provide a CPU alternative?

**Comment by PlutoniumHeart** [comment]
Hi, I am using a MATLAB version NUFFT from a U of Michigan Prof. Jeffrey Fessler. It's described in the paper "Nonuniform Fast Fourier Transforms Using Min-Max Interpolation". I actually wrote a mex wrapper for Gadgetron's NUFFT... 

I am working on a C/C++ version of the same CPU NUFFT, but currently it's only kinda working for 2D cases, and has some phase errors that I am still debugging, also the performance still need a lot of tuning, I would put it on github once I am comfortable with it, and I'll let you guys know.

**Comment by siatjiasen** [comment]
Hi, the CPU based NUFFT I am using is : https://www-user.tu-chemnitz.de/~potts/nfft/ . This library is based on FFTW3, can be parallelized, and contains an example of dealing with non-Cartesian MRI dataset (https://www-user.tu-chemnitz.de/~potts/nfft/mri.php). Moreover, codeare (another MR image reconstruction toolbox) also use this library for non-Cartesian reconstruction.  However, my poor programming ability can't give me full utilization of this library (my CG-SENSE implementation using this library is slower than the CG-SENSE implementation in Gadgetron using GPU).

**Comment by dchansen** [comment]
That is to be expected. While The Gadgetron NUFFT could certainly be optimized further, it should still beat any CPU based implementation by around a factor 5x. Both steps of the NUFFT (convolution and FFT) are significantly faster on the GPU.

Having a CPU NUFFT would still be great though, as it would allow users without a GPU to reconstruct non-cartesian data.
