### ISSUE TITLE
Gadget property string values are terminated by the first white space

### ISSUE THREAD

**Issue by ojosephs** [gadgetron/gadgetron#196]
Not sure whether this is a bug or intended behaviour.

I'm trying to add a matlab startup command property in gadgetron/gadgets/matlab/MatlabGadget.h.
Everything works fine for single word commands but if .....

In the .xml file I have

        <property><name>matlab_startcmd</name><value>matlab -nosplash</value></property>

and in matlab gadget .h

		startcmd_   = matlab_startcmd.value();

		GDEBUG("Starting MATLAB engine with command: %s\n", startcmd_.c_str());

When I run, I get the output:

2015-08-10 18:13:18 DEBUG [MatlabGadget.h:61] Starting MATLAB engine with command: matlab

i.e. with ' -nosplash' stripped off

I think in gadgetron/apps/gadgetron/Gadget.h, when the parameter string is stored or accessed, stringstream is stripping off all but the first word.

Cheers,
Oliver

**Comment by hansenms** [comment]
Well the problem is this code:

      virtual void string_value(const char* val)
      {
        GadgetPropertyBase::string_value(val);

        if (!is_reference_)
        {
          T tmp;
          std::stringstream(val) >> std::boolalpha >> tmp;
          this->value(tmp);
        }
      }

in Gadget.h

It will only really add the first word in the case of a string. The question is what should the behavior really be?

If we would like the behavior to be that it accepts full strings with spaces, then we should probably have a specialization for that case, but it should be something like:

      virtual void string_value(const char* val)
      {
        GadgetPropertyBase::string_value(val);

        if (!is_reference_)
        {
          T tmp;
          extract_value<T>(val,tmp);
          this->value(tmp);
        }
      }

And then we have to have:

    template <typename T> void extract_val(const char* val, T& tmp)
    {
          std::stringstream(val) >> std::boolalpha >> tmp;
    }

    template <> void extract_val(const char* val, std::string& tmp)
    {
         tmp = std::string(val);
    }

Or something like that. @ojosephs, could you give that a try and see if it solves it for you?

**Comment by ojosephs** [comment]
The following works, outside of any class definition, together with the modified string_value method.

template <typename T> inline void extract_value(const char* val, T& tmp)
{
      std::stringstream(val) >> std::boolalpha >> tmp;
}

template <> inline void extract_value(const char* val, std::string& tmp)
{
     tmp = std::string(val);
}

**Comment by ojosephs** [comment]
The following template functions, defined in Gadget.h outside of any class, work with the new string_value() method. Not sure if the scope is too wide, though.
```c++
template <typename T> inline void extract_value(const char* val, T& tmp)
{
std::stringstream(val) >> std::boolalpha >> tmp;
}

template <> inline void extract_value(const char* val, std::string& tmp)
{
tmp = std::string(val);
}
```

**Comment by hansenms** [comment]
I agree, maybe narrow the scope of those functions a bit (by naming them something longer or something).

Do you want to make a PR for this?
