### ISSUE TITLE
Matlab PATH not set in integration tests

### ISSUE THREAD

**Issue by naegelejd** [gadgetron/gadgetron#197]
The `run_gadgetron_test.py` script builds up the environment before running a test. This environment includes the `$PATH` variable, which includes the `bin/` directory in both `$ISMRMRD_HOME` and `$GADGETRON_HOME`, and, on Unix, the standard directories `/bin`, `/sbin`, `/usr/bin`, `/usr/sbin`, `/usr/local/bin`, `/usr/local/sbin`. On OS X at least, none of these directories contain the `matlab` executable, needed by the `MatlabGadget`. This causes the MatlabGadget to fail with the following output:
```
2015-08-18 09:00:00 DEBUG [MatlabBufferGadget.h:37] Starting MATLAB engine
matlab: Command not found.
2015-08-18 09:00:00 DEBUG [MatlabBufferGadget.h:40] Can't start MATLAB engine
```
The Gadgetron wiki says to set `$MATLAB_HOME` to something like `/Applications/MATLAB_R2013b.app`, then set your `$DYLD_FALLBACK_LIBRARY_PATH` to `$MATLAB_HOME/bin/maci64`. If this is done properly, the `run_gadgetron_test.py` script need only to add `$MATLAB_HOME/bin` to the `$PATH` for the integration tests.

**Comment by hansenms** [comment]
I think we should just add this, why not. I don't like the idea of adding more command line arguments as in the discussion with Paul on the discussion board. So is it just a one liner to add this? Do you mind putting up a PR, since I am traveling?
