### ISSUE TITLE
Mac OSX Installation 

### ISSUE THREAD

**Issue by DANAJK** [gadgetron/gadgetron#199]
I have been following the Mac OS X Installation instructions on a fairly new MacBook. I get as far as the following before errors:

Davids-MacBook:~ davidatkinson$ brew install libiconv
Error: No available formula for libiconv 
==> Searching formulae...
==> Searching taps...
homebrew/dupes/libiconv
Davids-MacBook:~ davidatkinson$ pip install h5py pyxb Cython ismrmrd
You are using pip version 7.1.0, however version 7.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting h5py
  Downloading h5py-2.5.0-cp27-none-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (4.3MB)
    100% |████████████████████████████████| 4.3MB 79kB/s 
Collecting pyxb
  Downloading PyXB-1.2.4.tar.gz (8.7MB)
    100% |████████████████████████████████| 8.7MB 40kB/s 
Collecting Cython
  Downloading Cython-0.23.1-cp27-none-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (3.8MB)
    100% |████████████████████████████████| 3.9MB 90kB/s 
Collecting ismrmrd
  Downloading ismrmrd-1.2.3.tar.bz2
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/tv/zshkqq2145qgzlqhz386g4kr0000gn/T/pip-build-Ug1cja/ismrmrd/setup.py", line 6, in <module>
        import pyxb.binding.generate
    ImportError: No module named pyxb.binding.generate
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/tv/zshkqq2145qgzlqhz386g4kr0000gn/T/pip-build-Ug1cja/ismrmrd

**Comment by naegelejd** [comment]
The wiki needed updating. I fixed it so the proper `pip` instructions are as follows:
```
pip install h5py PyXB
pip install ismrmrd
```
although I believe you also need `ismrmrd-python-tools` from [here](https://www.github.com/ismrmrd/ismrmrd-python-tools).

**Comment by hansenms** [comment]
Is this OK @DANAJK , can we close this issue?

**Comment by DANAJK** [comment]
Thanks for the help. The line  ` pip install h5py PyXB`   works now. However, I still have trouble with the lines before and after:

> Davids-MacBook:~ davidatkinson$ brew install libiconv
> Error: No available formula for libiconv 
> ==> Searching formulae...
> ==> Searching taps...
> homebrew/dupes/libiconv

and `pip install ismrmrd` which produces output that includes the message:

ERROR:pyxb.utils.utility:open /private/var/folders/tv/zshkqq2145qgzlqhz386g4kr0000gn/T/pip-build-DTO9pr/ismrmrd/schema/ismrmrd.xsd
  Traceback (most recent call last):
    File "/usr/local/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyxb/utils/utility.py", line 740, in DataFromURI
      stream = open(uri, 'rb')
  IOError: [Errno 2] No such file or directory: '/private/var/folders/tv/zshkqq2145qgzlqhz386g4kr0000gn/T/pip-build-DTO9pr/ismrmrd/schema/ismrmrd.xsd'
  error: [Errno 2] No such file or directory: '/private/var/folders/tv/zshkqq2145qgzlqhz386g4kr0000gn/T/pip-build-DTO9pr/ismrmrd/schema/ismrmrd.xsd'

Looking at my folders, it seems there is no pip-build-DTO9pr folder. I have now tried installing the more recent pip7.1.2, but I get a similar error (though the folder name is different).

**Comment by DANAJK** [comment]
The section of the Mac OS X Installation instructions for the Siemens converter probably has an out of date repo. I think `git clone https://github.com/nih-fmrif/siemens_to_ismrmrd` should be `git clone https://github.com/ismrmrd/siemens_to_ismrmrd.git` ?

**Comment by hansenms** [comment]
I changed the wiki. 

I need @naegelejd to comment on the pip issues. It is always an option to just clone ismrmrd-python and run:

    python setup.py install

**Comment by naegelejd** [comment]
I can't replicate the `pip` issue locally. There's some discrepancy with temporary paths and where PyXB is generating the bindings to the ISMRMRD schema. I have no idea how to make it work when you run `pip install` since it works fine locally. I can check out the code and run `pip install ./ismrmrd-python` and it works fine. Python packaging is beyond hope.

I think maybe we should pre-generate the Python XML code from the schema and just push that to PyPi so that a user only has to download the code... not worry about PyXB and generating bindings and all that nonsense.

In the meantime, the instructions should say to check out `ismrmrd-python` and run `python setup.py install`.

**Comment by hansenms** [comment]
I have updated the Wiki

I agree that we should just upload the PyXB generated code to pip. That also makes it one less dependency. Do we need some kind of script to do the pip upload then?

**Comment by naegelejd** [comment]
A script would make things easier but it's not *that* simple. You can't re-upload a release to PyPI if you make a mistake, need to rearrange the contents of the distribution, etc. I think this should be addressed in detail when it's time to upload a new release of `ismrmrd-python`.

**Comment by hansenms** [comment]
@naegelejd, OK. Should we close this for now and just leave it on the list. In any case, it is probably something for an issue on the ismrmrd repo.

**Comment by naegelejd** [comment]
Yes we should close this. I'll open an issue on the `ismrmrd-python` repo stating that we need to generate and package the XML bindings prior to uploading the next PyPI release.

**Comment by hansenms** [comment]
OK

**Comment by mirc-dsi** [comment]
Hello,
I have the same issue as above:
ERROR:pyxb.utils.utility:open /private/var/folders/_0/f14_2__s2mjb1djxx4vhjfb40000gn/T/pycharm-packaging/ismrmrd/schema/ismrmrd.xsd

Is there a work around for this? Would be very kind if I could get around this.

Best,
Sairam

**Comment by mirc-dsi** [comment]
Hello,
I have the same issue as above:
ERROR:pyxb.utils.utility:open /private/var/folders/_0/f14_2__s2mjb1djxx4vhjfb40000gn/T/pycharm-packaging/ismrmrd/schema/ismrmrd.xsd

Is there a work around for this? Would be very nice if I could!

Best,
Sairam
