### ISSUE TITLE
Mac OS X Installation: MATLAB and make

### ISSUE THREAD

**Issue by DANAJK** [gadgetron/gadgetron#201]
The Mac OS X instructions ask for the Java JDK with the same version as MATLAB to be installed. For me, using MATLAB R2015a, MATLAB `version -java` reports `Java 1.7.0_60-b19 ` which I assume means 7u60. However, after I download that from Oracle, the JDK will not install, claiming that I need an OS X version higher than 10.7.3, even though I have version 10.10.5 !

Neglecting this step (and also ignoring an error message for the `brew install libiconv` step), all goes fine until the Gadgetron make. This gets to:
> Linking CXX shared library libgadgetron_matlab.dylib
> Undefined symbols for architecture x86_64:
>  "_mxAddField", referenced from:
>      Gadgetron::BufferToMatlabStruct(Gadgetron::IsmrmrdDataBuffered*) in MatlabUtils.cpp.o 
> ......
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make[2]: *** [gadgets/matlab/libgadgetron_matlab.3.8.1.dylib] Error 1
> make[1]: *** [gadgets/matlab/CMakeFiles/gadgetron_matlab.dir/all] Error 2
> make: *** [all] Error 2 
 

Any suggestions?

**Comment by hansenms** [comment]
Are your PATHS set correctly to pick up your MATLAB paths?

**Comment by DANAJK** [comment]
I'm not sure what they should be, but I do have R2015a in some of my environment variables: 

DYLD_FALLBACK_LIBRARY_PATH=/usr/local/lib:/usr/local/lib:/Applications/MATLAB_R2015a.app/bin/maci64

MATLAB_HOME=/Applications/MATLAB_R2015a.app

PATH=/usr/local/bin:/usr/local/bin:/Applications/MATLAB_R2015a.app/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/git/bin

**Comment by hansenms** [comment]
I'll have to see if I can find some time to reproduce this, @inati can you comment?

**Comment by inati** [comment]
Sorry, haven’t had a chance to try this yet.  I just got a new machine that I am configuring later today, so I’ll get back to you soon.
-SI

**Comment by naegelejd** [comment]
I made some very minor changes to the wiki instructions and everything works for me using Matlab R2015b. You can see wiki changes [here](https://github.com/gadgetron/gadgetron/wiki/Mac-OS-X-Installation/_history)
