### ISSUE TITLE
Remove static building of toolboxes

### ISSUE THREAD

**Issue by hansenms** [gadgetron/gadgetron#23]
At some point, optional static building of toolboxes was introduced. However, multiple toolboxes (FFT, CloudBus, Logging, etc) rely on singletons for threadsafe operation. This breaks on Windows when building statically and the singletons were added specifically for Windows in many cases. 

Static building of toolboxes should be removed throughout.

**Comment by gtdeveloper5** [comment]
The static linkage is removed.
