### ISSUE TITLE
Using Boost

### ISSUE THREAD

**Issue by dchansen** [gadgetron/gadgetron#232]
What is our official policy about Boost? Do we intend to phase it out, or are we keeping it? 
I feel this is somewhat an all or nothing scenario. Only using a "little bit" of boost still gives us all the potential hassle (although that's mainly for windows), but few of the benefits. 

On the other hand if we do us Boost, I feel that we should try to use it for as much as possible, to avoid "not invented here" syndrome. We have a tendency of rolling our own for almost everything, and it just gives us more lines of code to maintain and debug.

Either way, I think it would be good to have a clear policy: either remove boost completely, or embrace it.

**Comment by hansenms** [comment]
@dchansen, I love your non-compromising all or nothing approach. There is nothing worse than the stench of compromise. 

I am leaning towards embrace for the following reasons:

There will always be somethings where we would want to turn to libraries to manage to make cross-platform stuff less of a nightmare, I am thinking specifically of OS system calls needed for network communications and dynamic runtime linking. At the moment we are using ACE for this, but I think boost::asio and Boost DLL (http://apolukhin.github.io/Boost.DLL/, I don't think it is officially in Boost yet, but will be) could do the same. We have also been using threading from ACE, but I think what we  need is in C++11 now.

So I think there is a reasonable chance that we could spend a week or two cleaning up and completely get rid of ACE and then just use boost, but I think there is virtually no chance of getting rid of both without reinventing the wheel and maintaining some ugly cross platform code. 

Boost has many other useful things such as program options for command line options, string parsing tools, etc. etc. That we could implement if we wanted to, but it is just too much work for our limited operation and quite frankly not where we should be spending our time. 

So I am voting for embrace, but phase out ACE to get rid of one dependency. 

With that said though, I think as features from boost make it into the C++ standard, we should use the standard, examples being shared_ptr, etc. that are now part of C++11. 

Thoughts?

Michael

**Comment by dchansen** [comment]
You know what they say: A good compromise leaves everyone unhappy.

I am very happy to use Boost, as it also gives us stuff that's in the standard library for C++14 and 17, such as boost::optional. I also agree that we should replace boost with std whenever possible.

I like the plan of replacing as much of ACE as possible with Boost, but I would much rather keep ACE  than have a bunch of physicists and engineers (i.e. us) try and glue something. Also, I am not sure if any of us have a week or two to spare, sadly.

**Comment by naegelejd** [comment]
> replacing as much of ACE as possible with Boost

sounds like fun to me, but alas, no spare time.

**Comment by hansenms** [comment]
We can put off replacing ACE, but it is conceptually straight forward:

1. Socket communication: Use Boost::asio
2. Threads, Mutexes, etc.: Use c++11 features
3. Queues, etc.: Use STL containers
4. Replace the underlying ContainerMessages with shared pointers that are chainable. This has to be done really carefully, because of performance issues, but it is doable. Goal would be to get rid of any ->release(), etc. stuff. The memory management should be automatic. 

It can be done in stages. Pretty much in the order I have outlined above. I would start with the socket communication because I think it has the most risk and performance could suffer if it is not done well. 

I say we put that on the back burner for now. But eventually, I think it should be done.

**Comment by PlutoniumHeart** [comment]
I had the same thought quite sometime ago. I would vote to remove boost, if network is the main use of boost, then C++17 would have everything we need. 

With that been said, I do agree that boost has a lot interesting and useful functions, so I think we should at least convert boost's overlapping functions with C++11(and later) to C++11. In other word, boost should be used only when there's no alternative in the C++ standard.

**Comment by hansenms** [comment]
So maybe when C++17 is released then?

There are other goodies in boost, like program options (it is a pain to program and not interesting, but important to do right), etc. There will always be some things where we would want to turn to boost, so I think it is nice to have around, but I agree, we should shift towards the standards in the language as they become available.
