### ISSUE TITLE
Integration Test Issues

### ISSUE THREAD

**Issue by DANAJK** [gadgetron/gadgetron#247]
Following test cases hang when downloading using `get_data.py`:
 gtplus/snr_unit_recon_ipat4/meas_MID00175_FID02912_GRE_reps=150_iPAT=4
 gtplus/snr_unit_recon_tpat3/meas_MID00171_FID02908_GRE_reps=150_TPAT=3.dat
 gtplus/FatWater/meas_MID00342_3e2i_R4.dat

Documentation for `run_all_tests.py` on Mac OSX page seems out of date - script now needs -I and -G flags in arguments?

`run_gadgetron_test.py`  has a call to `gadgetron_ismrmrd_client` with a -q flag that seems to be cause of an error.

`run_gadgetron_test.py`  when setting `info` inside script, seems to need a non-existent configuration `gadgetron_info.xml`. Reverting to older code here that calls `gadgetron_info` seems to work.

Test cases in `test_cases.txt` have error at case `cases/generic_grappa_T2W.cfg`. Tried copying `~/gadgetron/gadgets/mri_core/Generic_Cartesian_Grappa_T2W.xml` to `/usr/local/share/gadgetron/config` because it was not in `config` folder. Then, using `gadgetron_ismrmrd_client` at the command line, it will start this case until the following:
2015-11-15 09:22:03 INFO [GadgetStreamController.cpp:359]   Gadget parameters: 0
2015-11-15 09:22:03 INFO [GadgetStreamController.cpp:341] --Found gadget declaration
2015-11-15 09:22:03 INFO [GadgetStreamController.cpp:342]   Gadget Name: Scaling
2015-11-15 09:22:03 INFO [GadgetStreamController.cpp:343]   Gadget dll: gadgetron_mricore
2015-11-15 09:22:03 INFO [GadgetStreamController.cpp:344]   Gadget class: GenericReconImageArrayScalingGadget
2015-11-15 09:22:03 ERROR [GadgetStreamInterface.h:91] Failed to load factory (make_GenericReconImageArrayScalingGadget) from DLL (libgadgetron_mricore)
2015-11-15 09:22:03 ERROR [GadgetStreamInterface.h:119] Failed to load gadget using factory
2015-11-15 09:22:03 ERROR [GadgetStreamController.cpp:353] Failed to create GadgetModule from GenericReconImageArrayScalingGadget:gadgetron_mricore
2015-11-15 09:22:03 ERROR [GadgetStreamController.cpp:127] GadgetStream configuration failed
2015-11-15 09:22:03 DEBUG [GadgetStreamController.cpp:173] handle_close called
2015-11-15 09:22:03 INFO [GadgetStreamController.cpp:178] Shutting down stream and closing up shop...

Note earlier test cases in `test_cases.txt` run but `gadgetron.log` contains a line `ERROR [GadgetServerAcceptor.cpp:14] error opening acceptor` for each.

**Comment by hansenms** [comment]
The hanging while downloading data sometimes happens. Just stop it and start again. We are aware of it, but have not really put in a fix yet. 

As for the other stuff, it looks like you have downloaded a newer version of the code (and tests) but have not compiled and installed the corresponding version of the code. The -q argument to the client is relatively new, and the Generic_Cartesian_Grappa_T2W.xml is also new, if you had compiled that code and installed it, it should be in your config folder, you should not copy it manually. Can you try to do a clean build and install before running the test.

**Comment by DANAJK** [comment]
I have downloaded new versions, but I did compile the new stuff before opening this issue. Is there a specific order for ismrmrd, gadgetron etc to do the compilation, and is there anything that needs to be done to clean up before running `make`?

**Comment by hansenms** [comment]
I think you are missing a make install. Otherwise Generic_Cartesian_Grappa_T2W.xml should have been copied to your config folder.

**Comment by DANAJK** [comment]
Thanks. I had not done the make install. 
Now after reversing my previous changes (hopefully) and running make install, I think the situation is:

Cannot get the three datasets mentioned before to download despite stopping and restarting a few times (I realise this is nothing to do with make).

Still need -I and -G flags in call to `run_all_tests.py` (Mac OS X Wiki page needs updating?).



Test script `run_all_tests.py` failing on generic_grappa_T2W.cfg (see below). However, after starting a new gadgetron on port 9009, this will work: `gadgetron_ismrmrd_client -p9009 -c Generic_Cartesian_Grappa_T2W.xml -f generic_grappa_T2W.h5`

Not sure what to do next - I might have messed something up somewhere before when editing things? The `client.log` says `Error caught: write: Broken pipe` and the `gadgetron.log` is
2015-11-15 15:13:11 INFO [main.cpp:178] Starting cloudBus: localhost:8002
2015-11-15 15:13:11 INFO [main.cpp:205] Configuring services, Running on port 9003
2015-11-15 15:13:11 ERROR [GadgetServerAcceptor.cpp:14] error opening acceptor
2015-11-15 15:13:11 DEBUG [GadgetServerAcceptor.cpp:44] GadgetServerAcceptor::handle_close
2015-11-15 15:13:11 DEBUG [GadgetServerAcceptor.cpp:45] Close Data Acceptor



 


....
TEST: cases/epi_2d.cfg SUCCESS
Grabbing test case: cases/fs_csi.cfg
Running Gadgetron test with: 
  -- ISMRMRD_HOME  : /usr/local
  -- GADGETRON_HOME  : /usr/local
  -- PATH            : /usr/local/bin:/usr/local/bin:/Applications/MATLAB_R2015b.app/bin:/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin
  -- DYLD_FALLBACK_LIBRARY_PATH : /usr/local/lib:/usr/local/lib:/usr/local/../arma/lib:/Applications/MATLAB_R2015b.app/bin/maci64:/usr/local/cuda/lib64:/opt/intel/mkl/lib/intel64:/opt/intel/lib/intel64:/usr/local/lib:/usr/local/lib::/Applications/MATLAB_R2015b.app/bin/maci64
  -- TEST CASE       : cases/fs_csi.cfg
Running test case: cases/fs_csi.cfg
Missing siemens configuration parameter(s), assuming no conversion to ISMRMRD needed
Test skipped because system does not meet gpu requirements
System Requirements: Actual/Required
System Memory: 8192.0/2048.0
Python Support: True/False
Matlab Support: True/False
CUDA Support: False/True
GPU Memory: 0/1024.0
TEST: cases/fs_csi.cfg SUCCESS
Grabbing test case: cases/generic_grappa_T2W.cfg
Running Gadgetron test with: 
  -- ISMRMRD_HOME  : /usr/local
  -- GADGETRON_HOME  : /usr/local
  -- PATH            : /usr/local/bin:/usr/local/bin:/Applications/MATLAB_R2015b.app/bin:/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin
  -- DYLD_FALLBACK_LIBRARY_PATH : /usr/local/lib:/usr/local/lib:/usr/local/../arma/lib:/Applications/MATLAB_R2015b.app/bin/maci64:/usr/local/cuda/lib64:/opt/intel/mkl/lib/intel64:/opt/intel/lib/intel64:/usr/local/lib:/usr/local/lib::/Applications/MATLAB_R2015b.app/bin/maci64
  -- TEST CASE       : cases/generic_grappa_T2W.cfg
Running test case: cases/generic_grappa_T2W.cfg
Converting Siemens .dat file to ISMRMRD for the first dependency measurement.
Running Gadgetron recon on the first dependency measurement
Converting Siemens .dat file to ISMRMRD for data measurement.
Running Gadgetron recon on data measurement
Elapsed time: 0.0447270870209
Failed to run gadgetron_ismrmrd_client!
TEST: cases/generic_grappa_T2W.cfg FAILED
ALL_TESTS:  FAILED

**Comment by hansenms** [comment]
I'll update the wiki later. If you have installed in standard locations you should not need to specify anything with -I or -G. Defaults are fine.

On the hanging download. Please be aware that some of those files are huge (GBs) so it takes time. Before you device it is hanging, please verify that it is not still downloading (by checking if the files are growing)

On your error, I think you have a hanging Gadgetron instance on port 9003, please check (ps aux|grep gadgetron). Kill all running instances and try again.

------

**Comment by hansenms** [comment]
Sorry, my post before was partly hidden for some reason. Here is what I said:

I have updated the Wiki. If you have installed in standard locations you should not need to specify anything with -I or -G. Defaults are fine.

On the hanging download. Please be aware that some of those files are huge (GBs) so it takes time. Before you device it is hanging, please verify that it is not still downloading (by checking if the files are growing) 

 On your error, I think you have a hanging Gadgetron instance on port 9003, please check (ps aux|grep gadgetron). Kill all running instances and try again.

**Comment by DANAJK** [comment]
Thanks. Yes, despite logging out and in, there was a gadgetron running on port 9003 from 2 days ago. All tests now run (apart from those I have not tried to download).

**Comment by hansenms** [comment]
Great. I will close this issue now since I think it is all OK, right?

You may have better luck with individual downloads of those large files, e.g.:

    wget http://gadgetrontestdata.s3-website-us-east-1.amazonaws.com/gtplus/snr_unit_recon_tpat3/meas_MID00171_FID02908_GRE_reps=150_TPAT=3.dat

Once you have downloaded the once, they will only be verified on subsequent calls to get_data.py.

**Comment by DANAJK** [comment]
OK to close. Thanks.
