### ISSUE TITLE
Issues after compilation

### ISSUE THREAD

**Issue by btlorch** [gadgetron/gadgetron#256]
Hi,

I've been struggling through the compilation of Gadgetron and managed to build it with a few changes eventually, but now the executable runs into more issues.

When I try to run `gadgetron`, it seems like the path to the configuration file is not concatenated correctly.
```
2015-11-30 18:13:00 ERROR [main.cpp:108] Gadgetron configuration file /usr/local/bin/..//share/gadgetron/config/gadgetron.xml not found.
```

Having removed on of the slashes and applied `realpath()` on the configuration file's path, I recompiled the project but of course it didn't come far.
```
$ gadgetron
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
Aborted (core dumped)
```

So I guess I messed something up during the compilation.
First of all, I needed to comment out the section in the top level CMakeList.txt which checked the MKL version. The MKL_VERSION_STRING gave me `..` even though I should have the latest version installed with Intel Parallel Studio XE 2016.
Secondly, the ISMRMRD libary could not be located. I had build it from the source:
```
git clone https://github.com/ismrmrd/ismrmrd.git
cd ismrmrd
mkdir build
cd build
make
sudo make install
```

In `cmake/FindIsmrmrd.cmake` I had to add a line `set(ISMRMRD_HOME /usr/local/include/)` on the top and `set(ISMRMRD_INCLUDE_DIR /usr/local/include/ismrmrd)` on the bottom in order to satisfy cmake.

Given my changes to the installation process, can you guess why the path to the configuration file is messed up?

Thanks for your help!

**Comment by xueh2** [comment]
First thing to try :

cd /usr/local/bin/..//share/gadgetron/config
cp ./gadgetron.xml.example ./gadgetron.xml

**Comment by naegelejd** [comment]
The [installation instructions on the wiki](https://github.com/gadgetron/gadgetron/wiki/Linux-Installation) say to copy the configuration file from `gadgetron.xml.example` to `gadgetron.xml`.

The instructions also say to set your environment variables (including `ISMRMRD_HOME`, in this case to `/usr/local/`). You don't need to modify `FindIsmrmrd.cmake`.

**Comment by hansenms** [comment]
I think @xueh2 and @naegelejd have said it. Can you confirm that this solves your problem so that we can close the issue.

**Comment by btlorch** [comment]
Yes, thank you very much, indeed I missed to copy the xml as the very last step.
