### ISSUE TITLE
Deprecated GADGET_MESSAGE_ACQUISITION in AcquisitionFinishGadget

### ISSUE THREAD

**Issue by evgueni-ovtchinnikov** [gadgetron/gadgetron#295]
Running a client that uses AcquisitionFinishGadget causes Gadgetron to stall with the error message

2016-02-18 11:01:07 ERROR [GadgetronConnector.h:92] Unrecognized Message ID received: 1001

apparently because of the deprecated constant GADGET_MESSAGE_ACQUISITION still being used in AcquisitionFinishGadget. Renaming it to GADGET_MESSAGE_ISMRMRD_ACQUISITION eliminates the problem.

**Comment by hansenms** [comment]
Could you put up a PR with the fix.

**Comment by hansenms** [comment]
Closing this, since I believe it was fixed.
