### ISSUE TITLE
Code formatting guidelines

### ISSUE THREAD

**Issue by hansenms** [gadgetron/gadgetron#31]
We should have some code formatting guidelines. Mostly to avoid problems with lines looking like they have been edited when really they have not.

**Comment by grlee77** [comment]
I usually use an editor that is set to trim trailing white spaces when saving a file.  Many (most?) files in gadgetron have at least some lines with trailing white spaces, so this leads to even a single line edit showing up as a several line modification after trailing white spaces are removed.  

Obviously I can avoid this by disabling the white space trimming features in my editor, but I don't see a reason one would prefer to keep them around.  Would you be opposed to a PR stripping trailing white spaces across the codebase?

**Comment by hansenms** [comment]
I would be opposed to a PR which only purpose was to make it easier to work with a certain text editor. 

I would, however, not be opposed to generally doing some style changes in the codebase to to setting and policing style guidelines. 

So, we are in need of some cleaning, but it has to be more deliberate than simply because my editor does so and so.

**Comment by grlee77** [comment]
Fair enough.

I am not familiar enough with common C++ conventions to contribute much in general there.  I contribute most to Python projects that often use the [PEP8](https://www.python.org/dev/peps/pep-0008/) standards and where the automated pep8 format checking tool raises warnings for trailing white spaces, but perhaps that type of check is less common in C++ projects.

**Comment by dchansen** [comment]
The advantage of adopting the Cpp Core Guidelines is that they are explicitly trying to make it tool enforceable. From what I understand, these tools are coming soon, but are not yet production ready.

Another advantage is that it's supported by Bjarne Stroustrup and the C++ foundation, so it's as close to an official thing as we can get.

**Comment by hansenms** [comment]
I am on board with these guidelines. Should we wait for the tools to become available.

**Comment by naegelejd** [comment]
The Cpp Core Guidelines are not concerned with formatting and naming conventions. Tools such as `clang-format` already exist for standardizing formatting across a project.

**Comment by hansenms** [comment]
@naegelejd, understood. We probably need two layers of this:

1. Actually formatting style (clang-format)
2. Coding style, e.g. do we return arrays or use reference or pointer input arguments serve as containers for output, etc. (enforced by some other tool)

Then we should maybe appoint somebody chief of the code style police for something to have somebody take care of this.

**Comment by inati** [comment]
If anyone is interested in looking at the clang-format thing, @naegelejd and I put together a config file in the ismrmrd project:
https://github.com/ismrmrd/ismrmrd/blob/master/_clang-format
it could use a look over and a discussion of the style choices and of enforcement implementation.  Some experimentation is definitely in order.

**Comment by hansenms** [comment]
Stale. closing
