### ISSUE TITLE
Basic GRAPPA implementation

### ISSUE THREAD

**Issue by dgallichan** [gadgetron/gadgetron#332]
I'm new to Gadgetron - and a feature that I'd like to be able to use is a 'normal' GRAPPA implementation that can reconstruct a single volume of Cartesian undersampled data - or multiple volumes from a singel calibration scan. As far as I can tell, the current module relies on having timeseries data to generate the calibration data. Are there already plans to implement the more 'basic' version - or should I have a go at it myself?

Also - glancing through the ISMRMRD stuff I wasn't able to find a way of tagging certain samples as being 'calibration' data. Is this implemented on the ISMRMD side, or has someone already thought of a good way of handling this?

Thanks for your help

Daniel

**Comment by xueh2** [comment]
The Generic_Cartesian_Grappa.xml chain supports all calibration mode for 2D and 3D Cartesian reconstruction. This chain is a good place to start.

For a kspace line to be considered as calibration data, it should be labeled with
ISMRMRD_ACQ_IS_PARALLEL_CALIBRATION,
And/or
ISMRMRD_ACQ_IS_PARALLEL_CALIBRATION_AND_IMAGING,

**Comment by dgallichan** [comment]
Thanks for your quick reply - it's made me discover lots of code I hadn't spotted before when I was just looking through the documented GRAPPA example. I'll take a look and see how I get on.

**Comment by hansenms** [comment]
Closing this issue.
