### ISSUE TITLE
Move GRAPPA functionality from gtPlus to mri_core

### ISSUE THREAD

**Issue by hansenms** [gadgetron/gadgetron#34]
We need this moved and cleaned. This requires consolidation of some math functions in addition to general code cleaning, etc.

**Comment by hansenms** [comment]
@gtdeveloper5, we still need a simple chain using bukets/buffers and these new grappa functions. Were you going to put that in?

**Comment by hansenms** [comment]
@gtdeveloper5, @inati were we going to make simple chain using this code?

**Comment by inati** [comment]
Yes.  Haven’t gotten to it yet.

**Comment by xueh2** [comment]
This issue is solved.
