### ISSUE TITLE
SENSE reconstruction on cartesian data

### ISSUE THREAD

**Issue by cbasasif** [gadgetron/gadgetron#347]
Hi,

I am new to gadgetron . I would like to know whether Gadgetron has implemented CPU based SENSE algorithm on Cartesian k-space data.i have seen non-cartesian SENSE implementations but couldnt find cartesian based one.

Thanks in advance.

**Comment by xueh2** [comment]
Hi, Gadgetron does not have a Cartesian cpu sense chain implemented at this moment. You may consider to use grappa for Cartesian recon: Generic_Cartesian_Grappa.xml<https://github.com/gadgetron/gadgetron/blob/master/gadgets/mri_core/Generic_Cartesian_Grappa.xml>

Regards

Hui Xue

**Comment by cbasasif** [comment]
Thank you so much!
