### ISSUE TITLE
Remove the need to GCC_OLD_FLAG

### ISSUE THREAD

**Issue by hansenms** [gadgetron/gadgetron#35]
This flag was used in the past to indicate a GCC compiler older than 4.2. As far as I know, we don't support that compiler, so it should be removed. 

We should add a check in the top level cmake for GCC >= 4.4 (I think) and then remove the use of this flag throughout.

**Comment by inati** [comment]
Just FYI CentOS 6.5 ships with gcc 4.4.7 so greater than 4.4 would be fine in general.

Older systems e.g. CentOS 5.5 (NIH Biowulf cluster) have older compilers by default, but if you're on a system that old you're going to have to do some work and installing a newer gcc is not such a big deal in the grand scheme of things.

On Jan 4, 2015, at 7:35 PM, Michael Hansen <notifications@github.com<mailto:notifications@github.com>> wrote:


This flag was used in the past to indicate a GCC compiler older than 4.2. As far as I know, we don't support that compiler, so it should be removed.

We should add a check in the top level cmake for GCC >= 4.4 (I think) and then remove the use of this flag throughout.

**Comment by hansenms** [comment]
This is solved in 
https://github.com/gadgetron/gadgetron/commit/eddb8b662aff7affd027156d1d0d618cdde6b2e3
