### ISSUE TITLE
output_mode_ for solvers

### ISSUE THREAD

**Issue by pvelasco** [gadgetron/gadgetron#356]
Hi,

I noticed that the set_output_mode method of the class solver will set the member variable output_mode_ only if the input is positive and (strictly) less than OUTPUT_MAX (defined as 3, but that doesn't matter).

However, there are a couple of solvers (sbSolver and sbcSolver) that check for the condition:
if( this->output_mode_ >= solver<ARRAY_TYPE_ELEMENT, ARRAY_TYPE_ELEMENT>::OUTPUT_MAX )

Because of the restriction in set_output_mode, the above conditional statement will always be false.

Is that statement wrong, or is OUTPUT_MAX intended to be a sort of "super-verbose" mode?  (in which case, the set_output_mode method should be modified to allow set it to OUTPUT_MAX.

Thanks,

-Pablo

**Comment by hansenms** [comment]
@dchansen thoughts?

**Comment by pvelasco** [comment]
OK.  We agreed that OUTPUT_MAX is meant to be the size of the output_mode_ enum, not a super-verbose mode.  So I replaced the calls:
if( this->output_mode_ >= solver::OUTPUT_MAX )
with
if( this->output_mode_ >= solver::OUTPUT_VERBOSE )
