### ISSUE TITLE
CloudBus requires Boost UUID library - N/A in Boost 1.41

### ISSUE THREAD

**Issue by naegelejd** [gadgetron/gadgetron#37]
This library is not present in Boost <= 1.41, which is the version provided by CentOS 6.

See `toolboxes/cloudbus/CloudBus.h` lines 11-13:

```c++
#include <boost/uuid/uuid.hpp>
#include <boost/uuid/uuid_generators.hpp>
#include <boost/uuid/uuid_io.hpp>
```

**Comment by hansenms** [comment]
How should we deal with this. Simply disable the cloudbus on CentOS 6? Or does anybody know of another good library/method (which is cross platform) for generating a unique ID.

**Comment by hansenms** [comment]
And BTW, I hate CentOS

**Comment by naegelejd** [comment]
I, too, missed the step to install a newer Boost version (mentioned by Souheil in #4). The RHEL installation instructions actually don't contain a step for installing a newer Boost. I can make that an explicit step in the wiki so we avoid opening new issues regarding Boost on CentOS.

I did the following:

```bash
sudo wget http://repo.enetres.net/enetres.repo -O /etc/yum.repos.d/enetres.repo
sudo yum install boost-devel
```
after manually removing `boost-static`, which conflicted with this newer version.
source: http://vicendominguez.blogspot.com/2014/04/boost-c-library-rpm-packages-for-centos.html

BTW, installing a newer version of something is always an option, but installing unknown packages from random repos on the web seems a little hacky.

**Comment by hansenms** [comment]
If there is a way (or as in this case multiple ways) to get a compatible version of boost, them maybe we should just leave it like it is. I would however like to find a good way to make a unique ID without using a library, but we can defer that. Should we close this issues? Mark it as "wont fix" and move on?

**Comment by naegelejd** [comment]
Yes. I updated the wiki for RHEL installation to explicitly state how to install a newer Boost for now.

**Comment by hansenms** [comment]
OK closing it then.
