### ISSUE TITLE
Failed to load DLL

### ISSUE THREAD

**Issue by ps4735** [gadgetron/gadgetron#374]
Hello,
  I have installed gadgetron  according to the Windows installation VS2013 in my computer. Its operation system is Win10. And I would like to run the Hello World program. But it complained that 
![image](https://cloud.githubusercontent.com/assets/14343763/14973676/5116d980-111d-11e6-8eb0-fc5c885b9de6.png)
when I run the `gadgetron_ismrmrd_client.exe`.

**Comment by ps4735** [comment]
I have run the `set_gadgetron_path.bat`. But I did not set the path variable. I do not know how to set it.

**Comment by hansenms** [comment]
What is in your PATH environment variable?

Could you also set the environment variable ACE_DEBUG=1 and send the log with that enabled.

**Comment by ps4735** [comment]
My PATH environment is like that 

`C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5\bin`
`C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5\libnvvp`
`C:\Program Files (x86)\IntelSWTools\Trace Analyzer and Collector\9.1.2.024\bin`
`C:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2016.2.180\windows\mpi\intel64\bin`
`C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64_win\mpirt`
`C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\ia32_win\mpirt`
`C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64_win\compiler`
`C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\ia32_win\compiler`
`C:\Windows\system32`
`C:\Windows`
`C:\Windows\System32\Wbem`
`C:\Windows\System32\WindowsPowerShell\v1.0\`
`C:\Program Files\Microsoft SQL Server\110\Tools\Binn\`
`C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common`
`D:\matlab\runtime\win64`
`D:\matlab\bin`
`D:\matlab\polyspace\bin`
`C:\Program Files\Microsoft SQL Server\120\Tools\Binn\`
`C:\WINDOWS\system32`
`C:\WINDOWS`
`C:\WINDOWS\System32\Wbem`
`C:\WINDOWS\System32\WindowsPowerShell\v1.0\`
`C:\Users\luoqing\.dnx\bin`
`C:\Program Files\Microsoft DNX\Dnvm\`
`C:\Program Files\Microsoft SQL Server\130\Tools\Binn\`
`C:\Python27`
`C:\Program Files (x86)\CMake\bin`
`C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\`
`C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\`
`C:\Program Files\Git\cmd`
`C:\Program Files (x86)\CMake\bin`

**Comment by hansenms** [comment]
It looks like the path where you installed the Gadgetron is not in your PATH. You need to put the folder where all the Gadgetron DLLs are in your PATH. Can you try that and if you still have problems, please also add ACE_DEBUG=1 to your environment and run again.

**Comment by ps4735** [comment]
Thank you for your help. I have put the Gadgetron DLLs folder in my PATH. However, there is a new error. It is like this
![image](https://cloud.githubusercontent.com/assets/14343763/15003537/67912202-11df-11e6-9b19-51ac0103cd46.png)

**Comment by hansenms** [comment]
That error is fine. It is the Gadgetron detecting that the connection to the client has been terminated. You should have images in your output file, right?

**Comment by ps4735** [comment]
Thank you very much. There are reliably images in my output file. And you can close this as you like.
