### ISSUE TITLE
Add CPU based non-Cartesian FFT

### ISSUE THREAD

**Issue by hansenms** [gadgetron/gadgetron#38]
We need a non-Cartesian FFT on the CPU. This could either be implemented from scratch or by wrapping an existing library. The interface should conform to the existing nfft interface (on the GPU)

**Comment by ghisvail** [comment]
I intended to do it a while back but I was not sure whether this was much of a priority at the time. Besides, I wanted to use the [NFFT library](https://www-user.tu-chemnitz.de/~potts/nfft/) for that, but it was lacking support for other precisions than double. Since then, I have been cooperating with Jens Keiner to get the [library up on github](https://github.com/NFFT/nfft) and have a release with multi-precision support. Would you guys be happy with that ?

**Comment by hansenms** [comment]
Sounds like a reasonable approach to me. The really critical thing would be
if we could have a consistent interface on both CPU and GPU. That would
make it possible for us to do a lot of our current GPU stuff on the CPU as
well (e.g. for large datasets that need a lot of memory).

Is the NFFT library multithreaded?

Michael

**Comment by ghisvail** [comment]
> if we could have a consistent interface on both CPU and GPU

The NFFT library pretty much follows the design of FFTW, with an added precomputation step called after the non-uniform k-coordinates have been set on the NFFT plan. I'll check what you guys are doing on the GPU side but I am guessing it should be similar ?

> Is the NFFT library multithreaded? 

It uses OpenMP.

**Comment by hansenms** [comment]
Great, I say give it a go. Do you want me to assign you the issue?

**Comment by ghisvail** [comment]
Go ahead, I'll find some time to do it.

**Comment by hansenms** [comment]
You might need to assign it to yourself, if you can.

**Comment by ghisvail** [comment]
Just a quick update on that. I am currently working hard with Jens Keiner to get a new major release of NFFT out. I'll use that one as the basis for the cpu non-Cartesian FFT for Gadgetron.

**Comment by ghisvail** [comment]
With the release of NFFT ```v3.3.0.alpha4```, I believe I can now start the work on the CPU non-Cartesian FFT for Gagdetron.

FYI, the library is queued for upload in Debian experimental [1], and a PPA is available for easy installation on Ubuntu [2]. I'll have to test a Windows build at some point.

[1] https://ftp-master.debian.org/new/nfft_3.3.0~alpha4-1.html
[2] https://launchpad.net/~ghisvail/+archive/ubuntu/nfft-dev
