### ISSUE TITLE
RemoveROOverSampling bug

### ISSUE THREAD

**Issue by dchansen** [gadgetron/gadgetron#42]
Currently, the constant_noise_variance parameter in the [RemoveROOversampling]( https://github.com/gadgetron/gadgetron/blob/development/gadgets/mri_core/RemoveROOversamplingGadget.cpp) switches between two different code paths, which do the EXACT SAME THING. The only difference is a factor of sqrt(2), due to the different ways we handle normalization in the FFT.

The two paths should be merged into one, the redundant parameter removed, and all affected test cases should be updated to include the factor of sqrt(2).

**Comment by hansenms** [comment]
I agree.

**Comment by gtdeveloper5** [comment]
solved.
