### ISSUE TITLE
Message ID in data packages

### ISSUE THREAD

**Issue by roshtha** [gadgetron/gadgetron#454]
I have gone through this link: [https://github.com/gadgetron/gadgetron/wiki/Gadgetron-Streaming-Architecture]
Here is an excerpt from the above link:

> All packages that arrive on the socket will start with a message ID. Based on this ID, the Gadgetron delegates the responsibility of reading the package of the socket to a particular instance of a GadgetMessageReader ...

I learned that message ID identfies the particular reader class to be used for reading each data package. I also know that all packages to gadgetron will be in ISMRMRD format. So in which step we are associating message ID to data package? Thanks.

**Comment by hansenms** [comment]
Not all packages in Gadgetron are in ISMRMRD format. The Gadgetron can accept other kinds of data than ISMRMRD. I am not sure I understand your question about "in which step" you are associating the ID. The client and server sets the ID when they put packages on the wire. See for example:

https://github.com/gadgetron/gadgetron/blob/master/apps/clients/gadgetron_ismrmrd_client/gadgetron_ismrmrd_client.cpp#L1253

Where the client assigns the ID. 

Does that answer your question. To be able to help you better, I might need to know a bit more about what problem you are trying to solve.
