### ISSUE TITLE
Importing gadgetron source as a project in eclipse

### ISSUE THREAD

**Issue by tharagireesh** [gadgetron/gadgetron#469]
Hello,

Please provide help or hint to any documentation on how to import gadgetron source as a project in eclipse C++ IDE neon. I have a windows 10 64 bit operating system and Visual Studio 2015 installed. 

Thanks.

**Comment by hansenms** [comment]
Are you looking to use Visual Studio compilers, or do you want to use MinGW. 

You should be able to generate an eclipse project with:

    cmake -G"Eclipse CDT4 - MinGW Makefiles" <PATH TO GADGETRON SOURCE>

or 

    cmake -G"Eclipse CDT4 - NMake Makefiles" <PATH TO GADGETRON SOURCE>

I am assuming the NMake version would use visual studio, but to be honest, I have never tried and I have no idea how far you will get. Maybe give it a try and report back to us how far you get?

Hope this helps,
Michael
