### ISSUE TITLE
building with old MKL

### ISSUE THREAD

**Issue by KrisThielemans** [gadgetron/gadgetron#477]
At present, Gadgetron refuses to build when CMake finds a too old MKL:

```
MKL is found at /opt/intel/mkl

find MKL version : 11.0.1

CMake Error at CMakeLists.txt:261 (message):
   Gadgetron requires Intel MKL version >= 11.2.0
```
However, it can build after manually disabling MKL in the CMakeLists.txt. Is there a way to fall-back to this behaviour of MKL is too old?

**Comment by xueh2** [comment]
Not really. But you can get the free MKL community version
https://software.intel.com/en-us/articles/free-mkl

**Comment by hansenms** [comment]
The reason why we don't support older versions is not that it doesn't compile, but older versions have bugs that will cause errors in the reconstruction. As an example, the threaded (parallelized) SVD has bugs in previous versions. So we will not be "supporting" older versions. Does that make sense?

**Comment by KrisThielemans** [comment]
It does. No problem. However, we can build then without MKL? Sorry to be unclear.

**Comment by xueh2** [comment]
you can do

cmake -DMKLROOT_PATH= 

set cmake variable MKLROOT_PATH to empty will make cmake think there is no mkl available.

**Comment by hansenms** [comment]
@KrisThielemans if you don't have MKL, you need something else, like OpenBLAS, but you don't need MKL.

**Comment by KrisThielemans** [comment]
thanks guys.

cmake -DMKLROOT_PATH=

worked for me.
