### ISSUE TITLE
gadgetron_ismrmrd_client: Error caugt isn't an error

### ISSUE THREAD

**Issue by chrisdecker1201** [gadgetron/gadgetron#484]
Hallo,

I'm starting gadgetron_ismrmrd_client with nodeJs and listen to the stderr and stdout. When gadgetron isn't started I get the following output in the stdout and not in the stderr: Error caught: Error connecting using socket. 

I wondered if there is any reason why? For now I have a workaround by paring the content of the stdout for error but it would be nice to have it in the stderr.

Thanks for your help.

**Comment by hansenms** [comment]
Problem is here https://github.com/gadgetron/gadgetron/blob/master/apps/clients/gadgetron_ismrmrd_client/gadgetron_ismrmrd_client.cpp#L1853:

```
    } catch (std::exception& ex) {
        std::cout << "Error caught: " << ex.what() << std::endl;
	return -1;
    }
```
should be:

```
    } catch (std::exception& ex) {
        std::cerr << "Error caught: " << ex.what() << std::endl;
	return -1;
    }
```

@chrisdecker1201 want to put up a pull request to fix it?
