### ISSUE TITLE
reshaping the kspace in bartgadget.cpp is necessary?

### ISSUE THREAD

**Issue by siatjiasen** [gadgetron/gadgetron#488]
Hi, 

Following were several problems I encountered when using Bart_Recon.xml:
PI. 
In bartgadget.cpp, line 284-299: the reference and kspace data are reshaped from [E0, E1, E2, CHA] to  [E2, E0, E1, CHA]. However, in "https://github.com/mrirecon/bart/blob/master/src/misc/mri.h", the dimension order is defined as: [READ, PHS1, PHS2, COIL], the same as gadgetron. 
--In my opinion, it is not necessary to do the reshape. If I run BartRecon.xml on a 3D data with 2D acceleration, the recon chain will report error. 

P2. 
The "AcquisitionAccumulateTriggerGadget" used in BartRecon.xml will split the **integrated/separate calibration data** and **the sampled kspace data** into two hoNDArray. Then for a 3D data with 2D acceleration, the center of kspace hoNDArray is not fully sampled. 
However, the bart 'pics -l1' command relies on the kspace center to estimate a reasonable scaling factor, especially when using L1 regularization (Please see this thread: https://lists.eecs.berkeley.edu/sympa/arc/mrirecon/2017-02/msg00011.html  for more information). 
--Thus, for 'integrate reference scan', the reference data may also need to go into the kspace hoNDArray, while for 'separate reference scan', manually scaling of the kspace array is quite necessary for 'pics -l1'.

P3.
Bart uses multi-threaded FFTW, and by default, the thread number for multi-threaded FFTW is equal to omp_get_max_threads() (https://github.com/mrirecon/bart/blob/master/src/num/init.c). We noticed that if the available thread number is large, the multi-threaded FFT may slow down the 'ecalib' and 'pics' commands (my case is: data size of 320x320x256x24, CPU cores: 40cores 80 threads).

Thank you.
Best wishes,
Jia Sen

**Comment by hansenms** [comment]
@bijoumd78 please comment here.

@siatjiasen The BART Gadgets are really at a very prototype stage and you may well be right about all the issues. Feel free to suggest fixes and changes as appropriate.

**Comment by bijoumd78** [comment]
Hi,
Thanks for sharing your experience with "bart" gadget.
I agree "bart" still need work to handle more generic cases. However, only other users experience can help us improve the gadget. Therefore, I was wondering if you could share your data and the script you used to reconstruct the data for us to take close look at the error(s) generated. Also, suggestions are welcome on how to improve the gadget and I will be happy to implement them.
Thanks,
Mahamadou

**Comment by siatjiasen** [comment]
Hi,

Thank you both for the help.

1. Data
Please access the data (h5, converted from dat by siemens_to_ismrmrd) via this link: 
https://drive.google.com/open?id=0B-BR8ILdlBT0cVg0VEFVVmYwWUk

This data is 3D with size of 256 (ro) x 256 (pe1) x 80 (pe2), accelerated by GRAPPA x2 along PE1, and Partial Fourier along PE2, and using 12 channels. The data can be reconstructed by Generic_Cartesian_Grappa.xml perfectly as a reference. For BartRecon.xml, GenericReconPartialFourierHandlingPOCSGadget is needed after BartReconGadget.

2. The Bart script I used was:
/home/amax/bart/bart ecalib -r24 -k5 -m2 reference_data maps
/home/amax/bart/bart bart pics -d5 -l1 -r 0.004 -i 20  input_data maps ims

3. If the data is reshaped to [E2, E0, E1] (Problem 1 above), ‘ecalib’ will report 'calibration region can't be found'. For subsequent 'pics' recon, there is no fully sampled k-space center, 'pics' will scale the kspace wrongly, and the L1 regularization will not take effect (Problem 2 above). 

4. After correction, the logfile of BartRecon.xml was: 
2017-03-07 10:32:14 DEBUG [bartgadget.cpp:323] /home/amax/bart/bart bart pics -d5 -l1 -r 0.004 -i 20  input_data maps ims
2 maps.
ESPIRiT reconstruction.
Size: 5242880 Samples: 1762303 Acc: 2.98
**Calibration region...  (size: 32x24x32, pos: 113x116x24)
Scaling: 106.594673  (max = 179.090912/p90 = 106.594673/median = 58.540638)
Inverse scaling of the data: 106.594673**
l1-wavelet regularization: 0.004000
FISTA
#It 000: 1.000000   
#It 001: 0.219482   
#It 002: 0.041089   
#It 003: 0.010922   
#It 004: 0.007554   
#It 005: 0.006435   
#It 006: 0.006243   
#It 007: 0.006031   
#It 008: 0.006053   
#It 009: 0.006201   
#It 010: 0.006198   
#It 011: 0.006109   
#It 012: 0.006168   
#It 013: 0.006216   
#It 014: 0.006109   
#It 015: 0.006097   
#It 016: 0.006254   
#It 017: 0.006188   
#It 018: 0.006136   
#It 019: 0.006137   
Total Time: 33.165544

The result of BartRecon.xml was compared with GenericReconGrappa.xml: 
![qq 20170307113035](https://cloud.githubusercontent.com/assets/10806476/23640578/a5be94ba-0329-11e7-89ab-9b0e224e96e5.png).

There is still some residual aliasing artifact. I am working on solving it.

Best wishes,
Jia Sen

**Comment by bijoumd78** [comment]
@siatjiasen 
I assume you commented out in bartgadget.cpp, line 284-299 and other changes to bart configuration file. Therefore how did you get the "reference_data" and the "input_data", since the script doesn't show how they are generated ?
In the other hand, I do agree with you that the reshaping might not be necessary in other to make the gadget more generic. I am working on removing them and fixing some other issues.
Thanks,
Mahamadou.

**Comment by siatjiasen** [comment]
I just removed cmd1, and modified cmd2 and cmd3 correspondingly *for my only test data (3D with 2D acceleration)*:

   cmd2 << "bart resize -c 0 " << DIMS[0] << " 1 " << DIMS[1] << " " << " meas_gadgetron_ref reference_data";	 
      if (system(std::string("cd " + generatedFilesFolder + "&&" + cmd2.str()).c_str()))
	return GADGET_FAIL;
      
      if (DIMS[4] != 1)
	cmd3 << "bart reshape 1023 " << DIMS[0] << " " << DIMS[1] << " " << DIMS[2] << " " << DIMS[3] << " 1 1 1 1 1 " << DIMS[4] << " meas_gadgetron input_data";
      else
	cmd3 << "bart reshape 15 " << DIMS[0] << " " << DIMS[1] << " " << DIMS[2] << " " << DIMS[3] << " meas_gadgetron input_data";

      if (system(std::string("cd " + generatedFilesFolder + "&&" + cmd3.str()).c_str()))
	return GADGET_FAIL;
