### ISSUE TITLE
Gadgetron 3D with 2 echos

### ISSUE THREAD

**Issue by Newbie27** [gadgetron/gadgetron#490]
Hello every one,

I'm a newbie of Gadgetron. I've just discovered it and i'm having a hard time understanding .
well i've been testing the reconstruction of a 3D data with 2 echos .
i've converted it from Siemens to ISMRMRD and then i've tried sending it to the gadgetron server with a default configuration file and then a Generic_Cartesian_Grappa.xml and it just won't work: 

> 2017-03-24 15:17:35 DEBUG [BucketToBufferGadget.cpp:665] Encoding space : cartesian - FOV : [ 256 116 112 ]  - Matris size : [ 512 232 224 ] 
> 2017-03-24 15:17:35 DEBUG [BucketToBufferGadget.cpp:670] Sampling limits : - RO : [ 42 128 255 ] - E1 : [ 0 116 231 ] - E2 : [ 0 112 223 ]
> 2017-03-24 15:17:35 DEBUG [BucketToBufferGadget.cpp:551] Data dimensions [RO E1 E2 CHA N S SLC] : [256 232 224 4 2 8 1]
 
it gets here and it won't work . i waited 30min but i guess something is wrong. 
I'll put the ISMRMRD Header here :

`<?xml version="1.0"?>
<ismrmrdHeader xmlns="http://www.ismrm.org/ISMRMRD" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema" xsi:schemaLocation="http://www.ismrm.org/ISMRMRD ismrmrd.xsd">
	<studyInformation>
		<studyTime>03:46:23</studyTime>
	</studyInformation>
	<measurementInformation>
		<measurementID>40480_21647992_21647997_558</measurementID>
		<patientPosition>HFS</patientPosition>
		<protocolName>SPGR</protocolName>
		<frameOfReferenceUID>1.3.12.2.1107.5.2.36.40480.1.20170322135200093.0.0.0</frameOfReferenceUID>
	</measurementInformation>
	<acquisitionSystemInformation>
		<systemVendor>SIEMENS</systemVendor>
		<systemModel>Verio</systemModel>
		<systemFieldStrength_T>2.893620</systemFieldStrength_T>
		<relativeReceiverNoiseBandwidth>0.793000</relativeReceiverNoiseBandwidth>
		<receiverChannels>4</receiverChannels>
		<coilLabel>
			<coilNumber>0</coilNumber>
			<coilName>HeadMatrix:H3P</coilName>
		</coilLabel>
		<coilLabel>
			<coilNumber>1</coilNumber>
			<coilName>HeadMatrix:H4P</coilName>
		</coilLabel>
		<coilLabel>
			<coilNumber>2</coilNumber>
			<coilName>HeadMatrix:H1P</coilName>
		</coilLabel>
		<coilLabel>
			<coilNumber>3</coilNumber>
			<coilName>HeadMatrix:H2P</coilName>
		</coilLabel>
		<institutionName>SCE</institutionName>
	</acquisitionSystemInformation>
	<experimentalConditions>
		<H1resonanceFrequency_Hz>123202562</H1resonanceFrequency_Hz>
	</experimentalConditions>
	<encoding>
		<encodedSpace>
			<matrixSize>
				<x>512</x>
				<y>232</y>
				<z>224</z>
			</matrixSize>
			<fieldOfView_mm>
				<x>256.000000</x>
				<y>116.000000</y>
				<z>112.000000</z>
			</fieldOfView_mm>
		</encodedSpace>
		<reconSpace>
			<matrixSize>
				<x>256</x>
				<y>232</y>
				<z>224</z>
			</matrixSize>
			<fieldOfView_mm>
				<x>128.000000</x>
				<y>116.000000</y>
				<z>112.000000</z>
			</fieldOfView_mm>
		</reconSpace>
		<encodingLimits>
			<kspace_encoding_step_1>
				<minimum>0</minimum>
				<maximum>231</maximum>
				<center>116</center>
			</kspace_encoding_step_1>
			<kspace_encoding_step_2>
				<minimum>0</minimum>
				<maximum>223</maximum>
				<center>112</center>
			</kspace_encoding_step_2>
			<average>
				<minimum>0</minimum>
				<maximum>7</maximum>
				<center>0</center>
			</average>
			<slice>
				<minimum>0</minimum>
				<maximum>0</maximum>
				<center>0</center>
			</slice>
			<contrast>
				<minimum>0</minimum>
				<maximum>1</maximum>
				<center>0</center>
			</contrast>
			<phase>
				<minimum>0</minimum>
				<maximum>0</maximum>
				<center>0</center>
			</phase>
			<repetition>
				<minimum>0</minimum>
				<maximum>0</maximum>
				<center>0</center>
			</repetition>
			<set>
				<minimum>0</minimum>
				<maximum>0</maximum>
				<center>0</center>
			</set>
			<segment>
				<minimum>0</minimum>
				<maximum>0</maximum>
				<center>0</center>
			</segment>
		</encodingLimits>
		<trajectory>cartesian</trajectory>
		<parallelImaging>
			<accelerationFactor>
				<kspace_encoding_step_1>1</kspace_encoding_step_1>
				<kspace_encoding_step_2>1</kspace_encoding_step_2>
			</accelerationFactor>
			<calibrationMode>other</calibrationMode>
			<interleavingDimension>other</interleavingDimension>
		</parallelImaging>
	</encoding>
	<sequenceParameters>
		<TR>35.000000</TR>
		<TE>2.360000</TE>
		<TE>7.270000</TE>
		<TI>300.000000</TI>
		<flipAngle_deg>30.000000</flipAngle_deg>
		<sequence_type>Flash</sequence_type>
	</sequenceParameters>
	<userParameters>
		<userParameterDouble>
			<name>MaxwellCoefficient_0</name>
			<value>0.000000</value>
		</userParameterDouble>
		<userParameterDouble>
			<name>MaxwellCoefficient_1</name>
			<value>0.000000</value>
		</userParameterDouble>
		<userParameterDouble>
			<name>MaxwellCoefficient_2</name>
			<value>0.000000</value>
		</userParameterDouble>
		<userParameterDouble>
			<name>MaxwellCoefficient_3</name>
			<value>0.000000</value>
		</userParameterDouble>
	</userParameters>
</ismrmrdHeader>
`

**Comment by hansenms** [comment]
What kind of specs does that server have? It is a big dataset, are you sure you have enough RAM?

Can you upload an example dataset to somewhere, and I will give it a try.

**Comment by Newbie27** [comment]
That's also what i thought. I run on a 8GO Ram Machine with a intel i7 proc . i also thought perhaps there's something i should change in my XML configuration. Should i change the N_Dimension and the S_Dimention? Could you please explain them more to me.
It's a 10GO Data . i'm trying to upload it .
I can thank you enough for your time.

**Comment by hansenms** [comment]
There is no way you will be able to reconstruct that dataset on a machine with 8GB of RAM, it is just not going to happen. So you are probably running out of memory. 

N and S dimensions are just dimensions that you can choose to included in your reconstruction matrix. They could be something like repetition, phase, echo or something like that. You would have to set them. It looks like you have N set to echo (contrast) and S set to average. That means that you are passing on the entire volume to the recon gadget. Again, it is a huge amount of data. I cannot imagine it working on that hardware.

**Comment by Newbie27** [comment]
Thank you so much for the explanation. And that's true It Just won't work.

Rim Tounsi
Étudiante au cycle ingénieur en Réseaux et Télécommunications à l'INSAT.

2017-03-25 3:38 GMT+01:00 Michael Hansen <notifications@github.com>:
