### ISSUE TITLE
Where to put general image processing functionalities?

### ISSUE THREAD

**Issue by xueh2** [gadgetron/gadgetron#494]
Hi, 

@hansenms @dchansen 
I have some general image processing functionalities, such as region growing algorithm, connected region labeling etc. 

The question is where to put them in gadgetron. Should we add a toolbox (gadgetron_toolbox_image_processing, e.g.)?

**Comment by hansenms** [comment]
I would vote for `$GADGETRON_SOURCE/toolboxes/image_processing` for now. 

@dchansen thoughts?

**Comment by dchansen** [comment]
That sounds pretty reasonable. I have some denoising stuff that would fit
in there as well.
