### ISSUE TITLE
bug in chroot/CMakeLists.txt with CUDA

### ISSUE THREAD

**Issue by KrisThielemans** [gadgetron/gadgetron#524]
Line https://github.com/gadgetron/gadgetron/blob/master/chroot/CMakeLists.txt#L41 is problematic:
```cmake
get_filename_component(CUDABLAS_LIB_DIR ${CUDA_CUBLAS_LIBRARIES} PATH)
```
This will fail if `${CUDA_CUBLAS_LIBRARIES}` is set to more than 1 library, which apparently happens on Ubuntu 17.04. See https://www.jiscmail.ac.uk/cgi-bin/webadmin?A2=ind1707&L=CCP-PETMR-DEVEL&F=&S=&X=AE7343ED237D3E95F9&Y=k.thielemans%40ucl.ac.uk&P=12613

There seem to be similar lines with the same problem in this file.

**Comment by xpjiang** [comment]
There is also an error in Line 41
 get_filename_component(CUDABLAS_LIB_DIR ${CUDA_CUFFT_LIBRARIES} PATH)
when using windows 10 and vs2015.
And the CUDA_CUFFT_LIBRARIES = C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0/lib/x64/cublas.libC:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0/lib/x64/cublas_device.lib

**Comment by KrisThielemans** [comment]
probably the same as #480.

**Comment by KrisThielemans** [comment]
what about replacing all of these lines with
```cmake
foreach(_lib IN LISTS ${CUDA_LIBRARIES} ${CUDA_CUFFT_LIBRARIES} ${CUDA_CUBLAS_LIBRARIES})
  get_filename_component(_libdir ${_lib} PATH)
  set (LIBRARY_PATHS ${LIBRARY_PATHS}:${_libdir})
endforeach()
list(REMOVE_DUPLICATES LIBRARY_PATHS )
```
sorry, I cannot test as I don't have access to a relevant machine

**Comment by KrisThielemans** [comment]
By the way, this directory should only be included on Linux.
