### ISSUE TITLE
Unable to find the CBCT Sample Data Set

### ISSUE THREAD

**Issue by linda2341** [gadgetron/gadgetron#525]
Dear Gadgetron.
I try to access https://gadgetrondata.blob.core.windows.net/gadgetrongithubio/testdata/standalone/cbct/
but unable to find the data set. It seems the page is down.

**Comment by hansenms** [comment]
@xueh2 can you look at that BLOB store in the Azure account. You are not supposed to be able to access the folder as indicated by the URL, but maybe the individual files are not referenced appropriately in the Wiki. @linda2341 where are you trying to access this link from? Can you send us the link to the Wiki page?

**Comment by xueh2** [comment]
I did the check in the Azure. The CBCT test data is in the archive:


e.g.


https://gadgetrondata.blob.core.windows.net/gadgetrongithubio/testdata/standalone/cbct/projections.hdf5


data can be downloaded with this link. Maybe we should update wiki page url?


________________________________

**Comment by linda2341** [comment]
Thank you for the response.
Yeah, I remember I got the link from the Wiki page, but now it's working and I can get the data.

Thank you very much
