### ISSUE TITLE
BucketToBufferGadget for Partial Fourier

### ISSUE THREAD

**Issue by chandnisp77** [gadgetron/gadgetron#529]
Hello all,

I am using `gadgetron` to reconstruct images from a partial fourier `haste` sequence. The partial fourier reconstruction is done using matlab. 
I understood that the `BucketToBufferGadget` fills `IsmrmrdReconData` structures as phase encoding center (N/2) in alignment with the center specified in the encoding limits.
Thus, the sampled lines are kept along the centre part of k-space. But the partial fourier reconstruction algorithm requires the data to be kept at either the upper part or lower part of k-space. Is there a specific gadget to arrange data acquisitions for partial fourier reconstruction? 

Thanks.

**Comment by siatjiasen** [comment]
Hi,

The functions `fillSamplingDescription() `and `Stuff()` in `BucketToBufferGadget` both provides two parameters: `space_matrix_offset_E1 ` and `space_matrix_offset_E2` and some conditional statements to acheive your desired function of "arrange data acquisitions for partial fourier reconstruciton". The calculation of `space_matrix_offset_E1/E2 ` also depends on the `encoding.encodingLimits `and the `encoding.encodedspace.matrixsize` provided in the data header.  

It is also helpful if you can provide a test data to reproduce the problem.

**Comment by xueh2** [comment]
Hi,

You are right that default arrangement of kspace is to make sure ksapce center line is the stored center line.

To perform partial fourier handling, there is a gadget:

GenericReconPartialFourierHandlingPOCSGadget.h

This gadget actually determine which part of kspace is acquired and try to fill missing part.

Making sure stored kspace center is the center line will simplify processing steps e.g. kspace filtering. It could be better to implement partial fourier handling with this convention as well; such is to cope with both partial fourier modes (missing kspace is upper/lower part).

Regards

Hui
