### ISSUE TITLE
DICOM and Nifty import

### ISSUE THREAD

**Issue by alabamagan** [gadgetron/gadgetron#530]
Hi I am new to Gadgetron, I wonder if there are any interface to read either DICOM or nii.gz file?
I do see DICOM writers but for reader, I only find HDF5 readers

**Comment by xueh2** [comment]
HI Matthew,

To export dicom, gadgetron uses dcmtk. You need to install this package when compiling gadgetron. Then in the gadget chain, you can add DicomFinish gadget to save dicom images.

One example is in gadgetron<https://github.com/gadgetron/gadgetron>/gadgets<https://github.com/gadgetron/gadgetron/tree/master/gadgets>/dicom/dicom.xml

Currently gadgetron cannot export nifti format; but it can save images are analyze format. When you call the client “gadghetron_ismrmrd_client”, parameter

-F [ --outformat ] arg (=h5)          Out format, h5 for hdf5 and hdr for analyze image

-F hdr will export analyze format images.

Regards

Hui Xue

**Comment by teracamo** [comment]
Thanks for the prompt replay Xue! 
I am aware that gadgetron built DICOM writer, but what about reader? For example, DICOM tag  (0002,0010) state that the data might be compressed with various formats like JPEG...etc. So do I have to manually convert all targets to HDF5 before pushing them into Gadgetron pipeline?

**Comment by xueh2** [comment]
Hi Matthew,

Currently there is no diocm reader. So it means we cannot send dicom images to gadgetron.  We can send ismrmrd image to gadgetron.

I think dcmtk will handle compressed dicom well if compiled with jpg package.

Regards

Hui
