### ISSUE TITLE
linking problems with boost_python when using python3

### ISSUE THREAD

**Issue by KrisThielemans** [gadgetron/gadgetron#550]
When using python3 on Linux, we are getting linking errors, see https://github.com/CCPPETMR/SIRF-SuperBuild/issues/57. The internet says that we would have to use
```
find_package(Boost COMPONENTS python-py35)
```
on Ubuntu. Sadly, the suffix changes with OS, Python version, package manager etc etc. Caffe has [some logic to fix this](https://github.com/intel/caffe/blob/c7ed32772affaf1d9951e2a93d986d22a8d14b88/cmake/Dependencies.cmake#L247) which we might be able to use

**Comment by astrophys** [comment]
I encountered similar problems.  I'm using boost-1.67, python-3.5 and cmake-3.14.0-rc2 on Ubuntu-16.04.  A few points:

1. Cmake needs to be compatible (ours was too old).  See  https://stackoverflow.com/a/42124857/4021436
2. Calls in the CMakeLists.txt w/r/t both boost and python/numpy must be adjusted.  These are (roughly) the changes that I made:
   a)  `CMakeLists.txt`
      - `find_package(PythonLibs 2)` -> `find_package(PythonLibs 3)`


   b) `gadgets/CMakeLists.txt` : 
      - `find_package(Boost COMPONENTS python system thread)`  -> `find_package(Boost COMPONENTS python35 system thread)`
      - `if (Boost_PYTHON_FOUND AND PYTHONLIBS_FOUND AND NUMPY_FOUND)` -> `if (Boost_PYTHON35_FOUND AND PYTHONLIBS_FOUND AND NUMPY_FOUND)`
      - `if(NOT Boost_PYTHON_FOUND)` -> `if(NOT Boost_PYTHON35_FOUND)`


   c) `cmake/FindNumpy.cmake`:
      - `find_package(PythonInterp REQUIRED)` -> `find_package(Python3 REQUIRED)`
      - `if(NOT PYTHONINTERP_FOUND)` -> `if(NOT Python3_FOUND)`
      - `execute_process(COMMAND "${PYTHON_EXECUTABLE}" "-c"` -> `execute_process(COMMAND "${Python3_EXECUTABLE}" "-c"`
      - `find_package(PythonInterp)` -> `find_package(Python3)`


   d) `toolboxes/CMakeLists.txt`:
      - `find_package(Boost COMPONENTS python system thread)` -> `find_package(Boost COMPONENTS python35 system thread)`
      - `if (Boost_PYTHON_FOUND AND Boost_SYSTEM_FOUND AND Boost_THREAD_FOUND)` -> `if (Boost_PYTHON35_FOUND AND Boost_SYSTEM_FOUND AND Boost_THREAD_FOUND)`


   e) `apps/gadgetron/CMakeLists.txt`
      - `find_package(Boost COMPONENTS python)` -> `find_package(Boost COMPONENTS python35)`
      - `if (Boost_PYTHON_FOUND AND PYTHONLIBS_FOUND AND NUMPY_FOUND)` -> `if (Boost_PYTHON35_FOUND AND PYTHONLIBS_FOUND AND NUMPY_FOUND)`

For a different version of python (other than 3.5), change the 35 to the appropriate version (e.g. 37 for python-3.7).

**Comment by KrisThielemans** [comment]
possibly addressed via https://github.com/gadgetron/gadgetron/commit/ce74d69243b9733176ea7464e4570052a7dc6507 and its fix https://github.com/gadgetron/gadgetron/commit/b991f5838c967a98728a5e7259424cbb58a247a2. i haven't tested it.
