### ISSUE TITLE
option to disable Python support (and other things?)

### ISSUE THREAD

**Issue by KrisThielemans** [gadgetron/gadgetron#551]
In some cases, it would be nice to be able to compile without Python (or Matlab) support. For instance, to avoid #550, or just to speed-up build time if you're not interested in Python. This would be easily doable by adding an option `DISABLE_PYTHON_SUPPORT` or something, and change the CMakeLists.txt accordingly. Would you be willing to accept a PR for this?

Somewhat related is #507

**Comment by xueh2** [comment]
Hi Kris,

I think this option is reasonable. The default value could be false.

Regards

Hui

**Comment by KrisThielemans** [comment]
great. I've created PR #552 for this. Note that I've chosen to name the variable `BUILD_PYTHON_SUPPORT` (Defaulting to `On`) as opposed to `DISABLE`, as you had some `BUILD` variables already.
