### ISSUE TITLE
SimpleReconGadget produces only real data (imaginary data is 0)

### ISSUE THREAD

**Issue by spichardo** [gadgetron/gadgetron#567]
Hi,

I'm trying to do a phase data extraction from a simple single channel (body coil) GRE sequence.

I modified a copy of default.xml where I simply added the mask to extract mag,real,imag and phase data

```xml
...
     <gadget>
      <name>SimpleRecon</name>
      <dll>gadgetron_mricore</dll>
      <classname>SimpleReconGadget</classname>
     </gadget>

     <gadget>
      <name>ImageArraySplit</name>
      <dll>gadgetron_mricore</dll>
      <classname>ImageArraySplitGadget</classname>
     </gadget>

    <gadget>
      <name>Extract</name>
      <dll>gadgetron_mricore</dll>
      <property><name>extract_mask</name><value>15</value></property>
      <classname>ExtractGadget</classname>
    </gadget>
...
```
The images are indeed "extracted", but the imaginary data is always 0  for all images. As it is, magnitude image seems only reconstructed from pure real data, which it does not make too much sense. I wonder if SimpleRecon is doing something that is eliminating the imaginary data. From a simple inspection of the cpp code I couldn't tell.

In multi-coil GRE data, I managed to successfully to get imaginary and phase data by modifying a copy of Generic_Cartesian_Grappa.xml and adding the ExtractGadget as suggested in

https://groups.google.com/forum/#!topic/gadgetron/25Lhgxzojn0

Do you have any idea how to make work to get the phase data using the default.xml config and the SimpleRecon gadget?

Thanks
Sam

**Comment by srapacchi** [comment]
Hi Sam,
 I had a similar issue in the past. I ended up with the pipeline:
 /gadgets/mri_core/config/Generic_Cartesian_FFT.xml

which uses the GenericReconCartesianFFTGadget. 
Please try this reconstruction, it should work and you should be able to retrieve all components of the complex images with the ExtractGadget.

Stan

**Comment by dchansen** [comment]
The SimpleRecon gadget returns the magnitude of the signal, and not the amplitude, so getting the phase is not possible. 
Using the Generic_Cartesian_FFT.xml pipeline as @srapacchi suggest should solve your problem.
