### ISSUE TITLE
Compilation almost passed using cuda 9.1

### ISSUE THREAD

**Issue by valeryozenne** [gadgetron/gadgetron#574]
Hi,

I'm reporting a possible error using the last version of cuda 9.1 on Ubuntu 16.04 during the compilation of the Gadgetron, I attached the full log in case. 
It is for informational purpose, I finally use the cuda 8.0 version that passed.

Disabling the operators_test (in the cmake I guess) might allow to compile without error 

[log-gadgetron.txt](https://github.com/gadgetron/gadgetron/files/1668173/log-gadgetron.txt)

**Comment by melrobin** [comment]
I'm having the same problem.  No solution in sight it seems.

**Comment by dchansen** [comment]
So, this is a bug in Cuda, but I think our solution will be to simply disable the tests for now.
There will be an update later today, which fixes the issue.

**Comment by dchansen** [comment]
Fixed in master.
