### ISSUE TITLE
Convert python support to 3.x

### ISSUE THREAD

**Issue by dchansen** [gadgetron/gadgetron#579]
Python 2 is slowly being abandoned, and we should move our support to 3.x.

I would suggest that we abandon 2.7 entirely as it's not realistic for us to support both in the long term. 
Comments?

**Comment by MalteRoehl** [comment]
That would be a really good idea I think. Especially that new potentiell relevant libaries start to be only realistically usable in their python 3 version.

**Comment by kristofferknudsen** [comment]
I'm closing this issue, as only Python 3 is supported going forwards.
