### ISSUE TITLE
Linux RHEL CentOS Installation has obsolete repo

### ISSUE THREAD

**Issue by TWhelan3** [gadgetron/gadgetron#587]
The instructions say to get Boost from the enetres repo, which seems to be permanently down now. Unfortunately that seems to be the only repo where Boost>=1.55 was available.

**Comment by xueh2** [comment]
fixed

you can compile boost and install:

cd ~/software
wget https://dl.bintray.com/boostorg/release/1.66.0/source/boost_1_66_0.tar.gz
tar xvf ./boost_1_66_0.tar.gz
cd boost_1_66_0
./bootstrap.sh
sudo ./b2 --layout=versioned --build-type=complete address-model=64 install -j 20
