### ISSUE TITLE
Gadgetron and Qt5

### ISSUE THREAD

**Issue by melrobin** [gadgetron/gadgetron#590]
Is it possible to build Gadgetron using Qt5?  The CMake tags only appear to reference Qt4 which is quite old by now.

**Comment by dchansen** [comment]
I don't think anyone has tried. 
Do you need the Qt components of Gadgetron? It is only used for a single application (a GUI for 2d golden ration reconstruction).

**Comment by melrobin** [comment]
I encountered CMake errors in building Gadgetron.  Some are from Qt, but others are from ACE.  ACE is listed as optional, but is it indeed required?  

I would prefer to build without GUI elements.
