### ISSUE TITLE
libplplotd link problem on ubuntu 18.04

### ISSUE THREAD

**Issue by KrisThielemans** [gadgetron/gadgetron#608]
we have a report by @andersenthomas of gadgetron compilation on ubuntu 18.10 (with plplot-dev installed), where there are linking problems with using `libplplotd.so` and `libplplotcxxd.so`. Those libraries do not exist. It seems that this version of ubuntu comes with an upgraded plplot 5.13.0. Anyone any suggestions?

**Comment by siatjiasen** [comment]
1. According to /gadgetron/Docker/base folder, LTS versions (16.04, 18.04) of Ubuntu are recommended. Using Ubuntu 18.10 may not be stable enough.
2. Are you using the newest Gadgetron version? Gadgetron updated its gadgetron/cmake/FindPLplot.cmake. Please give it a try.

**Comment by KrisThielemans** [comment]
Of course, you're not supporting Ubuntu 18.10 yet, so feel free to ignore this for a while (but I thought I'd file it already).

@andersenthomas, could you check which Gadgetron commit you were using? If it was the default SIRF-SuperBuild version, it'd be e7eb430673eb3272e8a821b51750c0a2a96dafed which indeed doesn't have the plplot fix yet. Or you could just check if your gadgetron/cmake/FindPLplot.cmake looks like [current master](https://github.com/gadgetron/gadgetron/blob/master/cmake/FindPLplot.cmake).

By the way, I would have thought it'd be better to use `find_library`, possibly with some `HINTS`.

https://github.com/gadgetron/gadgetron/blob/master/cmake/FindPLplot.cmake

**Comment by KrisThielemans** [comment]
sorry. I had the Ubuntu version number wrong of course
