### ISSUE TITLE
any plan to target a newer base system

### ISSUE THREAD

**Issue by congzhangzh** [gadgetron/gadgetron#615]
Any plan to target a newer base system like debian buster/ubuntu 18.04, as the cmake module of hdf and boost all changed which need upgrade some part of gadgetron.

**Comment by siatjiasen** [comment]
Please check the folder: gadgetron/docker/base/. Ubuntu 18.04 is already supported. 

Also make sure the ismrmrd version is matched with gadgetron version. Gadgetron team upgraded ismrmrd by adding new field which influenced gadgetron_ismrmrd_client in Gadgetron.

**Comment by congzhangzh** [comment]
@siatjiasen Tks, get it on https://hub.docker.com/u/gadgetron/?page=3
