### ISSUE TITLE
Cannot download CULA with the given link.

### ISSUE THREAD

**Issue by deepdumbo** [gadgetron/gadgetron#619]
I am following [Windows Installation]
https://github.com/gadgetron/gadgetron/wiki/Windows-Installation

But I can't download CULA with the link:
http://www.culatools.com/downloads/dense

Any suggestions? Thanks a lot!

**Comment by siatjiasen** [comment]
Please see the 'warning' from Gadgetron team:
" Windows is not the easiest environment in which to work with the Gadgetron. As indicated in [List of Dependencies], the Gadgetron relies on multiple external libraries. Many of those libraries are not available as easy install packages and must be compiled separately. "

CULA website, forum and support have been closed for years. 

I have a copy of CULA-dense-R18.exe on disk, but I don't recommend to try.

**Comment by dchansen** [comment]
The Windows installation guide is in serious need of updating.
Gadgetron no longer uses CULA for anything.

**Comment by deepdumbo** [comment]
Thanks a lot for all of your help and response. I will try the Linux installation instead. Thank you!
