### ISSUE TITLE
CMakeLists.txt adds flags based on unsafe compiler version checking

### ISSUE THREAD

**Issue by KrisThielemans** [gadgetron/gadgetron#648]
CMakeLists.txt contains [lines like this](https://github.com/gadgetron/gadgetron/blob/7dab616d17198f9b902eb763dd6d7dcd669f279c/CMakeLists.txt#L148) on Unix (not Apple)
```cmake
   if(CMAKE_CXX_COMPILER_VERSION VERSION_LESS "4")
     set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fPIC -std=c++11")
    else()
       set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fPIC -std=c++14")
    endif()
```
This is unsafe (and actually sometimes crashes some of our Travis builds now, one example is [here](https://travis-ci.org/CCPPETMR/SIRF-SuperBuild/jobs/400142753)). The version check assumes the compiler is gcc. Moreover, the `std=c++14` flag seems only introduced from gcc  5.2 .

According to the [CMake CXX_STANDARD](https://cmake.org/cmake/help/latest/prop_tgt/CXX_STANDARD.html#prop_tgt:CXX_STANDARD) doc, The following should work
```cmake
  set(CMAKE_CXX_STANDARD 14)
```
as it should fall back to C++11 if 14 is not supported by the compiler. (You could set `CMAKE_CXX_STANDARD_REQUIRED` to 11). Sadly, this requires CMake 3.1 which is higher than your minimum requirement.

I would also recommend using 
```cmake
set(CMAKE_POSITION_INDEPENDENT_CODE ON)
```
as opposed to explicitly adding `fPIC`. This does require CMake 2.9.

Time to change your minimum CMake requirements? Or we can put in some code that checks on CMake version.

**Comment by Takishima** [comment]
Why not do something like this ?

    include(CheckCXXCompilerFlag)
    set(CXX_STANDARDS 17 14 11)
     
    set(CXX_STANDARD_FOUND 0)
    foreach(year ${CXX_STANDARDS})
      check_cxx_compiler_flag(-std=c++${year} COMPILER_SUPPORTS_CXX${year})
      if(COMPILER_SUPPORTS_CXX${year})
        set(CXX_STANDARD_FOUND 1)
        message(STATUS "Compiling using C++${year} standard")
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++${year}")
        break()
      endif(COMPILER_SUPPORTS_CXX${year})
    endforeach()
     
    if(NOT CXX_STANDARD_FOUND)
      message(FATAL_ERROR "The compiler does not support the most recent C++ standards. Please change compiler")
    endif(NOT CXX_STANDARD_FOUND)
