### ISSUE TITLE
Testdata link on CBCT is broken

### ISSUE THREAD

**Issue by jackyko1991** [gadgetron/gadgetron#687]
Hi I am trying to download the test data for CBCT reconstruct. However the URL is broken.

Can anyone help to fix it？

**Comment by xueh2** [comment]
did you do "python get_data.py"?

**Comment by jackyko1991** [comment]
I am trying to follow the instruction [here](https://github.com/jackyko1991/gadgetron/wiki/Cone-beam-CT-(CBCT)-reconstruction). The data cannot download and I have no idea where is  "get_data.py"
