### ISSUE TITLE
required boost version conflicts with matlab's boost

### ISSUE THREAD

**Issue by KrisThielemans** [gadgetron/gadgetron#711]
42247f78c97ef3aff3d316400c51ae5e70d6d7bb set required boost version to 1.64.0. When using Matlab, [we are struggling with boost version conflicts](https://github.com/CCPPETMR/SIRF/issues/240) as Matlab currently comes with shared libs of Boost 1.56.0 (checked with R2016b and R2018a). At present, the only way around that I found is to compile SIRF with Boost 1.56.0 as well.

@dchansen, do you have version conflicts, or does everything work well? Any idea why? Also, would you be able to downgrade your requirements to boost 1.56.0?

**Comment by KrisThielemans** [comment]
oops. my memory failed me. This was because of #671.

So... did anyone try MATLAB with recent Gadgetron? No problems at all?

**Comment by dchansen** [comment]
Matlab is indeed a constant source of problems and agony. 
I am having the same issues on my system - I have tried various workarounds, but without any luck.

Downgrading the requirements is not really an option. We're officially supporting Ubuntu 18.04, and the host of libraries and versions on that platform. 
Matlab should be staticly linking its libraries if it can't use the ones on the system - but I don't think we'll have any luck convincing Mathworks of that. 

We've had ton of issues with this on Matlab over the years (it's also the reason you can't have mixed Matlab and python chains), and I think the only sane way forward is for the MatlabGadget to live in its own process, where it won't be bothering anyone else. 
I'll think a little more on this, and how we might sandbox of Matlab with the least amount of trouble.

**Comment by KrisThielemans** [comment]
what about linking with static boost libraries? We'll try to give that a go for SIRF

**Comment by KrisThielemans** [comment]
This doesn't work for us, as SIRF is built as a set of shared libraries to be able to call it from Python or Matlab, but then it needs `-fPIC` on Linux.

**Comment by KrisThielemans** [comment]
I did a very quick test and Gadgetron compiles and seems to run fine with boost static libraries. Not sure if that helps you.
