### ISSUE TITLE
linking problem on OSX

### ISSUE THREAD

**Issue by KrisThielemans** [gadgetron/gadgetron#716]
we're [getting](https://travis-ci.org/CCPPETMR/SIRF/jobs/465480695)
```
Undefined symbols for architecture x86_64:
  "Gadgetron::NFFT_plan<Gadgetron::hoNDArray, float, 2u>::compute_NFFT_C2NC(Gadgetron::hoNDArray<Gadgetron::complext<float> >&, Gadgetron::hoNDArray<Gadgetron::complext<float> >&)", referenced from:
      vtable for Gadgetron::hoNFFT_plan<float, 2u> in hoNFFT_test.cpp.o
```
Probably v3.17.0 was ok.

I have no idea how this can happen.

**Comment by KrisThielemans** [comment]
Confirmed that v3.17.0 works fine, [example (confusing as parallel build) log-file](https://api.travis-ci.org/v3/job/465629097/log.txt).

**Comment by dchansen** [comment]
But only on OSX? That is a problem... 

We don't currently have integration tests running on OSX, and I don't have access to an OSX machine, so replicating this will be tricky. 
We Gadgetron 4.0 in the works, where we switched to target based CMake files. That should (hopefully) help fix this sort of issue. 
For now, if you could git-bisect your way to a specific commit, I would have a much easier time figuring out what the issue is.

**Comment by KrisThielemans** [comment]
I'm sorry. I don't have an OSX machine either. If you cannot find someone, I'll ask someone from our lab, but it'll be January I'm afraid. Ping me if needed.

**Comment by rijobro** [comment]
The problematic commit is 82b37efcf03153c35e8cc1fda005f3dd028c44a2 (as mentioned in #719, didn't realise this issue exitsed).

**Comment by dchansen** [comment]
So..... the problem seems to be that the symbol defined in NFFT.hpp are somehow not generated on OSX.
Why? I simply don't know. Everything works with clang on Linux, which in theory should be the same compiler.

**Comment by KrisThielemans** [comment]
Apple-clang is not clang (see e.g. [here](https://news.ycombinator.com/item?id=16545037)).

@rijobro, can you with some tool see what symbols are in `gadgetron_toolbox_cpunfft.dylib` (or whatever it's called)? And then we compare with some other library I guess.

**Comment by KrisThielemans** [comment]
oops. Ignore my statement about `gadgetron_toolbox_cpunfft.dylib`. I was looking for `hoNFFT`.

**Comment by KrisThielemans** [comment]
oops. Ignore my statement about ignoring my statement about `gadgetron_toolbox_cpunfft.dylib`. It is in the `hoNFFT::vtable` after all. I think I'll delete these 2 comments to avoid embarassment!

**Comment by KrisThielemans** [comment]
clutching at straws here... what about saying
```C++
template
class EXPORTNFFT Gadgetron::hoNFFT_plan<float, 1U>;
```
making the `unsigned int` explicit? ([Original line](https://github.com/gadgetron/gadgetron/blob/252429638715c350a82b3eb6ea4de93378334e71/toolboxes/nfft/cpu/hoNFFT.cpp#L416))

**Comment by dchansen** [comment]
No, that wouldn't make a difference I think. 
What might work is making all the non-virtual functions in NFFT.h (and their implementations in NFFT.hpp) inline. That should force the compiler to include the symbols everywhere, though it's still puzzling why it's needed at all.

**Comment by rijobro** [comment]
As far as I can see, the only methods in `NFFT.h` that aren't already `inline` or `virtual` are the constructors. Changing them to `inline` didn't solve the problem.

However, changing the following four methods from `virtual` to `inline` did solve it:
```
        inline void compute_NFFT_C2NC(ARRAY <complext<REAL>>&in, ARRAY <complext<REAL>>& out);

        inline void compute_NFFT_NC2C(const ARRAY <complext<REAL>>& in, ARRAY <complext<REAL>>& out);

        inline void compute_NFFTH_NC2C(const ARRAY <complext<REAL>>& in, ARRAY <complext<REAL>>& out);

        inline void compute_NFFTH_C2NC(ARRAY <complext<REAL>>& in, ARRAY <complext<REAL>>& out);
```

Is this acceptable?

**Comment by KrisThielemans** [comment]
it is correct C++, yes. All `inline` functions should be declared that way, it's just that most compilers don't bother. It should only be necessary in the class definition.

Please generate a PR for @dchansen to check. thanks!

**Comment by rijobro** [comment]
in fact, just remove the `virtual` from the `.h` files solves this (adding `inline` doesn't seem necessary).

**Comment by dchansen** [comment]
Still odd that the behaviour was different on OSX, but the methods certainly did not need to be virtual, so I am happy with this solution.
