### ISSUE TITLE
linking problems with packaged boost 1.68

### ISSUE THREAD

**Issue by KrisThielemans** [gadgetron/gadgetron#717]
A heads-up: due to ABI differences between boost libraries compiled with different C++ standards, you will get linking problems for Gadgetron when using a binary version of boost compiled with an older C++ version. More info at https://github.com/CCPPETMR/CCPPETMR_VM/issues/113 (and a ton of other places on the internet).

**Comment by dchansen** [comment]
That sounds reasonable. Would you make the pull request?

**Comment by rijobro** [comment]
ok, I think this can be closed now.
