### ISSUE TITLE
gadgetron server time-out issues on OSX

### ISSUE THREAD

**Issue by KrisThielemans** [gadgetron/gadgetron#719]
We are having run-time errors on OSX with Gadgetron v3.17.0 and ISMRMRD v1.4.0. Some more info on
https://github.com/CCPPETMR/SIRF/issues/279

Everything works fine with e7eb430673eb3272e8a821b51750c0a2a96dafed and https://github.com/ISMRMRD/ISMRMRD/commit/42d93137cc16c270c8ba065edd2496483161bd21.

Any advice on how we'd run ISMRMRD and Gadgetron test-suites that might help you pin-point the problem?

**Comment by dchansen** [comment]
For starters, I would check that the unit test and integration test in Gadgetron are passing on your OSX setup. If any of the integration test fail, please post the Gadgetron log file. That should give us something to work with.

**Comment by KrisThielemans** [comment]
can you point us to instructions please? (sorry)

**Comment by KrisThielemans** [comment]
found this
https://github.com/gadgetron/gadgetron/wiki/Integration-test-in-Gadgetron

but unit-tests?

**Comment by KrisThielemans** [comment]
I found this
```bash
cd /whereever/build
cd test
ctest -VV
```
(note that `ctest` doesn't work from the `build` directory, which is suprising).

we'll try this. Anything else?

**Comment by dchansen** [comment]
That should be it. Will let us know if Gadgetron is working as intended, or if this is a problem in SIRF/Gadgetron

**Comment by rijobro** [comment]
Hi @dchansen, I'm working through the ctest on Mac, and it's tripping up here:

```
1: [----------] Global test environment tear-down
1: [==========] 246 tests from 42 test cases ran. (12841 ms total)
1: [  PASSED  ] 245 tests.
1: [  FAILED  ] 1 test, listed below:
1: [  FAILED  ] hoNDArray_blas_Real/0.asumTest, where TypeParam = float
```

Initially, we thought that this wouldn't be the same problem as ours in SIRF, since we don't use BLAS. However, I commented out `hoNDArray_blas_test.cpp ` from `test/CMakeLists.txt` (to test everything except BLAS), and the ctest passed. 

Any thoughts on how we can fix this one?

**Comment by rijobro** [comment]
Thanks for the help. Running

```
./test_all --gtest_filter=hoNDArray_blas_Real/0.asumTest
```
gave the following output:
```
Note: Google Test filter = hoNDArray_blas_Real/0.asumTest
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from hoNDArray_blas_Real/0, where TypeParam = float
[ RUN      ] hoNDArray_blas_Real/0.asumTest
/Users/rich/Documents/Code/Gadgetron/Source/test/hoNDArray_blas_test.cpp:50: Failure
Expected equality of these values:
  this->Array.get_number_of_elements()
    Which is: 792281
  real(asum(&this->Array))
    Which is: 0
/Users/rich/Documents/Code/Gadgetron/Source/test/hoNDArray_blas_test.cpp:52: Failure
Expected equality of these values:
  this->Array.get_number_of_elements()*3
    Which is: 2376843
  real(asum(&this->Array))
    Which is: -0
[  FAILED  ] hoNDArray_blas_Real/0.asumTest, where TypeParam = float (4 ms)
[----------] 1 test from hoNDArray_blas_Real/0 (4 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (4 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] hoNDArray_blas_Real/0.asumTest, where TypeParam = float
```

Looks like the number of elements is 0, and therefore the sum is 0.

I don't know if this is of any relevance, but in CMake, all BLAS libraries (e.g., `BLAS_acml_LIBRARY`) are set to `NOTFOUND`. The exception is `BLAS_Accelerate_LIBRARY`, which is set to:
```
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Accelerate.framework
```
Lastly, cblas is set to: `/usr/lib/libcblas.dylib`.

**Comment by dchansen** [comment]
Well, this is a pretty big bug. I expected there to maybe be a minute difference, but asum returning 0 is just plain wrong. 
We're just calling the sasum function in cblas internally, so this is a bug in the Accelerate library on OSX. I would recommend you install OpenBLAS and use that instead (it should be on MacPorts).

I don't know if this is the cause of your original problem, but a significant number of reconstructions will fail in new and interesting ways if BLAS functions are randomly just returning 0.

**Comment by rijobro** [comment]
I'm struggling with MacPorts, so I installed OpenBLAS with brew (`brew install openblas`). 

However, Gadgetron requires 14 BLAS libraries and only 1 is installed with brew (`libopenblasp-r0.3.5.dylib`). Any idea what to do? Sorry if these are basic questions!

**Comment by dchansen** [comment]
We only require a single library with a working BLAS interface, CMake just looks for all 14 and decides which one to use.
 OpenBlas, MKL, ATLAS, etc would all be sufficient on their own. Accelerate should have worked just fine as well, but obviously didn't.

**Comment by rijobro** [comment]
If the bug is in Apple's Accelerate library, is it possible to change `BLAS_Accelerate_LIBRARY`?

**Comment by dchansen** [comment]
Not really, but using OpenBLAS instead should work.

**Comment by rijobro** [comment]
Hi, I didn't realise that newer versions of Gadgetron gave the option to choose the BLAS library and include dirs. This is great, and possibly solves the problem (reconstructions make sense now). However, linking of `test_all` with the current master fails with:
```
Undefined symbols for architecture x86_64:

  "Gadgetron::NFFT_plan<Gadgetron::hoNDArray, float, 2u>::compute_NFFT_C2NC(Gadgetron::hoNDArray<Gadgetron::complext<float> >&, Gadgetron::hoNDArray<Gadgetron::complext<float> >&)", referenced from:

      vtable for Gadgetron::hoNFFT_plan<float, 2u> in hoNFFT_test.cpp.o

  "Gadgetron::NFFT_plan<Gadgetron::hoNDArray, float, 2u>::compute_NFFT_NC2C(Gadgetron::hoNDArray<Gadgetron::complext<float> > const&, Gadgetron::hoNDArray<Gadgetron::complext<float> >&)", referenced from:

      vtable for Gadgetron::hoNFFT_plan<float, 2u> in hoNFFT_test.cpp.o

  "Gadgetron::NFFT_plan<Gadgetron::hoNDArray, float, 2u>::compute_NFFTH_C2NC(Gadgetron::hoNDArray<Gadgetron::complext<float> >&, Gadgetron::hoNDArray<Gadgetron::complext<float> >&)", referenced from:

      vtable for Gadgetron::hoNFFT_plan<float, 2u> in hoNFFT_test.cpp.o

  "Gadgetron::NFFT_plan<Gadgetron::hoNDArray, float, 2u>::compute_NFFTH_NC2C(Gadgetron::hoNDArray<Gadgetron::complext<float> > const&, Gadgetron::hoNDArray<Gadgetron::complext<float> >&)", referenced from:

      vtable for Gadgetron::hoNFFT_plan<float, 2u> in hoNFFT_test.cpp.o
```

Any idea what's going on? Everything compiles fine if I remove all `GTEST` variables (and therefore don't compile the testing unit).

**Comment by rijobro** [comment]
The error seems to be coming from here:
https://github.com/gadgetron/gadgetron/blob/e03b8a254eb25ff158175ac453500aa8b3c6199c/test/hoNFFT_test.cpp#L104

I assume it was causing you some troubles, too, given the revert/revert. Any ideas?

**Comment by rijobro** [comment]
ok, I think this can be closed now.

**Comment by KrisThielemans** [comment]
All our tests are working now. Thanks @rijobro and @dchansen
