### ISSUE TITLE
clashes with DT_NONE enum and define

### ISSUE THREAD

**Issue by KrisThielemans** [gadgetron/gadgetron#727]
@johannesmayer had compilation problems when including `nifti1.h` as it #defines `DT_NONE` etc, while Gadgetron uses the same name as an enum. More info is at https://github.com/CCPPETMR/SIRF/issues/282. We think it would be better to rename the Gadgetron `enum`s, but not sure if that can be done.

**Comment by dchansen** [comment]
I have to disagree with you that this is not a SIRF issue, as SIRF is the library in the business of being compatible with both NIFTI and Gadgetron. 

I would argue that the NIFTI define should have been `NIFTI_DT_NONE`, but that doesn't really solve anyone's problem.

The best solution would be to simply not include `nifti1.h` in any header file in SIRF, but only use it in source files. That way your code isn't tightly coupled to any particular NIFTI implementation, and `nifti1.h` doesn't leak any of its 119 occurrences of ` #define`.

**Comment by KrisThielemans** [comment]
we actually don't include `nifti1.h` in SIRF. @johannesmayer is one of our users who did it in his own code (we've created SIRF functionality that this isn't any longer necessary). So it isn't a SIRF problem.

I agree with `NIFT_DT_NONE` but that isn't going to happen. I just thought to let you know that these conflicts can happen because Gadgetron uses the same name.

Feel free to keep this closed and ignore of course.

**Comment by dchansen** [comment]
Ohh, I'm sorry. I misunderstood the problem. Thanks for the heads up.
