### ISSUE TITLE
cmake incompatability with cuda10.1 in docker build

### ISSUE THREAD

**Issue by ojosephs** [gadgetron/gadgetron#739]
Needed to add this to get cmake to succeed to build cuda 10.1 incremental docker image.

`#New cmake for gadgetron cmake
RUN apt-get -y purge cmake && wget -qO- "https://cmake.org/files/v3.12/cmake-3.12.4-Linux-x86_64.tar.gz" | \
tar --strip-components=1 -xz -C /usr/local`

Same error and temporary workaround reported here:
https://github.com/clab/dynet/issues/1457

**Comment by xueh2** [comment]
ok, great! do you mind to make a PR?
