### ISSUE TITLE
Bugs in ExtractGadget

### ISSUE THREAD

**Issue by evgueni-ovtchinnikov** [gadgetron/gadgetron#743]
The recent implementation of ExtractGadget has a couple of bugs.

1. The loop

            for (int imtype = IMTYPE::ISMRMRD_IMTYPE_MAGNITUDE; imtype <= IMTYPE::ISMRMRD_IMTYPE_PHASE; imtype++){
                if (bitmask[imtype-1]) image_types.push_back(IMTYPE(imtype));

apparently assumes that

    ISMRMRD::ISMRMRD_ImageTypes::ISMRMRD_IMTYPE_MAGNITUDE is 1
    ISMRMRD::ISMRMRD_ImageTypes::ISMRMRD_IMTYPE_REAL is 2
    ISMRMRD::ISMRMRD_ImageTypes::ISMRMRD_IMTYPE_IMAGE is 3
    ISMRMRD::ISMRMRD_ImageTypes::ISMRMRD_IMTYPE_PHASE is 4

whereas according to `ismrmrd.h` the actual values are

    enum ISMRMRD_ImageTypes {
        ISMRMRD_IMTYPE_MAGNITUDE = 1,
        ISMRMRD_IMTYPE_PHASE     = 2,
        ISMRMRD_IMTYPE_REAL      = 3,
        ISMRMRD_IMTYPE_IMAG      = 4,
        ISMRMRD_IMTYPE_COMPLEX   = 5
    };

Consequently, wrong data is extracted.

2. When running running the short chain below, `ExtractGadget::process_config` does not get called, resulting in empty vector `image_types` and no images extracted:
```
	<reader>
	 <slot>1022</slot>
	 <dll>gadgetron_mricore</dll>
	 <classname>MRIImageReader</classname>
	</reader>

	<writer>
	 <slot>1022</slot>
	 <dll>gadgetron_mricore</dll>
	 <classname>MRIImageWriter</classname>
	</writer>

	<gadget>
	 <name>Extract</name>
	 <dll>gadgetron_mricore</dll>
	 <classname>ExtractGadget</classname>
	 <property>
	  <name>extract_mask</name>
	  <value>1</value>
	 </property>
	</gadget>

	<gadget>
	 <name>ImageFinish</name>
	 <dll>gadgetron_mricore</dll>
	 <classname>ImageFinishGadget</classname>
	</gadget>
```

Longer chains do not seem to miss calling `process_config` - a multithreading issue?

(Note that the previous implementation did not have `process_config`.)

**Comment by dchansen** [comment]
First issue is fixed in Master. Not sure about the second one. I wasn't able to reproduce it.
