### ISSUE TITLE
GRAPPA Hangs

### ISSUE THREAD

**Issue by mckib2** [gadgetron/gadgetron#748]
After converting Siemens raw data to ISMRMRD format and sending to Gadgetron with the grappa_cpu.xml configuration file, the GrappaUnmixing gadget appears to hang.  I have this happen using both 3T and 7T data from VB line scanners.  Happy to share raw data if it helps resolve this issue.

Here is the output of the gadgetron.log file:

`06-18 03:37:31.037 INFO [GadgetStreamController.cpp:48] Connection from 172.17.0.1:56384
06-18 03:37:31.037 INFO [GadgetStreamController.cpp:202] Running configuration: /usr/local/share/gadgetron/config/grappa_cpu.xml
06-18 03:37:31.037 INFO [GadgetStreamController.cpp:226] Found 2 readers
06-18 03:37:31.037 INFO [GadgetStreamController.cpp:227] Found 1 writers
06-18 03:37:31.037 INFO [GadgetStreamController.cpp:228] Found 11 gadgets
06-18 03:37:31.037 INFO [GadgetStreamController.cpp:244] --Found reader declaration
06-18 03:37:31.037 INFO [GadgetStreamController.cpp:245]   Reader dll: gadgetron_mricore
06-18 03:37:31.037 INFO [GadgetStreamController.cpp:246]   Reader class: GadgetIsmrmrdAcquisitionMessageReader
06-18 03:37:31.037 INFO [GadgetStreamController.cpp:247]   Reader slot: 1008
06-18 03:37:31.141 INFO [GadgetStreamController.cpp:244] --Found reader declaration
06-18 03:37:31.141 INFO [GadgetStreamController.cpp:245]   Reader dll: gadgetron_mricore
06-18 03:37:31.141 INFO [GadgetStreamController.cpp:246]   Reader class: GadgetIsmrmrdWaveformMessageReader
06-18 03:37:31.141 INFO [GadgetStreamController.cpp:247]   Reader slot: 1026
06-18 03:37:31.141 INFO [GadgetStreamController.cpp:277] --Found writer declaration
06-18 03:37:31.141 INFO [GadgetStreamController.cpp:278]   Writer dll: gadgetron_mricore
06-18 03:37:31.141 INFO [GadgetStreamController.cpp:279]   Writer class: MRIImageWriter
06-18 03:37:31.141 INFO [GadgetStreamController.cpp:280]   Writer slot: 1022
06-18 03:37:31.141 DEBUG [GadgetStreamController.cpp:296] Processing 11 gadgets in reverse order
06-18 03:37:31.141 INFO [GadgetStreamController.cpp:310] --Found gadget declaration
06-18 03:37:31.141 INFO [GadgetStreamController.cpp:311]   Gadget Name: ImageFinish
06-18 03:37:31.141 INFO [GadgetStreamController.cpp:312]   Gadget dll: gadgetron_mricore
06-18 03:37:31.141 INFO [GadgetStreamController.cpp:313]   Gadget class: ImageFinishGadget
06-18 03:37:31.142 INFO [GadgetStreamController.cpp:328]   Gadget parameters: 0
06-18 03:37:31.142 INFO [GadgetStreamController.cpp:310] --Found gadget declaration
06-18 03:37:31.142 INFO [GadgetStreamController.cpp:311]   Gadget Name: FloatToShort
06-18 03:37:31.142 INFO [GadgetStreamController.cpp:312]   Gadget dll: gadgetron_mricore
06-18 03:37:31.142 INFO [GadgetStreamController.cpp:313]   Gadget class: FloatToUShortGadget
06-18 03:37:31.142 INFO [GadgetStreamController.cpp:328]   Gadget parameters: 0
06-18 03:37:31.142 INFO [GadgetStreamController.cpp:310] --Found gadget declaration
06-18 03:37:31.142 INFO [GadgetStreamController.cpp:311]   Gadget Name: AutoScale
06-18 03:37:31.142 INFO [GadgetStreamController.cpp:312]   Gadget dll: gadgetron_mricore
06-18 03:37:31.142 INFO [GadgetStreamController.cpp:313]   Gadget class: AutoScaleGadget
06-18 03:37:31.142 INFO [GadgetStreamController.cpp:328]   Gadget parameters: 0
06-18 03:37:31.143 INFO [GadgetStreamController.cpp:310] --Found gadget declaration
06-18 03:37:31.143 INFO [GadgetStreamController.cpp:311]   Gadget Name: Extract
06-18 03:37:31.143 INFO [GadgetStreamController.cpp:312]   Gadget dll: gadgetron_mricore
06-18 03:37:31.143 INFO [GadgetStreamController.cpp:313]   Gadget class: ExtractGadget
06-18 03:37:31.143 INFO [GadgetStreamController.cpp:328]   Gadget parameters: 0
06-18 03:37:31.143 INFO [GadgetStreamController.cpp:310] --Found gadget declaration
06-18 03:37:31.143 INFO [GadgetStreamController.cpp:311]   Gadget Name: GrappaUnmixing
06-18 03:37:31.143 INFO [GadgetStreamController.cpp:312]   Gadget dll: gadgetron_grappa
06-18 03:37:31.143 INFO [GadgetStreamController.cpp:313]   Gadget class: GrappaUnmixingGadget
06-18 03:37:31.144 INFO [GadgetStreamController.cpp:328]   Gadget parameters: 0
06-18 03:37:31.144 INFO [GadgetStreamController.cpp:310] --Found gadget declaration
06-18 03:37:31.144 INFO [GadgetStreamController.cpp:311]   Gadget Name: Grappa
06-18 03:37:31.144 INFO [GadgetStreamController.cpp:312]   Gadget dll: gadgetron_grappa
06-18 03:37:31.144 INFO [GadgetStreamController.cpp:313]   Gadget class: GrappaGadget
06-18 03:37:31.144 INFO [GadgetStreamController.cpp:328]   Gadget parameters: 2
06-18 03:37:31.144 INFO [GadgetStreamController.cpp:335] Setting parameter target_coils = 8
06-18 03:37:31.144 INFO [GadgetStreamController.cpp:335] Setting parameter use_gpu = false
06-18 03:37:31.144 INFO [GadgetStreamController.cpp:310] --Found gadget declaration
06-18 03:37:31.144 INFO [GadgetStreamController.cpp:311]   Gadget Name: RemoveROOversampling
06-18 03:37:31.144 INFO [GadgetStreamController.cpp:312]   Gadget dll: gadgetron_mricore
06-18 03:37:31.144 INFO [GadgetStreamController.cpp:313]   Gadget class: RemoveROOversamplingGadget
06-18 03:37:31.145 INFO [GadgetStreamController.cpp:328]   Gadget parameters: 0
06-18 03:37:31.145 INFO [GadgetStreamController.cpp:310] --Found gadget declaration
06-18 03:37:31.145 INFO [GadgetStreamController.cpp:311]   Gadget Name: AsymmetricEcho
06-18 03:37:31.145 INFO [GadgetStreamController.cpp:312]   Gadget dll: gadgetron_mricore
06-18 03:37:31.145 INFO [GadgetStreamController.cpp:313]   Gadget class: AsymmetricEchoAdjustROGadget
06-18 03:37:31.145 INFO [GadgetStreamController.cpp:328]   Gadget parameters: 0
06-18 03:37:31.145 INFO [GadgetStreamController.cpp:310] --Found gadget declaration
06-18 03:37:31.145 INFO [GadgetStreamController.cpp:311]   Gadget Name: CoilReduction
06-18 03:37:31.145 INFO [GadgetStreamController.cpp:312]   Gadget dll: gadgetron_mricore
06-18 03:37:31.145 INFO [GadgetStreamController.cpp:313]   Gadget class: CoilReductionGadget
06-18 03:37:31.145 INFO [GadgetStreamController.cpp:328]   Gadget parameters: 1
06-18 03:37:31.145 INFO [GadgetStreamController.cpp:335] Setting parameter coils_out = 16
06-18 03:37:31.145 INFO [GadgetStreamController.cpp:310] --Found gadget declaration
06-18 03:37:31.145 INFO [GadgetStreamController.cpp:311]   Gadget Name: PCA
06-18 03:37:31.145 INFO [GadgetStreamController.cpp:312]   Gadget dll: gadgetron_mricore
06-18 03:37:31.145 INFO [GadgetStreamController.cpp:313]   Gadget class: PCACoilGadget
06-18 03:37:31.145 INFO [GadgetStreamController.cpp:328]   Gadget parameters: 0
06-18 03:37:31.145 INFO [GadgetStreamController.cpp:310] --Found gadget declaration
06-18 03:37:31.145 INFO [GadgetStreamController.cpp:311]   Gadget Name: NoiseAdjust
06-18 03:37:31.145 INFO [GadgetStreamController.cpp:312]   Gadget dll: gadgetron_mricore
06-18 03:37:31.145 INFO [GadgetStreamController.cpp:313]   Gadget class: NoiseAdjustGadget
06-18 03:37:31.145 INFO [GadgetStreamController.cpp:328]   Gadget parameters: 0
06-18 03:37:31.145 INFO [GadgetStreamController.cpp:356] Gadget Stream configured
06-18 03:37:31.146 DEBUG [NoiseAdjustGadget.cpp:58] Folder to store noise dependencies is /tmp/gadgetron/
06-18 03:37:31.146 DEBUG [NoiseAdjustGadget.cpp:63] NoiseAdjustGadget::perform_noise_adjust_ is 1
06-18 03:37:31.146 DEBUG [NoiseAdjustGadget.cpp:66] NoiseAdjustGadget::pass_nonconformant_data_ is 0
06-18 03:37:31.146 DEBUG [NoiseAdjustGadget.cpp:75] receiver_noise_bandwidth_ is 0.793000
06-18 03:37:31.146 DEBUG [NoiseAdjustGadget.cpp:84] Measurement ID is 35002_4837481_4837486_93
06-18 03:37:31.146 DEBUG [PCACoilGadget.cpp:65] Number of uncombined channels (present_uncombined_channels) set to 0
06-18 03:37:31.146 DEBUG [CoilReductionGadget.cpp:66] Coil reduction from 8 to 8
06-18 03:37:31.146 DEBUG [NoiseAdjustGadget.cpp:361] Noise dwell time: 10.016026
06-18 03:37:31.146 DEBUG [NoiseAdjustGadget.cpp:362] receiver_noise_bandwidth: 0.793000
06-18 03:37:31.147 DEBUG [NoiseAdjustGadget.cpp:367] Calculating noise decorrelation
06-18 03:37:31.147 DEBUG [AsymmetricEchoAdjustROGadget.cpp:23] max RO for encoding space  0 : 768
06-18 03:37:31.147 DEBUG [NoiseAdjustGadget.cpp:549] Noise dwell time: 10.016026
06-18 03:37:31.147 DEBUG [NoiseAdjustGadget.cpp:550] Acquisition dwell time: 2.500000
06-18 03:37:31.147 DEBUG [NoiseAdjustGadget.cpp:551] receiver_noise_bandwidth: 0.793000
06-18 03:37:31.147 DEBUG [NoiseAdjustGadget.cpp:552] noise_bw_scale_factor: 0.629179
06-18 03:37:31.147 DEBUG [RemoveROOversamplingGadget.cpp:43] RemoveROOversamplingGadget:omp_set_num_threads(1) ... 
06-18 03:37:31.147 DEBUG [GrappaGadget.cpp:71] Dimensions 768, 252, 128, 8, 1
06-18 03:37:31.172 DEBUG [GrappaGadget.cpp:114] Running GRAPPA recon with 8 source channels and 8 target channels
06-18 03:37:31.172 DEBUG [GrappaGadget.cpp:119] use_gpu_ is 0
06-18 03:37:44.689 DEBUG [GrappaWeights.cpp:50] Releasing Mutex to Wait for result
06-18 03:39:00.319 DEBUG [Gadget.h:174] Gadget (NoiseAdjust) Close Called with flags = 1
06-18 03:39:00.319 DEBUG [Gadget.h:184] Gadget (NoiseAdjust) waiting for thread to finish
06-18 03:39:00.319 DEBUG [Gadget.h:174] Gadget (NoiseAdjust) Close Called with flags = 0
06-18 03:39:00.319 DEBUG [NoiseAdjustGadget.cpp:333] write out the noise dependency file : /tmp/gadgetron//GadgetronNoiseCovarianceMatrix_35002_4837481_4837486_93
06-18 03:39:00.319 DEBUG [Gadget.h:186] Gadget (NoiseAdjust) thread finished
06-18 03:39:00.319 DEBUG [Gadget.h:123] Shutting down Gadget (NoiseAdjust)
06-18 03:39:00.320 DEBUG [Gadget.h:174] Gadget (PCA) Close Called with flags = 1
06-18 03:39:00.320 DEBUG [Gadget.h:184] Gadget (PCA) waiting for thread to finish
06-18 03:39:00.320 DEBUG [Gadget.h:174] Gadget (PCA) Close Called with flags = 0
06-18 03:39:00.320 DEBUG [Gadget.h:186] Gadget (PCA) thread finished
06-18 03:39:00.320 DEBUG [Gadget.h:123] Shutting down Gadget (PCA)
06-18 03:39:00.320 DEBUG [Gadget.h:174] Gadget (CoilReduction) Close Called with flags = 1
06-18 03:39:00.320 DEBUG [Gadget.h:184] Gadget (CoilReduction) waiting for thread to finish
06-18 03:39:00.320 DEBUG [Gadget.h:174] Gadget (CoilReduction) Close Called with flags = 0
06-18 03:39:00.320 DEBUG [Gadget.h:186] Gadget (CoilReduction) thread finished
06-18 03:39:00.320 DEBUG [Gadget.h:123] Shutting down Gadget (CoilReduction)
06-18 03:39:00.320 DEBUG [Gadget.h:174] Gadget (AsymmetricEcho) Close Called with flags = 1
06-18 03:39:00.320 DEBUG [Gadget.h:184] Gadget (AsymmetricEcho) waiting for thread to finish
06-18 03:39:00.320 DEBUG [Gadget.h:174] Gadget (AsymmetricEcho) Close Called with flags = 0
06-18 03:39:00.320 DEBUG [Gadget.h:186] Gadget (AsymmetricEcho) thread finished
06-18 03:39:00.320 DEBUG [Gadget.h:123] Shutting down Gadget (AsymmetricEcho)
06-18 03:39:00.320 DEBUG [Gadget.h:174] Gadget (RemoveROOversampling) Close Called with flags = 1
06-18 03:39:00.320 DEBUG [Gadget.h:184] Gadget (RemoveROOversampling) waiting for thread to finish
06-18 03:39:00.323 DEBUG [Gadget.h:174] Gadget (RemoveROOversampling) Close Called with flags = 0
06-18 03:39:00.323 DEBUG [Gadget.h:186] Gadget (RemoveROOversampling) thread finished
06-18 03:39:00.323 DEBUG [Gadget.h:123] Shutting down Gadget (RemoveROOversampling)
06-18 03:39:00.323 DEBUG [Gadget.h:174] Gadget (Grappa) Close Called with flags = 1
06-18 03:39:00.323 DEBUG [Gadget.h:184] Gadget (Grappa) waiting for thread to finish
06-18 03:39:00.754 DEBUG [Gadget.h:174] Gadget (Grappa) Close Called with flags = 0
06-18 03:39:00.754 DEBUG [GrappaGadget.cpp:37] Shutting down GRAPPA Gadget
06-18 03:39:00.755 DEBUG [Gadget.h:186] Gadget (Grappa) thread finished
06-18 03:39:00.755 DEBUG [GrappaGadget.cpp:37] Shutting down GRAPPA Gadget
06-18 03:39:00.755 DEBUG [GrappaWeightsCalculator.cpp:41] Hanging up in weights calculator
06-18 03:39:00.834 DEBUG [Gadget.h:123] Shutting down Gadget (Grappa)
06-18 03:39:00.834 DEBUG [Gadget.h:174] Gadget (GrappaUnmixing) Close Called with flags = 1
06-18 03:39:00.834 DEBUG [Gadget.h:184] Gadget (GrappaUnmixing) waiting for thread to finish
`

**Comment by mckib2** [comment]
Update: the reconstructions are successful when I use the Generic_Cartesian_Grappa.xml configuration file which uses a different GRAPPA gadget.  I have a feeling that the standard gadget should be working, but this is a suitable workaround for us right now.

**Comment by kristofferknudsen** [comment]
The Gadgets used by the old grappa chains (grappa_cpu.xml, grappa_gpu.xml) have been extensively reworked for Gadgetron 4.0. They call the same toolbox functions, but the data-flow and threading layer has been entirely rewritten. 
I am glad the generic chain is a suitable workaround. Should the problem persist, please don't hesitate to let us know.
