### ISSUE TITLE
[feature request] extend PythonGadget with an end lifecycle

### ISSUE THREAD

**Issue by congzhangzh** [gadgetron/gadgetron#750]
Add an explict overrideable end lifecycle for Gadget to support multiple  thread like application, like UI application or Gadget self control services.

Gadgetron Gadget will end after receive the the stream close signal and all data in queue be processed, this function is provide by ACE Task framework and the Gadget has no explicit point to do something before task end.

Why this lifecycle point is must needed, for Gadget self control multiple thread application, property tear down the python spawned thread is must needed, the spawned thread's lifecycle must in the period of main python thread, or the application will crashed.

The ACE thread manager will try to close these spawned threads, but the embedded python already in an unusable status, if the thread try do anything python related, the application will crashed.

The only way to proper handle the problem is follow the principle who create who dispose which need give a change for python Gadget to do self clean, that's why the explict end lifecycle is needed!

**Comment by dchansen** [comment]
This is now possible with Gadgetron 4.1.
