### ISSUE TITLE
How should I change the header of ISMRMRD for colored MRI?

### ISSUE THREAD

**Issue by so2liu** [gadgetron/gadgetron#752]
Hello everyone,

I am trying to write a Gadget, which can add colors to the original grayscaled image. 

That means I want to change a grayscaled image into an RGB image. And then paint some colors on it. 

My basic idea is to extend the 2d matrix (256, 256, 1, 1) data to 3d matrix (256, 256, 3) data as RGB and add some colors.
Therefore, I think I should change a suitable ISMRMRD header, in order to fit the dimension. 

How should I change the head? I am using Python to write the Gadget. 

I have tried 
`head.channels = 3` or
`head.matrix_size[2] = 3` 
(or both), but it doesn't work. 

Could anyone help me?

Thank you so much~

Yang Liu

**Comment by dchansen** [comment]
Hi @so2liu,

You might get better answers on the [mailing list](https://groups.google.com/forum/#!forum/gadgetron). The ISMRMRD header should have channels=3, and then the image itself should have the dimensions changed via numpy.
