### ISSUE TITLE
removing dependency on boost::thread

### ISSUE THREAD

**Issue by KrisThielemans** [gadgetron/gadgetron#777]
I think it'd be a good idea to replace `boost::thread` with `std::thread`. It's more future proof and reduces dependencies. Longer motivation below.

We have a SIRF PR https://github.com/CCPPETMR/SIRF/pull/430/files that seems to succesfully do this. 99% of the relevant changes would directly apply to Gadgetron/ISMRMRD as it's essentially your code that we copied for those bits. 2 questions:

- I'll confess that my threading knowledge is limited. It compiles and seems to run ok but maybe someone would want to check?
- would you be interested in a relevant PR porting this to you?

Longer motivation:

We're having regular problems with SIRF with boost::thread linking conflicts (and other boost libraries), see e.g. https://github.com/CCPPETMR/SIRF/issues/429 and https://github.com/CCPPETMR/SIRF/issues/241. The relevant code was mostly lifted from Gadgetron/ISMRMRD code for the gadgetron client. Some of this code mixes `boost::thread` and `std::thread` (probably not a good idea anyway). We therefore are trying to remove boost compiled libraries as much as possible.

Although we don't have this problem with Gadgetron at the moment, these things do come up sometimes, see #717 and #711. I thought you might be interested therefore.

**Comment by dchansen** [comment]
Removing Boost Thread from Gadgetron should not be a problem. Gadgetron 4.0 doesn't use Boost Thread at all, so the dependency is just an oversight on our part.

As for the issues with Matlab, we chose to go the other direction for Gadgetron 4.1, and move Matlab to a separate process. From a principle point of view, it was unacceptable that Matlab should  which libraries we could use.
The old interface also had some security concerns that were fixed.
