### ISSUE TITLE
no option to disable building of the documentation

### ISSUE THREAD

**Issue by KrisThielemans** [gadgetron/gadgetron#778]
Currently we cannot switch of the building of the documentation if doxygen is installed. As this then [requires sphynx](https://github.com/gadgetron/gadgetron/blob/89a3f6281aa57ccf0e3a436a6435b3aae8f921dd/doc/CMakeLists.txt#L4) (which needs a load of other stuff), it'd be nice to be able to switch this off with a CMake option `BUILD_DOCUMENTATION`, presumably defaulting to `ON`.

**Comment by dchansen** [comment]
Option added in https://github.com/gadgetron/gadgetron/commit/8ea7f911e87575f666e30bfa5ffe7269023b0480
