### ISSUE TITLE
Compiling "MatlabBucketReconGadget" fails

### ISSUE THREAD

**Issue by dabosch** [gadgetron/gadgetron#786]
Hello,

I'm getting error messages when compiling gadgetron with MATLAB support.
(Ubuntu 18.04, Matlab R2019b, gadgetron "version": git commit edc0ca2)

There seem to be two unrelated issues:
**a) Compilation error**
```
home/gadgetron/test/gadgetron/gadgets/matlab/MatlabBucketReconGadget.cpp:110:45: error: ‘get_gadgetron_home’ was not declared in this scope
         std::string gadgetron_matlab_path = get_gadgetron_home().string() + "/share/gadgetron/matlab";
                                             ^~~~~~~~~~~~~~~~~~
```
I don't know enough of the gadgetron ecosystem to fix it properly. I was, however, able to alleviate the problem by replacing the function call by a hard-coded path. I know that this is no proper fix, but at least it allows me to compile.
Old code: 
`std::string gadgetron_matlab_path = get_gadgetron_home().string() + "/share/gadgetron/matlab";`
New code:
`std::string gadgetron_matlab_path = "/usr/local/share/gadgetron/matlab";`

**B) Linking error**
Now that I can compile MatlabBucketReconGadget.cpp, I have trouble linking it:
```
[ 95%] Building CXX object gadgets/matlab/CMakeFiles/gadgetron_matlab.dir/MatlabBucketReconGadget.cpp.o
[ 95%] Linking CXX shared library libgadgetron_matlab.so
/usr/bin/ld: cannot find -lgadgetron_gadgetbase
collect2: error: ld returned 1 exit status
gadgets/matlab/CMakeFiles/gadgetron_matlab.dir/build.make:175: recipe for target 'gadgets/matlab/libgadgetron_matlab.so.4.0.0' failed
```

This I was able to solve by removing line 38 in gadgets/matlab/CMakeList.txt
(gadgetron_gadgetbase in target_link_libraries). There seems to be no libgadgetron_gadgetbase anywhere.

For now I was able to solve the problem and everything seems to work, I just wanted to let you know that there seems to be some problem.

**Comment by dchansen** [comment]
This is referring to the old Matlab interface, which is no longer supported.
