### ISSUE TITLE
AcquisitionFinishGadget needed

### ISSUE THREAD

**Issue by evgueni-ovtchinnikov** [gadgetron/gadgetron#788]
The latest Gadgetron version no longer has `AcquisitionFinishGadget`.

Would it be possible to restore it, as it is very much needed by CCPPETMR Synergistic Image Reconstruction Framework (SIRF) code?

**Comment by dchansen** [comment]
In Gadgetron 4.0 and newer, the finish gadgets litterally do nothing. 
Would simply removing your usages of the gagdets be feasible for you?

**Comment by hansenms** [comment]
@dchansen, I am not sure that is true. It did not transform the data, but it did return it to the controller for output, so it returned the acquisition to the client. It would be very easy to put it back in.

**Comment by dchansen** [comment]
The controller went away in 4.0 😉
 All messages that reach the end of the chain are sent back to the client
if the chain has an appropriate writer.
We kept the ImageFinishGadget, because it was so widely used, but it
litterally just passed on everything it receives and all the chains would
work the same without it.

tir. 24. dec. 2019 23.37 skrev Michael Hansen <notifications@github.com>:

**Comment by hansenms** [comment]
How do you return stuff from the middle of the chain? Say navigation data?

**Comment by dchansen** [comment]
Well, almost all Gadgets will pass on messages that have the wrong type for
that Gadget, so in most cases you would just send it on.

More generally though, you could just create a branching chain.



ons. 25. dec. 2019 17.09 skrev Michael Hansen <notifications@github.com>:

**Comment by hansenms** [comment]
> Well, almost all Gadgets will pass on messages that have the wrong type for
that Gadget, so in most cases you would just send it on.

That does not sound like a reliable mechanism for high priority return of data, e.g. for navigation purposes. 

Sounds like branching is the more appropriate way. I haven't really investigated the model for this here.

In any case, the argument for removing the `AcquisitionFinishGadget` is pretty clear. It makes sense. I would say that it should apply to `ImageFinishGadget` too. I understand that it is more pervasive, but dragging on the confusion of the role of that may not be worth the effort....as is evident from this issue ;)
