### ISSUE TITLE
Include statements using <filename.hxx> instead of "filename.hxx"

### ISSUE THREAD

**Issue by johannesmayer** [gadgetron/gadgetron#793]
When trying to include gadgetron code and use against the core cpu library there are compilation errors arising from the include statements at the end of files for example:

`toolboxes/core/cpu/ho2DArray.h`

The final line including the `.hxx` file :

`#include <ho2DArray.hxx>`
wants to be replaced by 
`#include "ho2DArray.hxx"`

Otherwise it does not build because it seems to starts looking in the wrong location.

This is already done in the file `toolboxes/core/cpu/hoNDArray.h` but not in many of the other files.

**Comment by dchansen** [comment]
Hi Johannes,

Thank you for reporting this issue. If you already have it fixed, would you mind submitting a pull request?

Best regards,
David
