### ISSUE TITLE
GPU dwt operation result is different with the cpu dwt operation。

### ISSUE THREAD

**Issue by xpjiang** [gadgetron/gadgetron#795]
Help!When I using gpu dwt operation on a image, the result is different with the cpu dwt operation.
result from gpu dwt operation:
![result from gpu dwt operation](https://user-images.githubusercontent.com/2570137/74406595-0f193980-4e6b-11ea-8424-78ec31c264b4.png)
result from cpu dwt operation:
![result from cpu dwt operation](https://user-images.githubusercontent.com/2570137/74406808-91a1f900-4e6b-11ea-9744-1bd87a91b0db.png)

**Comment by dchansen** [comment]
Hi!
Could you share the image you're trying to process, as well as what exact calls you're making to perform the wavelet transform?
We have a number of different wavelets in Gadgetron, both redundant and non-redundant, so it would really help to know the exact functions that are causing problems.

**Comment by xpjiang** [comment]
Thanks for your reply.
This is the image for process.
[brain.zip](https://github.com/gadgetron/gadgetron/files/4202465/brain.zip)
and the test code:
`int test_code()
{
	// Load sample data from disk
	boost::shared_ptr< hoNDArray<float> > host_data =
		read_nd_array<float>("brain.img");

	if (!host_data.get()) {
		cout << endl << "Input image not found. Quitting!\n" << endl;
		return 1;
	}

	if (host_data->get_number_of_dimensions() != 2) {
		cout << endl << "Input image is not two-dimensional. Quitting!\n" << endl;
		return 1;
	}

	// Upload host data to device
	cuNDArray<float> data(host_data.get());

	cuNDArray<float> result(data);
	cuDWTOperator<float, 2> dwt;
	dwt.set_levels(3);
	dwt.mult_M(&data, &result);

	auto host_result = result.to_host();

	write_nd_array<float>(host_result.get(), "Brain_dwt_operation.img");

	return 0;

}`

**Comment by hansenms** [comment]
Stale, closing.
