### ISSUE TITLE
DUSE_CUDA=false

### ISSUE THREAD

**Issue by marcsous** [gadgetron/gadgetron#801]
I'm trying to compile Gadgetron without Cuda using the script below.
```
https://github.com/gadgetron/gadgetron/wiki/Install-gadgetron-at-Ubuntu-16.04#compile-and-install-gadgetron-to-your-local-folder
```
I tried passing -DUSE_CUDA=false via the cmake call, which seems to be the right thing to do, but then nothing compiles and there's no obvious error messages. Almost certainly this is user error but I don't know how to move forward - any help appreciated - thanks.

**Comment by kristofferknudsen** [comment]
Ubuntu 16.04 is getting pretty long in the tooth, and compiling Gadgetron on 16.04 requires a lot of legwork not covered in that guide. You'll need to update GCC (6 or newer required) install boost and armadillo from source (to get them new enough). 

None of this is covered by the guide you are trying to use (which is also getting pretty old). 

If you are absolutely stuck on 16.04, I suggest you take a look at the 16.04 Docker images ([here](https://github.com/gadgetron/gadgetron/blob/master/docker/base/ubuntu_1604_basic/Dockerfile) and [here](https://github.com/gadgetron/gadgetron/blob/master/docker/incremental/ubuntu_1604_cuda100_cudnn7/Dockerfile)).

If you are not stuck on 16.04, I suggest you get yourself a more recent Ubuntu. Try [this guide](https://github.com/gadgetron/gadgetron/wiki/Linux-Installation-(Gadgetron-4)) for 18.04 (works on 20.04 as well).

**Comment by marcsous** [comment]
Hi Kristoffer,

Thanks for your reply and for that link - it's a lot of help. In fact, all I am trying to do is use gadgetron as a gateway to matlab. I had it working on 3.1x a few years ago but now it's all broken and I've been in dependency hell for days...

Very happy to see you have authored a new Foreign Language plugin - fantastic! I will try to get that installed. I have compiled 4.1.1 (master) and installed the Gadgetron Add On inside matlab. So what happens now?  ;)  I'm going to do some searching for how it works... 

Mark

**Comment by kristofferknudsen** [comment]
Hi Mark, 

Did you download the test data? 

Easiest way is probably to run the 'get_data.py' script provided in `/test/integration`. It'll fetch 10 GiB worth of test data for the integration tests to run on, including the file you are trying to convert. 

Once the data is downloaded you should be able to run the Matlab integration tests. I've written [this](https://github.com/gadgetron/gadgetron/wiki/Using-Matlab-with-Gadgetron) intro to the new Matlab interface, which should cover this in detail. 

Kristoffer
