### ISSUE TITLE
2D and 3D cufft inaccuracy when the dims are different.

### ISSUE THREAD

**Issue by xpjiang** [gadgetron/gadgetron#802]

**Comment by xpjiang** [comment]
In line 189:
std::vector<int> int_dims {int(input->get_size(0)),int(input->get_size(1))};
maybe should changed to:
 std::vector<int> int_dims {int(input->get_size(1)),int(input->get_size(0))};
the same as in line 223.

**Comment by dchansen** [comment]
Could you provide more details?
We obviously want the FFT to work for images where the first and second dimensions are different.

**Comment by xpjiang** [comment]
Introduction to cufftPlanMany() 's parameters:
`cufftResult 
    cufftPlanMany(cufftHandle *plan, int rank, int *n, int *inembed,
        int istride, int idist, int *onembed, int ostride,
        int odist, cufftType type, int batch);`
the input n is 
Array of size rank, describing the size of each dimension, n[0] being the size of the outermost and n[rank-1] innermost (contiguous) dimension of a transform.

from https://docs.nvidia.com/cuda/cufft/#function-cufftplanmany
also I can give a standalone app for test in Widows operating system using vs2015.

**Comment by dchansen** [comment]
Thank you very much for bringing this to our attention - it really is a great help.
I have fixed it on the current master branch. 
Could you confirm that this fixes the issue for you?

**Comment by xpjiang** [comment]
Thanks for your reply. It really will solve the problem.
