### ISSUE TITLE
Bucket_to_Buffer + external -> Matlab not working in some cases

### ISSUE THREAD

**Issue by aTrotier** [gadgetron/gadgetron#808]
Hi,

We are adapting our MP2RAGE reconstruction code to gadgetron 4.1. but i have an issue when using bucket_to_buffer and sending the data to matlab. **acquisition = next_acquisition()";** give me that error :
```>> gadgetron.external.listen(18000, @handle_connection_Bucket_example);
Starting external MATLAB module 'handle_connection_Bucket_example' in state: [PASSIVE]
Waiting for connection from client on port: 18000
handle_connection was called.
Unable to perform assignment because the left and right sides have a different number of elements.

Error in socket.Socket/read (line 38)
                bytes(current_index + 1:next_index) = read(self.sock, nbytes);

Error in gadgetron.external.readers.read_array>read_complex_array (line 20)
        gadgetron.external.readers.as_interleaved_complex(read(socket, 2 * prod(dims), type)), ...

Error in gadgetron.external.readers.read_array (line 4)
            arr = read_complex_array(socket, 'single');

Error in gadgetron.external.readers.read_recon_data>read_recon_buffer (line 16)
    buffer.data = gadgetron.external.readers.read_array(socket, 'complex64');

Error in gadgetron.external.readers.read_recon_data>read_recon_bit (line 11)
    recon_bit.buffer = read_recon_buffer(socket);

Error in gadgetron.external.readers.read_recon_data>@(~)read_recon_bit(socket) (line 7)
    recon_bits = arrayfun(@(~) read_recon_bit(socket), 1:n_recon_bits);

Error in gadgetron.external.readers.read_recon_data>read_recon_bits (line 7)
    recon_bits = arrayfun(@(~) read_recon_bit(socket), 1:n_recon_bits);

Error in gadgetron.external.readers.read_recon_data (line 2)
    recon_data = gadgetron.types.ReconData(read_recon_bits(socket));

Error in gadgetron.external.Connection/read_next (line 79)
            item = reader(self.socket);

Error in gadgetron.external.Connection/next (line 35)
            [item, mid] = self.read_next();

Error in handle_connection_Bucket_example>@(varargin)connection.next(varargin{:}) (line 5)
next_acquisition = @connection.next;

Error in handle_connection_Bucket_example (line 22)
    acquisition = next_acquisition(); % Call input function to produce the next acquisition.

Error in gadgetron.external.listen (line 14)
    handler(connection, varargin{:});

```

I am able to reconstruct the data by removing the bucker_to_buffer and doing the bufferization under matlab.

It seems to be related to my datasets (I try 2 datasets acquired with different MP2RAGE sequences) 
What's in common between the 2 is that the datasets size is important. It is a compressed-sensing acquisition and the bottom of kspace are left empty for some lines (see the ky/kz mask) : 
<img width="288" alt="Capture d’écran 2020-03-17 à 17 44 54" src="https://user-images.githubusercontent.com/12255163/78266831-964b6b00-7506-11ea-9f2c-566c5be8446a.png">

[log_error.txt](https://github.com/gadgetron/gadgetron/files/4421913/log_error.txt)

The reconstruction works with the test datasets of gadgetron (gre_2D and gre_3D ) (see log)
[log_2D_working.txt](https://github.com/gadgetron/gadgetron/files/4421906/log_2D_working.txt)

You can find the config and matlab function used : 
[Archive.zip](https://github.com/gadgetron/gadgetron/files/4421932/Archive.zip)

And i have uploaded one of the dataset (approx 6go) : https://www.rmsb.u-bordeaux.fr/nextcloud/index.php/s/Ag4tzqDXjp4CMXd

Any idea ?
Thanks

**Comment by kristofferknudsen** [comment]
Thank you for getting back to us with this issue. 

I've had a look at the read function (socket.Socket/read), and it *looks* like there's a bug when reading large blocks of data. I *think* I've found the problem, and the solution should be reasonably simple. 

I can't - however - run the reconstruction at the moment. My work-from-home-pc is a little anaemic, and has trouble with the 23 GiB buffer. I'll do my best to get my hands on some hardware so I can verify the fix. I'll get it posted as soon as possible. 

Best regards, 
Kristoffer

**Comment by aTrotier** [comment]
Thank you :)

I can try your fix if you want on my server.

Regards,
Aurélien

**Comment by kristofferknudsen** [comment]
Hi Aurélien,

I've grabbed a more beefy PC, which unfortunately will not run the reconstruction either (I run out of memory - I consider the current consumption an issue). I do get a lot further though, and I do believe I've fixed the issue you are seeing. 

I need your help to verify it though - I've pushed some code to my fork of the [gadgetron-matlab](https://github.com/gadgetron/gadgetron-matlab/compare/master...kristofferknudsen:large-buffer-fix) repository. 

If it works for you, I'll make the pull request. Thank you for your help, and for getting this issue back to us.

Best regards, 
Kristoffer

**Comment by aTrotier** [comment]
Hi Kritoffer,
The new gadgetron_matlab is "working", I am able to reconstruct the data.

However i have done a little test about the speed : 
- With bucketToBuffer : memory required is 91go (115 without removing the baseline) and it took 213 sec to create the kspace dataset in matlab.
- Without BucketToBuffer and with accumulateTrigger : memory = 16go and 37 sec in order to buffer the data into a kspace dataset. I'm using this way to buffer in matlab : 
````
next_acquisition = @connection.next;

sRO = connection.header.encoding.reconSpace.matrixSize.x;
sPE = connection.header.encoding.reconSpace.matrixSize.y;
sSE = connection.header.encoding.reconSpace.matrixSize.z;

nContrast = connection.header.encoding.encodingLimits.contrast.maximum;
nSet = connection.header.encoding.encodingLimits.set.maximum;
maxDim = max(nContrast, nSet) + 1; % Sequence of pierre use nSet and my sequence use nContrast

acquisition = next_acquisition(); % Call input function to produce the next acquisition.
nCh = size(acquisition.data.data,2);

kdata=zeros(sRO,nCh,sPE*sSE,maxDim);

row = acquisition.data.header.kspace_encode_step_1 + 1;
col = acquisition.data.header.kspace_encode_step_2 + 1;

if nContrast > nSet
    TI_idx = acquisition.data.header.contrast + 1;
else
    TI_idx = acquisition.data.header.set + 1;
end

kdata(:,:,sub2ind([sPE,sSE,maxDim],row,col,TI_idx))=acquisition.data.data;
````
 Maybe we should open a new issue for that.

Anyway good job 👍 . We can close the issue.
Aurélien

**Comment by kristofferknudsen** [comment]
I've had a short look. 

First up is the memory use during transfer to Matlab. It appears Matlab needs several times the space of the incoming item. For very large items (for instance a 23.4 GiB buffer), this becomes significant. I consider this an issue - I'll probably open one tomorrow. I'm not sure what causes this, but I'll look into it. 

Regarding the speed; this is the apples-oranges. The bucket assembled by Gadgetron and sent to Matlab is 2.8 GiB. It's pretty dense, containing pure acquisition data. Matlab then allocates a large buffer (50 GiB 'cause you are using doubles), and writes the acquisition data in it. I assume this large buffer is mostly copies/zeros. 

When sending the ReconData assembled by BucketToBuffer, the 23.4 GiB array is assembled in Gadgetron. And the whole 23.4 GiB buffer, zeros and all, is sent to Gadgetron. I'd expect the transfer to take about ten times longer, but Matlab being able to operate on the data immediately afterwards. 

I believe it's not too far off the numbers you are seeing - they seem reasonable to me. 

I note that the `Bucket` data type exists exactly to dodge the cost of sending gigabytes of zeros to Matlab. It's not an ideal type - a more generic sparse matrix type would be nice I think, but I suggest you use buckets in your reconstruction if at all possible.

Best regards, 
Kristoffer

**Comment by aTrotier** [comment]
Hi, thanks for the answer.

For me the Bucket data type, that's what i use for now and it works well so i'll stick to that. We can close the issue :)

Just a last minor question : is there a gadget to convert the double to single complex value in order to reduce the size of the buffer.

**Comment by kristofferknudsen** [comment]
Gadgetron usually works in 'single' complex numbers, doubles are actually pretty rare in the C++ codebase. Matlab loves doubles, and will happily convert anything and everything to doubles if given the chance. 

You are seeing a double array in Matlab 'cause you allocate an array of doubles. Assigning into this array converts the single complex values from Gadgetron to double values, and adds another array of doubles for the imaginary parts. This line allocates the double buffer:
```matlab
kdata=zeros(sRO,nCh,sPE*sSE,maxDim);
```
If you want an array of 'single' complex numbers, something like this should do:
```matlab
kdata = complex(zeros(sRO, nCh, sPE*sSE, maxDim, 'single'));
``` 

I'll close this issue for now, and open up an issue on the memory usage. Thank you for getting this feedback to us, it really helps. 

Best regards, 
Kristoffer
