### ISSUE TITLE
libgadgetron_gadgetbase is not "versioned"

### ISSUE THREAD

**Issue by naegelejd** [gadgetron/gadgetron#81]
Unlike all other Gadgetron libraries, `libgagdgetron_gadgetbase` (in `apps/gadgetron/`) is not generated with version numbers in its name. Is this intentional or should the CMakeLists.txt file contain the following line?

    set_target_properties(gadgetron_gadgetbase PROPERTIES VERSION ${GADGETRON_VERSION_STRING} SOVERSION ${GADGETRON_SOVERSION})

**Comment by hansenms** [comment]
It should be versioned. It is a mistake. Please fix if you have time.
