### ISSUE TITLE
Integration test failing

### ISSUE THREAD

**Issue by TheZeldaBoss** [gadgetron/gadgetron#810]
Hello,

I've just started using gadgetron a few days ago, but I'm stuck with one of the tutorials from the wiki:

First, I'm really sorry if this is not the correct place to ask, but I haven't found anywhere else...

I've tried a few tutorials before (Hello World and Gadget creation), which worked fine, but now, I'm trying the integration tests, and I always get stuck with a "No such file or directory: 'siemens_to_ismrmrd': 'siemens_to_ismrmrd' error...

I am running Gadgetron on Ubuntu 18.04, with version 4.1 as I haven't been able to compile the master branch correctly...

Here is the full log of one of the tests I passed :

```./run_tests.py ./cases/simple_gre.cfg 

Test 1 of 1: ./cases/simple_gre.cfg

Running Gadgetron test ./cases/simple_gre.cfg with:
  -- ISMRMRD_HOME    : /usr/local
  -- GADGETRON_HOME  : /usr/local
  -- TEST CASE       : ./cases/simple_gre.cfg
Starting Gadgetron instance on port 9003
Converting Siemens data: data/simple_gre/meas_MiniGadgetron_GRE.dat -> test/in.h5
Traceback (most recent call last):
  File "run_gadgetron_test.py", line 498, in <module>
    sys.exit(main())
  File "run_gadgetron_test.py", line 491, in main
    result, return_code = action_chain(test=args.test)
  File "run_gadgetron_test.py", line 441, in <lambda>
    return lambda **state: action(chain_actions(actions), **state)
  File "run_gadgetron_test.py", line 191, in handle_subprocess_errors
    return cont(**state)
  File "run_gadgetron_test.py", line 441, in <lambda>
    return lambda **state: action(chain_actions(actions), **state)
  File "run_gadgetron_test.py", line 206, in clear_test_folder_action
    return cont(**state)
  File "run_gadgetron_test.py", line 441, in <lambda>
    return lambda **state: action(chain_actions(actions), **state)
  File "run_gadgetron_test.py", line 222, in start_gadgetron_action
    return cont(gadgetron=gadgetron, **state)
  File "run_gadgetron_test.py", line 441, in <lambda>
    return lambda **state: action(chain_actions(actions), **state)
  File "run_gadgetron_test.py", line 249, in action
    return cont(gadgetron=gadgetron, **state)
  File "run_gadgetron_test.py", line 441, in <lambda>
    return lambda **state: action(chain_actions(actions), **state)
  File "run_gadgetron_test.py", line 288, in convert_siemens_data_action
    flag=config['SIEMENS'].get('data_conversion_flag', None))
  File "run_gadgetron_test.py", line 61, in siemens_to_ismrmrd
    check=True)
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'siemens_to_ismrmrd': 'siemens_to_ismrmrd'
```
I'm running it from ~/Downloads/gadgetron/test/integration folder (I didn't move the gadgetron folder after downloading it) and everything is well installed and configurated.

Also, it seems that the command in the corresponding wiki page is not correct anymore, as there is no -G or -I commands in run_test.py.
Thank you very much for your answer...

**Comment by kristofferknudsen** [comment]
Hello, 

The integration tests rely heavily on data stored as Siemens data files (most of the test data comes straight out of Siemens scanners). To run the integration tests, the data needs to be converted to the ISMRMRD data format, using a conversion tool. 

The tool is called [siemens_to_ismrmrd](https://github.com/ismrmrd/siemens_to_ismrmrd), and the error message indicates that it's missing on your system. 

Quite a number of wiki pages are not updated for 4.x, and only cover Gadgetron 3.17. We're slowly working our way through them, updating as we go. 

The -I and -G options are used to set the 'GADGETRON_HOME' and 'ISMRMRD_HOME' environment variables, but Gadgetron 4 does a pretty good job of finding these by itself. They are still available as environment variables if you truly need to set them, but I suspect you don't. 

We should have an up-to-date page on installing 4.1, I believe you can find it [here](https://github.com/gadgetron/gadgetron/wiki/Linux-Installation-(Gadgetron-4)). It briefly touches on integration tests, and covers the installation of siemens_to_ismrmrd. 

Best regards, 
Kristoffer

**Comment by TheZeldaBoss** [comment]
Hello,
I have just found the instructions for it on this page a few minutes ago, but thanks for your answer. It would be great if you could add it on the integration wiki page, for people like me who don't take enough time to read the foot of a page when they have what it's supposed to do...
