### ISSUE TITLE
3.17 -> 4 : would it be possible that hoNDFFT<T>::instance()->fft doesn't work as before /at all

### ISSUE THREAD

**Issue by valeryozenne** [gadgetron/gadgetron#818]
Hi, 

I have to report a issue happening in Gadgetron4 and not in 3.17, it is currently confirmed by two users. For some reasons, the following line results in a crash.

hoNDFFT<float>::instance()->fft(&data,0); 

with hoNDArray< std::complex<float> >& data ,  all points in data are accessible within the Gadegtron and allocated and can be saved on the disk before reco. Gdb indicate that the function crash when doing the allocation.

To reproduce the bug: please compile the following branch:
https://github.com/valeryozenne/gadgetron-sms/tree/master_4.0

The data are accessible here: 
meas_MID00110_FID51718_cmrr_1_7iso_GP2_MB2_36s_50sur

the command line is :

gadgetron_ismrmrd_client 
-f meas_MID00030_FID49096_cmrr_12s_80p_MB0_GP2.h5
-c Generic_Cartesian_Slice_Grappa_EPI_v5.xml

I will try to reproduce the bug in the master of Gadgetron

**Comment by TheZeldaBoss** [comment]
I'm the second user mentionned by Valery, and I can add some more informations : 
According to GDB, it looks like the error comes directly from the hoNDFFT constructor, inside the instance() function. It's on line 18 in my local file, and it seems to be the same on the remote one.

The complete line which calls the instance() function  is : 
`hoNDFFT<float>::instance()->fft(&data,0);

And the line calling the constructor in hoNDFFT.cpp : 
`instance_ = new hoNDFFT<T>();`

**Comment by dchansen** [comment]
Hi,
I posted a fix for this last night. Could you check your code with the latest master?
