### ISSUE TITLE
Density compensation for arbitrary trajectories - useful?

### ISSUE THREAD

**Issue by jmontalt** [gadgetron/gadgetron#834]
Dear all,

I have implemented the algorithm described in [Zwart et al. (2011)](https://onlinelibrary.wiley.com/doi/full/10.1002/mrm.23041) for estimation of density compensation weights of arbitrary 2D/3D non-Cartesian trajectories, which is useful for my work. The implementation uses native Gadgetron arrays and is for both CPU and GPU. Would this be of interest to Gadgetron users/maintainers? If so I would be happy to document and submit a PR.

Javier

**Comment by dchansen** [comment]
That sounds very useful. The density compensation we have right now is specific to spiral or radial trajectories, which can be problematic. I think we would certainly be interested.
 
Some (perhaps naive) questions as I'm not familiar with the algorithm:
Does it handle the same (or very close) trajectory point appearing more than once?
What is the speed like?
How does it compare with trajectory specific methods?

None of these are showstoppers,as we have nothing right now, but it might help decide to what degree it should be the default.  

@ACampbellWashburn do you have any input? You're more up to date than I on this.

**Comment by jmontalt** [comment]
Thanks for the quick reply!
- According to the authors the algorithm should be robust in areas of high trajectory overlap. In my own experience, it works just fine on spiral-out trajectories with a densely sampled k-space centre.
- The algorithm is based on an iterative grid-degrid process, so the speed is mostly determined by the efficiency of the convolution. The current implementation is based on the Gadgetron's NUFFT. Here's some measurements to give you an idea (Intel Core i7 6700K, 32 GB RAM, NVIDIA GTX 1070):

> 2D, 384x384 matrix, 126k samples
> CPU: 150 ms precomputation + ~10 ms per iteration
> GPU: ~20 ms per iteration (no precomputation)
> 
> 3D, 192x192x64 matrix, 2.6M samples:
> CPU: 12 s precomputation + ~1 s per iteration
> GPU: 2.6M samples: ~1 s per iteration (no precomputation)

- I never needed more than 10 iterations and can often get away with 5. As it currently stands, it uses the sparse convolution matrix for the CPU implementation and atomics for the GPU implementation, which is why there's no precomputation time for the latter but the time per iteration is relatively long. I decided to use the atomics GPU implementation initially because the convolution is done on a very oversampled grid (factor = 2.1 as per the authors' recommendation), so the standard type GPU convolution would quickly cause memory issues in 3D.
- Unfortunately I can't advise on how it compares with trajectory specific methods, sorry. My work tends to involve irregular trajectories for which such methods are not generally suitable.

It's great to know this could be useful, I'll prepare it then. If I may ask a couple of questions:
- Where in the directory tree should I put it? I was thinking under `toolboxes/mri/sdc`. SDC stands for sampling density compensation.
- What should be the external interface? I was thinking one option would be to model it after the NUFFT:
```
auto plan = SDC<ARRAY, REAL, D>::make_plan(matrix_size, os_factor, num_iterations);
plan->compute(traj, dcw); // dcw is the output and possibly an input (an initial estimate)
```
This object oriented approach is useful internally but it might be unnecessary for the user who could potentially write something like this:
```
estimate_dcw<ARRAY, REAL, D>(traj, dcw, matrix_size, os_factor, num_iterations);
```
Thanks!

**Comment by ACampbellWashburn** [comment]
This will be very useful! It adds new functionality over the DCW that we already have. We have been using a similar iterative method for our offline non-Cartesian recons, and find that they work very robustly. 

I will leave the ultimate directory/implementation decision up to @dchansen, but I agree that modeling it after the NUFFT would work well from the user-perspective and support this idea.

**Comment by dchansen** [comment]
From what I understand, the plan wouldn't really be reusable, so a plan wouldn't be very useful for end users.
I think I would favour something along the line of
`dcw = estimate_cw<ARRAY,REAL,D>(traj,dcw,matrix_size,os_factor,num_iterations)`
with os_factor and num_iterations having sensible defaults.
`toolboxes/mri/sdc`  sounds like a reasonable place to put this.

**Comment by aTrotier** [comment]
Hi, 
Great initiative, for now most of non-cartesian reconstructions are done through matlab/python in order to compute the DCF is required.
I just wanted to add something : It is important also important to be able to send the results to python/matlab/bart_gadget because it is something we can use for advanced iterative reconstruction in 3D, it helps the reconstruction to converge (in bart).

**Comment by jmontalt** [comment]
Hi, thank you all for your feedback, I'll keep it in mind. Regarding the ability to send results to python/matlab/bart, I guess some reconstruction gadgets might need to be updated to look for the DCW, possibly using the member `density_` in the `IsmrmrdDataBuffered` structure or as an extra dimension in the trajectory?
