### ISSUE TITLE
can't convert ismrmrd into dicom with dicom.xml

### ISSUE THREAD

**Issue by valentine256** [gadgetron/gadgetron#838]
hi. i am a new user of gadgetron.
i studied as an official tutorial and succeeded in creating an image from siemens data (test data and my data).
however, no dicom image can be created with the same data. according to the logs i looked at, there seems to be no problem with the functionality on the gadgetron server.
but, the client does not receive the results. here i will attach the docker image i configured and the commands i ran and logs. please help.
Thank you.

- Docker
![0-1](https://user-images.githubusercontent.com/44939217/82662473-defee500-9c68-11ea-9a79-1c7b62d3ce9f.png)
![0](https://user-images.githubusercontent.com/44939217/82660997-25067980-9c66-11ea-89e9-3aae7ba100fb.png)

- Command

1. Convert siemens dat into ismrmrd(noise, data)
`siemens_to_ismrmrd -f meas_MID03485_FID51095_se.dat -z 1 -o noise.h5`
`siemens_to_ismrmrs -f meas_MID03485_FID51095_se.dat -z 2 -o data.h5`
![1-1](https://user-images.githubusercontent.com/44939217/82661015-3059a500-9c66-11ea-972d-a3428504e1cc.png)
![1-1_end](https://user-images.githubusercontent.com/44939217/82661023-33549580-9c66-11ea-824c-f6950688da2e.png)
![1-2](https://user-images.githubusercontent.com/44939217/82661026-38194980-9c66-11ea-945e-e7bcbaad3bd3.png)

2. Save dependency noise data into gadgetron server
`gadgetron_ismrmrd_client -f noise.h5 -c default_measurement_dependencies.xml`
![2](https://user-images.githubusercontent.com/44939217/82661042-3d769400-9c66-11ea-9cd7-95e7d74a5bce.png)

3. Make image from data and noise(successed)
`gadgetron_ismrmrd_client -f data.h5 -o data_default.h5 -c default.xml`
![3](https://user-images.githubusercontent.com/44939217/82661055-423b4800-9c66-11ea-8316-0008d2d8a71f.png)

4. Make image from data and noise with grappa(successed)
`gadgetron_ismrmrd_client -f data.h5 -o data_generic_cartesian_grappa_snr.h5 -c Generic_Cartesian_Grappa_SNR.xml`
![4](https://user-images.githubusercontent.com/44939217/82661062-46676580-9c66-11ea-899d-18efb4276b19.png)

5. Make dicom image from data and noise(failed) 
`gadgetron_ismrmrd_client -f data.h5 -o data_dicom.h5 -c dicom.xml`
![5](https://user-images.githubusercontent.com/44939217/82661092-52532780-9c66-11ea-8eb3-c175a544e504.png)

- Data(link)
https://drive.google.com/drive/folders/12kBg5mGKsNmeZRSkuS40YKN1co9EfATB?usp=sharing

**Comment by valentine256** [comment]
as a result of debugging, I found the code causing the error of boost inside GadgetronClientBlobMessageReader of gadgetron_ismrmrd_client. I was able to get a dicom by commenting this, but for a good result I need to learn more.
![2020-05-25-214943_3840x2131_scrot](https://user-images.githubusercontent.com/44939217/82814547-55eae680-9ed2-11ea-9b7e-5c410c82f69b.png)
![2020-05-25-215001_3840x2160_scrot](https://user-images.githubusercontent.com/44939217/82814552-58e5d700-9ed2-11ea-8031-9b5ec6f144de.png)

**Comment by praveenivp** [comment]
A great find !!! Even I had the same issue when compiling my own gadgetron. But somehow it works fine with the pre-compiled docker containers. The error can also be reproduced even with the testdata generated using ismrmrd_generate_cartesian_shepp_logan.

I think I further narrowed down the source of the problem. It is in the DicomImageWriter.cpp: line 65. It looks like when the ISMRMRD header information is not initialized, it doesn't write the length meta_data block length in the output stream. Writing a length of zero when there is no meta_data solves the issue for me. There must be more elegant way to fix this.

![dicom_export error](https://user-images.githubusercontent.com/36160564/82975586-355b8300-9fdd-11ea-8013-21d6ed511882.png)

**Comment by achataigner** [comment]
Is it solved by this commit  2ce9937daa814d84a15e0303c55430b3f9e314d6 ?

**Comment by dchansen** [comment]
Should be.
