### ISSUE TITLE
gadgetron_mri_noncartesian

### ISSUE THREAD

**Issue by ahsanjav** [gadgetron/gadgetron#847]
I get this error when I run Gadgetron compiled using cmake from command line however when I use vscode for compilation it seems to works just fine. Any ideas on how to resolve it ? 

06-04 22:58:41.690 DEBUG [Gadget.h:130] Shutting down Gadget ()
06-04 22:58:41.690 DEBUG [Gadget.h:130] Shutting down Gadget ()
06-04 22:58:41.691 ERROR [Core.cpp:18] [Connection Main Thread] ERROR: boost::dll::shared_library::load() failed (dlerror system message: gadgetron_mri_noncartesian: cannot open shared object file: No such file or directory): Bad file descriptor
06-04 22:58:41.691 INFO [Core.cpp:76] Connection state: [FINISHED]

**Comment by dchansen** [comment]
Fixed in the current master.
