### ISSUE TITLE
Use of GRAPPA in Python

### ISSUE THREAD

**Issue by zaccharieramzi** [gadgetron/gadgetron#865]
I am interested in using GRAPPA for MRI reconstruction, and I stumbled across [this PR](https://github.com/gadgetron/gadgetron/pull/730).

Do you know if it's possible to use it for MRI reconstruction in Python? I don't see how in the docs ([the linked page in the wiki is actually empty](https://github.com/gadgetron/gadgetron/wiki/Cartesian-2D-Parallel-MRI-(GRAPPA))) and I can't find the examples folder ([this one being all C++](https://github.com/gadgetron/gadgetron/tree/master/gadgets/examples)). If it is possible, do you have by any chance a code snippet or an example laying around?

I would also be interested in understanding whether there is a GPU implementation of GRAPPA, since I see [a GPU folder](https://github.com/gadgetron/gadgetron/tree/master/gadgets/grappa/gpu) in the GRAPPA folder.

**Comment by dchansen** [comment]
In short - it isn't currently possible. You could write your own wrapper (see [this unsupported repository](https://github.com/dchansen/gadgetron_pybind) for details) if you're feeling adventurous.

**Comment by hansenms** [comment]
We used to have the ability to "instrument" a Gadget in Python. So you could effectively build a Gadget chain in Python and it could be a mix of Python and C++ Gadgets. If you look at version 3, we had a WrapperGadget:

https://github.com/gadgetron/gadgetron/blob/Gadgetron3.17/gadgets/python/gadgets/gadgetron.py

And I once did some gymnastics for the ISMRM to show how it worked.
