### ISSUE TITLE
Cuda device # not being passed correctly to downstream gadgets

### ISSUE THREAD

**Issue by ahsanjav** [gadgetron/gadgetron#886]
I am passing a buffer with cuNDArrays in it but noticed that the device number on variables received downstream is always zero - This seems to be a bug.

**Comment by hansenms** [comment]
@dchansen was this investigated?

**Comment by dchansen** [comment]
No - I don't have any multi-GPU systems available to me.

**Comment by hansenms** [comment]
OK, I can probably spin something up to test this. @ahsanjav can you provide me with a way to repro this?

**Comment by hansenms** [comment]
@ahsanjav do you have some kind of repro we can test for this? Otherwise, I suggest we close this.

**Comment by hansenms** [comment]
Closing this until we have a repro.

**Comment by ahsanjav** [comment]
This was resolved by David.
