### ISSUE TITLE
GT compilation issues in debug mode

### ISSUE THREAD

**Issue by ahsanjav** [gadgetron/gadgetron#889]
I am unable to compile GT in debug mode with gcc-9.3 on ubuntu 20.04. 

It seems to be having trouble with linking some files . I can compile just fine in release mode though. 

I am compiling using 'cmake ../ -G Ninja` followed by `ninja` .  Attached is the log file from where the compilation begins to fail.

[gt_log.log](https://github.com/gadgetron/gadgetron/files/5251964/gt_log.log)

**Comment by dchansen** [comment]
This was a bug in the NFFT code. It's fixed in the latest commit
