### ISSUE TITLE
DLL Loading Error in 4.x on Linux

### ISSUE THREAD

**Issue by MalteRoehl** [gadgetron/gadgetron#891]
I was trying to update my recon chain that is written in 3.17 to 4.x. This was mostly since I believe to have a memory leak behaviour in the NFFT library and hoped that with the update this might already have been fixed. I now build gadgetron based on the 20.04 Ubuntu docker image and install my gadgets from a separate source tree. I modified my cmake script according to the newest version and are able to build my gadgets and install them in the according places. However if I then start the gadetron and run a simple recon chain with just one new gadget I get following error.

09-24 09:10:48.392 DEBUG [Stream.cpp:52] Loading Gadget DiscardValue of class SpiralDiscardValueGadget from gadgetron_spiral_util_gadgets
terminate called after throwing an instance of 'std::runtime_error'
  what():  locale::facet::_S_create_c_locale name not valid
Aborted (core dumped)

So I attached a debugger and investigated and found that as the error suggest something in the dll loading process fails.
I was wondering if anyone had a similar behaviour and could help me out since I am a bit stuck with this.
Thanks a lot in advance.
Malte

PS: I attached the cmake file that is responsible for building that specific target
[CMakeLists.txt](https://github.com/gadgetron/gadgetron/files/5274828/CMakeLists.txt)

**Comment by dchansen** [comment]
There could be a ton of different reasons, but they are hard to debug without seeing your code.

In your gadget chain xml, try using "libgadgetron_spiral_utils_gadget.so", rather than "gadgetron_spiral_utils_gadget". That should give you a clearer error message (hopefully).

**Comment by dchansen** [comment]
@MalteRoehl I'm closing this. Please open a new issue or create a post on [Discourse](https://gadgetron.discourse.group/) if you still have the issue.
