### ISSUE TITLE
Motion correction standalone

### ISSUE THREAD

**Issue by riep** [gadgetron/gadgetron#904]
Hi everyone,

All standalone motion correction seem to be corrupted CPU/GPU.

There are for instance problems in vector initalization:   
     int D=2;
     typename uint64d<D>::Type twos(2);  
This first index is set to 2 but the second stays at 0

I will try to inverstigate that,

Pierre

**Comment by dchansen** [comment]
Hey Pierre,

Your code example is not really making sense to me. 

`vector_td<size_t,2> twos(2);`

will initialize twos to [2,2] as expected. 
Could you give me a little more context?

**Comment by riep** [comment]
sorry it was a wrong copy
const typename uintd<D>::Type twos(2);

**Comment by riep** [comment]
When I was debuging it was not the case for some reason. I had no time to inverstigate that so far.
Does the standolone MOCO work for you ?
