### ISSUE TITLE
spiral_flag.cfg test not working

### ISSUE THREAD

**Issue by hansenms** [gadgetron/gadgetron#907]
Not quite sure if the `spiral_flag.cfg` integration test is supposed to pass, but it doesn't (at all). It was added by @dchansen in https://github.com/gadgetron/gadgetron/commit/9eca76be4d2ae9f166c116ebfd26053f389a44c8

It is the only integration test that I don't have passing at the moment.

**Comment by dchansen** [comment]
You're absolutely right. The spiral_flag.cfg test does not work, and is unlikely to ever work with the test data we currently have. It should be removed.

**Comment by hansenms** [comment]
I have removed it in #905
