### ISSUE TITLE
 range/v3/core.hpp Compilation failed on ubuntu 18.04 using either gcc 7 or gcc 8 

### ISSUE THREAD

**Issue by valeryozenne** [gadgetron/gadgetron#917]
Hi,

I'm still using ubuntu 18.04 and I tried to compile the last master version using gcc 7 or gcc 8 . I got the following message.

fatal error: range/v3/core.hpp: Aucun fichier ou dossier de ce type
 #include <range/v3/core.hpp>

cmake output looks fine :
In case someone know how to fix this error.
Best 
Valéry 

-- The CXX compiler identification is GNU 8.4.0
-- The C compiler identification is GNU 8.4.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for packages in : /usr/local
-- Found Git: /usr/bin/git (found version "2.17.1") 
64bit system is found
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
OpenMP multithreading enabled
-- Performing Test COMPILER_SUPPORTS_WRETURNTYPE
-- Performing Test COMPILER_SUPPORTS_WRETURNTYPE - Success
-- Performing Test COMPILER_SUPPORTS_WTERMINATE
-- Performing Test COMPILER_SUPPORTS_WTERMINATE - Success
-- Performing Test COMPILER_SUPPORT_WNON_VIRTUAL
-- Performing Test COMPILER_SUPPORT_WNON_VIRTUAL - Success
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   system
--   program_options
--   filesystem
--   timer
--   chrono
-- Found CUDA: /usr/local/cuda (found version "10.0") 
Compiling with  -arch=sm_30 -gencode arch=compute_30,code=sm_30 ;--std=c++17
-- Found Armadillo: /usr/include (found version "8.400.0") 
-- Found pugixml: /usr/lib/x86_64-linux-gnu/libpugixml.so  
-- HDF5: Using hdf5 compiler wrapper to determine C configuration
-- Found HDF5: /usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5.so;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/x86_64-linux-gnu/libsz.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libm.so (found version "1.10.0.1") found components:  C 
FFTW3 UNIX libraries: /usr/lib/x86_64-linux-gnu/libfftw3f.so/usr/lib/x86_64-linux-gnu/libfftw3.so
-- Found FFTW3: /usr/lib/x86_64-linux-gnu/libfftw3f.so  
-- Looking for sgemm_
-- Looking for sgemm_ - found
-- Found BLAS: /usr/lib/x86_64-linux-gnu/libopenblas.so  
OpenBLAS found
OPENBLAS_OMP_LIBRARIES OPENBLAS_OMP_LIBRARIES-NOTFOUND 
OMP OPENBLAS NOT FOUND
BLAS /usr/lib/x86_64-linux-gnu/libopenblas.so LAPACK 
-- Found CBLAS: /usr/lib/x86_64-linux-gnu/libopenblas.so  
-- Looking for cheev_
-- Looking for cheev_ - found
-- A library with LAPACK API found.
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- A library with LAPACK API found.
pkgconfig lapacke and 
-- Found LAPACKE: /usr/include  
-- Checking for module 'lapacke'
--   Found lapacke, version 3.7.1
OpenBLAS detected; setting max number of OpenBLAS pthreads to one.
Do not find TORCH_HOME
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.6m.so (found suitable version "3.6.9", minimum required is "3") 
Find numpy after python3
Find python 3
-- Found Python3: /usr/bin/python3.6 (found version "3.6.9") found components:  Interpreter 
-- Found NumPy: version "1.15.4" /usr/local/lib/python3.6/dist-packages/numpy/core/include
Find numpy 1.15.4 at /usr/local/lib/python3.6/dist-packages/numpy/core/include
Found numpy : /usr/local/lib/python3.6/dist-packages/numpy/core/include  /usr/include/python3.6m /usr/lib/x86_64-linux-gnu/libpython3.6m.so
Boost_VERSION 1.65.1
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   python3
Searching for OpenGL, GLEW, GLUT, and Qt. These libraries are only used in a single standalone application and are thus non-essential.
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libOpenGL.so   
GLEW NOT FOUND
-- Found GLUT: /usr/lib/x86_64-linux-gnu/libglut.so  
-- Looking for Q_WS_X11
-- Looking for Q_WS_X11 - found
-- Looking for Q_WS_WIN
-- Looking for Q_WS_WIN - not found
-- Looking for Q_WS_QWS
-- Looking for Q_WS_QWS - not found
-- Looking for Q_WS_MAC
-- Looking for Q_WS_MAC - not found
-- Found Qt4: /usr/bin/qmake-qt4 (found suitable version "4.8.7", minimum required is "4.6") 
PLplot is found at /usr/include/plplot
PLplot libraries: /usr/lib/x86_64-linux-gnu/libplplot.so;/usr/lib/x86_64-linux-gnu/libplplotcxx.so
Compiling cpu based optical flow registration toolbox.
Compiling gpu based optical flow registration toolbox.
Find python; build gadgetron toolbox python
PYTHON_INCLUDE_PATH is /usr/include/python3.6m
PYTHON_LIBRARIES is /usr/lib/x86_64-linux-gnu/libpython3.6m.so
NUMPY_INCLUDE_DIRS is /usr/local/lib/python3.6/dist-packages/numpy/core/include
Boost_LIBRARIES is /usr/lib/x86_64-linux-gnu/libboost_python3.so
Build python generic gadgets ... 
ZFP NOT Found
Build python cmr gadgets ... 
BART not found, NOT compiling bartgadget
Cuda found, compiling gpu accelerated gadgets
Compiling DICOM gadget
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   date_time
DCMTK 
Include: /usr/include
Libraries: dcmdata;oflog;ofstd;z;m;pthread
-- Found GTest: /usr/local/lib/libgtest.a  
GTEST FOUND: TRUE
-- LIBRARY_PATHS for chroot: /usr/local/lib:/usr/local/cuda/lib64:/usr/local/cuda/lib64:/usr/local/cuda/lib64
CPACK_PACKAGING_INSTALL_PREFIX: /usr/local
-- Found CPack generators: DEB
-- Configuring done
-- Generating done
-- Build files have been written to: /home/valery/Dev/gadgetron-4.1/build

**Comment by hansenms** [comment]
Have you tried installing librange from source? I think @dchansen said that was the workaround, but I have not tried. I will try to get an Ubuntu 18.04 Dockerfile up at some point, but I have been trying to get the testing running first.

**Comment by valeryozenne** [comment]
Hi Michael, 
Thanks , it is even simpler than suggested, I didn't know that the depencies has changed, sudo apt-get install -y librange-v3-dev fix the issue.
Issue can be closed

**Comment by hansenms** [comment]
@valeryozenne I am just looking into this again and I am wondering how you are getting it to compile. I agree the error about the missing header file can be made to go away as you describe, but I get lots of other errors on 18.04. Are you on the latest version of the source. 

@dchansen what we are seeing is this stuff:

```
../toolboxes/core/cpu/hoNDArray_utils.h: In function 'auto Gadgetron::concat_along_dimension(const COLL&, size_t)':
../toolboxes/core/cpu/hoNDArray_utils.h:1015:121: error: cannot deduce template arguments for 'logical_and' from ()
       bool all_dimensions_valid = ranges::accumulate(arrays | view::transform(dimensions_valid), true, std::logical_and() );
                                                                                                                         ^
../toolboxes/core/cpu/hoNDArray_utils.h:1020:61: error: 'views' has not been declared
       const size_t inner_stride = ranges::accumulate(dims | views::slice(size_t(0), dimension),
                                                             ^~~~~
../toolboxes/core/cpu/hoNDArray_utils.h:1021:81: error: cannot deduce template arguments for 'multiplies' from ()
                                                      size_t(1), std::multiplies());
                                                                                 ^
```

I have upgraded to gcc/g++ 8.4 but same issues.

**Comment by valeryozenne** [comment]
You are right Michael , once I wrote the message , I just show the next error you are pointing , I'm planning to talk about this subject at the next hangout.

By the way, we haven't had a chance to give greetings recently. The agenda is still a issue, but I hope we can organize a short meeting in January for informal discussion about you work at Microsoft (if it is not top secret) and the Gadgetron. I'm sure that will be of interest. Best, Valéry

**Comment by hansenms** [comment]
@valeryozenne we have this PR up: https://github.com/gadgetron/gadgetron/pull/921

It adds the 18.04 images back in and there is an install script for the dependencies, which should at least be a roadmap for you. The solution in the end was gcc/g++ 9 and install range v3 from source.
