### ISSUE TITLE
Dockerfile for Ubuntu 18.04

### ISSUE THREAD

**Issue by hansenms** [gadgetron/gadgetron#919]
We should re-introduce Dockerfile for Ubuntu 18.04. We will need to deal with the librange issue.

**Comment by dchansen** [comment]
Gadgetron compiles on Ubuntu 18.04 with gcc 10 and librange-v3 from github (I used the 0.11.0 release).

**Comment by hansenms** [comment]
Seems like gcc-10 is not supported on the nvidia/cuda images, and we are using gcc-9 for the Ubuntu 20.04 images, so I will experiment a bit. 

Tagging #921 for reference, I can see you did some pushes to that and I did some further fixing of some typos in the image names. I will continue to see if I can find my way through this.
