### ISSUE TITLE
Strange debug stream for every acquisition

### ISSUE THREAD

**Issue by ojosephs** [gadgetron/gadgetron#940]
When I use the noise adjust gadget with perform_noise_adjust = false (to just discard noise acquisitions) I get output from the following for every acquisition. Type is something like N9Type..., I don't remember exactly. Is this correct?

https://github.com/gadgetron/gadgetron/blob/f7ae2b29cef76b68a2e6820c33cb9ab4155bf8e2/gadgets/mri_core/NoiseAdjustGadget.cpp#L410

**Comment by dchansen** [comment]
No, the presence of the debug statement was a bug. It's fixed in [this pull request](https://github.com/gadgetron/gadgetron/pull/946)
