### ISSUE TITLE
[proposal][external language interface][cling] C++ gadget without compile

### ISSUE THREAD

**Issue by congzhangzh** [gadgetron/gadgetron#967]
Hi All,

As C++ with Interactive coding may be a good way to do high-performance computing、fast experiments and easy deploy process, maybe we can provide an external implement like python to support it.

1. implement the hook in gadgetron
2. implement the bootstrap code for client side, maybe copy or reuse some code from gadgetron core code
3. provide some sample on user side
4. provide the module to easy local debug if needed

### ref:
1. https://blog.llvm.org/posts/2020-12-21-interactive-cpp-for-data-science/
2. https://developer.nvidia.com/gtc/2020/video/s21588-vid
3. https://github.com/ComputationalRadiationPhysics/xeus-cling-cuda-container
4. https://github.com/root-project/cling/issues/115
5. https://github.com/jupyter-xeus/xeus-cling

Tks,
Cong

**Comment by dchansen** [comment]
Hi @congzhangzh,

Well we're always open for pull requests ;) 
Most of the required code is already in Gadgetron. We would have to create a simplified version of the server code, but most of  the building blocks are in [https://github.com/gadgetron/gadgetron/tree/master/core](core), with our iostream implementation in [https://github.com/gadgetron/gadgetron/blob/master/apps/gadgetron/connection/SocketStreamBuf.h](SocketStreamBuf).

We would have to make sure everything is tested, but none of it is unrealistic.

I'm happy to give advice, but I do not currently have the time to implement it.

**Comment by congzhangzh** [comment]
@dchansen ok, get it. I can try it lately.

**Comment by hansenms** [comment]
Closing this for now.
