### ISSUE TITLE
Install instructions seem incorrect for V4.1?

### ISSUE THREAD

**Issue by bwheelz36** [gadgetron/gadgetron#968]
I am trying to install on Ubuntu (i've tested both 20.04 and 18.04).
There are two wiki articles covering this:
[Linux Installation (Gadgetron 4)](https://github.com/gadgetron/gadgetron/wiki/Linux-Installation-(Gadgetron-4))
[Linux Installation (Gadgetron 3.17)](https://github.com/gadgetron/gadgetron/wiki/Linux-Installation-(Gadgetron-3.17))

Clearly these cover two different versions of Gadgetron, however both documents contain the exact same clone command:
git clone https://github.com/gadgetron/gadgetron.git

I assume that this should either point to a released version of code, or else there should be some further git commands to checkout the correct release?
When I tried to follow the instructions for gadgetron4, I got all sorts of build errors. When I used the released version 4.1 instead, everything appears to have built correctly.

**Comment by hansenms** [comment]
If you check out the git repo, you should get the latest tested version of the code. You should not need to checkout a specific branch (older version of the code). 

In order to help with the specific problem you are having, it would be good to know what failure you are seeing. We test every PR and merge on Ubuntu 20.04 and 18.04 so the latest master branch should work. 

You need to make sure that you have all the dependencies install....for Ubuntu there is a script that will do that: 

https://github.com/gadgetron/gadgetron/blob/master/docker/install_ubuntu_dependencies.sh

We also have Docker images that are already built, e.g.:

```bash
docker pull ghcr.io/gadgetron/gadgetron/gadgetron_ubuntu_2004:latest
```

or if you have a GPU:

```bash
docker pull ghcr.io/gadgetron/gadgetron/gadgetron_ubuntu_2004_cuda11_cudnn8:latest
```

**Comment by bwheelz36** [comment]
Hi @hansenms, 

thanks for the link to the dependency installer. I just tried that on a relatively 'fresh' install of ubuntu 20.04, and everything built. However, my broader point is: 

- if I follow instructions to install 4.1, they should install 4.1. If I follow instructions for 3.17, then that's what they should install.
- It seems that the instructions for 4.1 don't work with the most recent versions of code - so if you simply follow these installation instructions, they both install the 'wrong' version, and also don't work*.
- Am I looking in the wrong place for how to install? these seemed to be the most up to date instructions we could find, but it appears we should be using a procedure outlined in your answer above.

*Sorry I didn't provide more specific error messages - the problem is that once I get something to build, it's quite a bit of effort to get it to 'break' again, I have to uninstall all the dependencies...but, I could do that if it will be helpful? I think from memory the errors related to missing dependencies. 

I haven't explored the docker option yet, but I guess it might be the best option moving forward - i'm pretty sure on another system, I had issues because of contrasting cuda versions.

**Comment by hansenms** [comment]
@bwheelz36, I would say the documentation in general (on this project and many others ;)) is always out of date. For the most up to date recipe for installation, I would recommend looking at the install steps followed by the CI/CD system, which are captures in the Dockerfile and the artifacts utilized by the Docker builds. So there is not necessarily something wrong with your approach, but rather some documentation updating that should be done at some point, but I think there has been a lack of bandwidth to get that done.

The Docker images are the way to run it and have consistently been the way that the installation steps (on Linux) have been captured and tested.
