### ISSUE TITLE
bug in GenericReconFieldOfViewAdjustmentGadget?

### ISSUE THREAD

**Issue by kkamiya-rad** [gadgetron/gadgetron#970]
Dear Gadgetron experts,

here I report a possible bug in GenericReconFieldOfViewAdjustmentGadget with Gadgetron4.

Reconstruction with Generic_Cartesian_Grappa_EPI.xml resulted in a strange black line in the middle of the image. As advised by Nils in Gadgetron Discourse (https://gadgetron.discourse.group/t/artifact-in-genericcartesiangrappaepi-outputs/256), commenting out GenericReconFieldOfViewAdjustmentGadget resolved the black line.

I used gadgetron/ubuntu_2004 docker image to reconstruct SE-EPI diffusion scan with

siemens_to_ismrmrd -f meas_MID00419_FID277015_diffusion_ep2d_tra_4_Scan_Trace.dat -z 1 -m IsmrmrdParameterMap_Siemens.xml -x IsmrmrdParameterMap_Siemens_EPI.xsl -o trace_adj.h5
siemens_to_ismrmrd -f meas_MID00419_FID277015_diffusion_ep2d_tra_4_Scan_Trace.dat -z 2 -m IsmrmrdParameterMap_Siemens.xml -x IsmrmrdParameterMap_Siemens_EPI.xsl -o trace_data.h5
gadgetron_ismrmrd_client -f trace_adj.h5 -c default_measurement_dependencies.xml
gadgetron_ismrmrd_client -f trace_data.h5 -o trace_out.h5 -C ./Generic_Cartesian_Grappa_EPI.xml

I share the .dat file via Google drive below.
https://drive.google.com/file/d/1Do35qYhveRUZ_yoexL4i8di0JRlMF6Xp/view?usp=sharing

Kouhei

**Comment by dchansen** [comment]
Hey @kkamiya-rad 
I'm sorry for not looking into this sooner. I can't actually reproduce your bug on the latest version of Gadgetron. 
About 5 months ago, a bug was fixed in GenericReconFieldOfViewAdjustmentGadget, and without that fix I also get the error you're seeing.

Could you confirm that you're still getting the bug when using the latest Gadgetron? 
You can get it by running `docker pull ghcr.io/gadgetron/gadgetron/gadgetron_ubuntu_2004:latest`. Unfortunately our images on dockerhub are no longer up to date.

**Comment by dchansen** [comment]
On another note, would you be ok with us using this dataset for integration testing? That would mean us hosting it together with the rest of the test data, and checking every Gadgetron commit against it.

**Comment by kkamiya-rad** [comment]
Hi, David.

I tried the latest docker image you suggested, and the image was
reconstructed correctly with GenericReconFieldOfViewAdjustmentGadget. Thank
you so much!

It looks a bit tricky to correctly identify the up-to-date version. Could
you please also guide me which is the latest version in case of local
installation (not Docker, e.g.,  apt-get)?

Please feel free to use that data for your integration testing. It is
merely a very short, phantom scan. If I could contribute any, that would be
my pleasure.
***@***.***>

Best regards,
Kouhei


2021年4月22日(木) 23:05 David Christoffer Hansen ***@***.***>:

**Comment by dchansen** [comment]
Hi Kouhei,

Unfortunately we do not have an apt-get version that is always up to date. The one we used for the summer school is only updated sporadically. It is on our to-do list, but I don't have a time estimate for it.

Right now, the recommended method is to build directly from the source code.

Best regards,
David
