### ISSUE TITLE
Cannot find library in prebuilt docker containers

### ISSUE THREAD

**Issue by gkiar** [gadgetron/gadgetron#978]
Hi! I'm hoping to start using this project, and was planning to poke around and process some benchmark data via your docker containers, available here: https://hub.docker.com/r/gadgetron/ubuntu_2004_base_basic

However, when I launch the container, it looks like there is no code in `/opt/code`, and `pip3 show` suggests that `gadgetron` isn't installed within the container. It was unclear to me if this was intended as the base for later containers which actually contain the library, of if I was just missing something.

Also, I notice the tutorial on the website is flagged as "out of date", so wondered where a good place to start might be.

Thanks!

**Comment by hansenms** [comment]
Please use the latest [github published](https://github.com/orgs/gadgetron/packages?repo_name=gadgetron) images, e.g.:

```
docker pull ghcr.io/gadgetron/gadgetron/gadgetron_ubuntu_2004:latest
```
